### ISSUE TITLE
No package ‘popt’ found.

### ISSUE THREAD

**Issue by FinlayMc** [mikebrady/shairport-sync#1003]
Similar issue as in the past: https://github.com/mikebrady/shairport-sync-for-openwrt/issues/10

**Comment by mikebrady** [comment]
That’s pretty cryptic. Could you take a look at the [REPORTING ISSUES.md](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md) page please?

**Comment by FinlayMc** [comment]
Apologies, I am fairly new to github and these kinds of projects. 

I am trying to set up shairport-sync on a raspberry-pi 2. I was following the steps in this guide online: https://pimylifeup.com/raspberry-pi-airplay-receiver/comment-page-2/?unapproved=26792&moderation-hash=a405ee7041ae9c23e2388d5650ec4ba4#comment-26792

When I tried to run the command:

'''
./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata

'''
It resulted in the issue:

No package 'popt' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables POPT_CFLAGS
and POPT_LIBS to avoid the need to call pkg-config.

Tried running:

'''

sudo systemctl status shairport-sync

'''

but results in:

Unit shairport-sync.service could not be found.


I'm unsure what information you might need, I am running Linux kernel version 4.19.97-v7+
If there is anything I can run to get you information just let me know.

Thanks

**Comment by mikebrady** [comment]
Many thanks. I updated the post for format – I hope that's okay.

Anyhow, the reason for the problem is that, while locating all the components with which to build Shairport Sync, the build system could not find the library containing the `popt` facilities.

Assuming you are using the standard Raspberry Pi operating system Raspbian, the most likely explanation is that you might have skipped over some of the commands in Step 2 of the guide you are following – is that a possibility?

Actually, dare I say it, there is a better guide at [INSTALL.md](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md). The key thing is to follow each the steps meticulously. 

BTW, the issue you referenced is rather old, and is for OpenWrt, a very compact version of Linux targeted at small low-power linux devices, very different to Raspbian.

When you build something for OpenWrt, you usually build it with a set of tools running in a more complete Linux system on a much more capable machine. Raspbian, on the other hand, is quite complete, and you can build stuff like Shairport Sync for Rasbpian directly on a Raspbian system.

**Comment by FinlayMc** [comment]
Ah damn, yeah you are correct. I had not entered a full command in step 2 due to the scroll bar at the bottom. That was stupid of me, sorry. 

ah excellent, that guide does look better, thanks.

Ah ok, I had not realised that, sorry. That makes a lot of sense now.

Issued solved anyway, all working. Can't wait to finally get this all set up and working. Fantastic package this. Thank you very much
