### ISSUE TITLE
Devices fail to connect

### ISSUE THREAD

**Issue by ncitro** [mikebrady/shairport-sync#1021]
I have installed Shairport and seems to run properly, but my devices cannot connect. I see the Pi in the list of airplay choices, but I get "unable to connect" when I try to airplay to them. I have two iPhones and two iPads in the house as well as a PC running iTunes and a MacBook Pro as well as a MacMini. All have the same issue. The iOS devices are wireless (obviously), the MB, MM, PC, and PI are wired. I am running a Ubiquiti USG router and wireless access points. I thought possibly a network issue (although all devices can airplay to my AppleTV with no issue), so I direct connected the MB and PI with static IP addresses. I still see the PI as an Airplay choice, but again get "unable to connect". I have also disabled the firewall in the MB. Given it was the direct connect, I cannot see how it could be a network issue, but I am at my wits end. 

Any suggestions or help would be much appreciated.

Thank you,

**Comment by mikebrady** [comment]
Thanks for the post. The fact the the problem is so consistent hopefully makes it easier to troubleshoot.

There are some hints in [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md). From your report, it seems that Shairport Sync is running on a Raspberry Pi – it would be nice to have a [bit more information](https://github.com/mikebrady/shairport-sync/blob/master/REPORTING%20ISSUES.md).

Are you accessing the Pi via WiFi? If so, ensure power management is off. Another possibility is a firewall issue – is there a firewall running on the Pi itself?

**Comment by ncitro** [comment]
That rung a bell for me. I am using a Pi from another project and I had enabled the firewall. I disabled it and it works great! Thank you so much!!
