### ISSUE TITLE
shairport on raspberry pi not showing up in MacOs Catalina

### ISSUE THREAD

**Issue by r0held** [mikebrady/shairport-sync#1024]
Hi

I installed shairport on a raspberry pi 2 model b and so far it works great, I can access it via iPhones running iOS12, iOS13 and AppleTV HD running tvOS13. However, I'm not able to connect to it via MacBook running Catalina 10.15.5 (2 different machines) because it's not showing up as an output device in the sound preferences or in the app Music (former iTunes). The AppleTV however is available in also selectable. Is this a known issue? Thanks for any help

Cheers
r0held

**Comment by mikebrady** [comment]
Thanks for the post. This is probably not an issue with Shairport Sync itself. Let me suggest you look through the [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/master/TROUBLESHOOTING.md) guide for some suggestions. At a guess, it sounds like a firewall or network problem.

**Comment by EmperiuM666** [comment]
@r0held try to reboot your computer, when I first move to Catalina it happened the same to me. Shairport-sync appear on my iPhone 11 pro with iOS 13.5.1 but. no on my macOS Catalina 10.15.5. My first try was to disable and reenable airport (because, sometimes, airport on macbooks are a little bit tricky) bit nothing different happened, but when I reboot my macbook and also the rPI the problem was solved.

**Comment by r0held** [comment]
Hi @mikebrady 

thanks for your reply and first of all for the great work you've done (this should've been in my first post already!). I'm pretty sure that it is not an issue with shairport sync itself because it works at least with one device and there without any problems.
I also tried to reboot several times all system as advised by @EmperiuM666 but unfortunately this didn't solve the problem either.
What I realised is that currently only my iPhone with iOS 12 shows me the airplay speakers and the AppleTV. Another iPhone with iOS 13 and both MacBooks with OSX 10.15 don't show the speaker in any menu. I wonder if I installed and outdated version of shareport sync or if I did a mistake in setting it up or if this is maybe related to Airplay 2?
I'm surprised that I couldn't find any other complaining of shairport sync and catalina so my guess is that I did something wrong. Any help is more than welcome

**Comment by mikebrady** [comment]
Thanks for the kind words. It's extremely unlikely that the non-appearance of Shairport Sync is due to an out of date version. It's much more likely to be some kind of network or firewall problem. 

BTW, I'm assuming all the time that your Pi is connected over only one network connection – either WiFi or Ethernet, not both. 

There is a free app both for iOS and macOS called "Discovery" by TildeSoft. It will show you what Bonjour/Zeroconf information your iOS/Mac device can see on the network. To see AirPlay, it should see services with the code `_raop._tcp`. Here is an extract from what my Mac can see:

![image](https://user-images.githubusercontent.com/4265913/85234787-cb7da000-b407-11ea-97f1-7f963435cd6f.png)

On the Shairport Sync device, there is a utility called `avahi-browse`, part of the `avahi-tools` package, that allows you to see the same information. So, you could check that the `_raop._tcp` information is being produced by Shairport Sync.

If you can't see something like this on your iOS/macOS device, and if it's being produced by the Shairport Sync player, then it's not getting through and it being lost somewhere.

**Comment by r0held** [comment]
Hi @mikebrady 

I forgot to mention something important which is that I use my raspberry also as a gateway for VPN connection and it seems that this is causing the problem (which is completely in line with your thoughts that something is not set up properly in the network...). Sorry for not mentioning this, I just didn't think about that as a possible source of failure because I had openVPN running and in parallel I could connect with my iOS12 cellphone and the AppleTV (which uses the VPN connection through the pi), so it worked for some devices. After the openVPN crashed airplay was accessible by all machines in the local network. 
I guess I can close this thread here and have to find a solution how to use shairport sync for the local network and run a VPN gateway on the same raspberry. If you have any hint how to set this up correctly, would be nice, but this is not really related to Shairport Sync.
Thanks for your help!

**Comment by calvincorrieri** [comment]
What's interesting is that on Catalina, if you use the Music (iTunes) app to airplay music, the shairport speaker does show up. However it does not show up anywhere else. So Catalina is obviously aware of the speaker and is able to play to it just fine (I tested it myself) so it's got to be some Apple bs trying to force people to buy Apple TV's instead of using alternatives like this. If anyone thinks of a way to defeat this mechanism that seems to be built into macOS Catalina, send me an email at nutsackula@gmail.com

**Comment by mikebrady** [comment]
See #1402.
