### ISSUE TITLE
MPRIS Quit() method does not quit properly

### ISSUE THREAD

**Issue by jgabriel98** [mikebrady/shairport-sync#1028]
When you call at the `Quit()` method from the `MPRIS2` implementation, the player gets into some kind of "limbo":

It disconnects the current connected device (this is ok), but then neither finishes the process nor becomes available to new connections.

So after calling `Quit()`, you can't try to connect again later to Shairport Sync with any workaround, because there is no signal/evidence that the process should be restarted, and it cannot reconnect to a device after calling `Quit()`.

I think that Shairport Sync should become available to new connections after calling `Quit()`, or finish the process (I think that this is less preferable).

[edited a tiny bit]

**Comment by mikebrady** [comment]
Thanks for the post.

The `MPRIS` `Quit()` method is meant to terminate the "media player" – see [here](https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:CanQuit). 
That's what it does, or rather that is what it is intended to do. In fact, due to some errors, it was asking the `shairport-sync` player to terminate, but the program was left in a "defunct" or zombie mode. This is now fixed in the current `development` branch, so the `shairport-sync` program now terminates properly. Thanks for drawing attention to these issues.

Maybe the `Quit()` facility does not make sense in the case of Shairport Sync. It really seems that the term "media player" refers to something like iTunes rather than Shairport Sync itself. So maybe the `CanQuit` property should be set to false...

**Comment by jgabriel98** [comment]
I see, makes sense.

Thanks for the quick and clear reply.

I think that Quit() should be kept, since is the only way to stop a connection in mpris.

Or is there any other way to disconnect the current device using MPRIS?

And what about using other ways, like signaling to the shairport running process, is there any?

**Comment by mikebrady** [comment]
Shairport Sync can act as an intermediary between an `MPRIS` client and the music source, e.g. iOS, so that when you issue a command like `Play()` or `Stop()`, Shairport Sync passes an appropriate remote-control command to the player, (which BTW is called the "client", where Shairport Sync is an AirPlay "server"). When you pause or stop, the connection is dropped after a few seconds determined by the player.

While iOS and iTunes generally respond to remote control commands, recent versions of the macOS Music app do not. It may be that Shairport Sync will have to do some kind of authentication to make it work on the macOS Music app, but as of now, it doesn't work.

**Comment by jgabriel98** [comment]
Makes sense now why when i've called Stop(), my iphone said it was still connected but would stop propely working.

Thanks for all the clarification, saved me a lot of time.

If it depends in me, this issue can be closed. And maybe marked as informational? (because of the info about how Stop() works and the problem with macOS Music app)
