### ISSUE TITLE
Add support for 16000 Mhz?

### ISSUE THREAD

**Issue by flatsiedatsie** [mikebrady/shairport-sync#1036]
I am currently using Shairport with a ReSpeaker USB microphone array, which has a built in USB sound card. This microphone has a cool feature: it can filter the music out of the audio it's capturing. By 'subtracting' the outgoing music stream from the incoming capture stream, this device can accurately pick up voice commands even while the music is playing.

Because of this feature, the device does come with a limitation: it [only supports 16Khz audio output](https://github.com/respeaker/usb_4_mic_array/issues/9). Unfortunately, the lowest what Shairport supports is 44Khz. This is probably why I [ran into an issue](https://github.com/mikebrady/shairport-sync/issues/1035) using direct hardware output, as is normally suggested.

I managed to overcome that issue by using `plughw` instead of `hw`. Still, I was wondering if it would be an idea to also support 16Khz?

**Comment by mikebrady** [comment]
Thanks for the post. It's an interesting application of Shairport Sync.

Regarding the sample rate -- AirPlay runs at 44,100 frames per second (fps), so Shairport Sync runs at 44,100 or multiples thereof.  Audio is transported through AirPlay losslessly, so Shairport Sync is designed is to pass audio as cleanly as possible, with an absolute minimum of modification.

The only modifications made to audio passing through Shairport Sync are due to do occasional synchronisation -- adding or removing a frame -- or to implement volume control where a hardware mixer is not available. Apart from this, Shairport Sync does nothing else, so adding transcoding would be a pretty big change in scope. In the circumstances, respectfully, I don't think it's a great idea.

As far as I know -- not being a ALSA plugins expert -- you can chain ALSA plugins together, so that you could have a transcoder plugin at 44,100 fps being fed by Shairport Sync and outputting at 16,000 fps, in turn feeding a mixer plugin to splice in a 16,000 fps microphone feed, going eventually to the output device. Another possibility is to take output from Shairport Sync via a unix named pipe and then process that through an ALSA plugin chain.

**Comment by flatsiedatsie** [comment]
Thanks for the reply and the explanation. Very interesting, and I totally understand that adding transcoding is out of scope.

You're right, in most cases this could simply be solved with a pass-through in an ALSA config file.

Unfortunately in my situation, where the software runs as an addon for the Mozilla Webthings Gateway, I'm not allowed to make any changes to the ALSA config file. This is because doing so could create trouble for other addons that are also using audio output. If each addon would make changes, things would become a mess. So Mozilla's solution is that nobody can.

Piping the output from Shairport into another program that downsamples it sounds interesting. Addons are allowed to run their own binaries if they can run without installing extra libraries. This it how Shairport is run, with a local copy of `libconfig.so.9` in the [same directory](https://github.com/flatsiedatsie/airport/tree/master/shairport), and [using LD_LIBRARY_PATH](https://github.com/flatsiedatsie/airport/blob/f7ceeb3180b32040aaac6c6c6e6689b7da8893a0/pkg/airport.py#L80) to change in which directory Shairport looks for that one file.

Would you by chance have a suggestion on which application could be used for piping through live transcoding?

**Comment by mikebrady** [comment]
I think [SoX](http://sox.sourceforge.net) might be worth checking out.
