### ISSUE TITLE
Shairport / PulseAudio - moving sink to a combined output results in stuttering audio output

### ISSUE THREAD

**Issue by fm1234** [mikebrady/shairport-sync#1049]
Hello Mike and community,

thanks for all your effort you are putting into Shairport!

I have the following portion in my shairport config file
```
pa = {
	sink = "alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo";
};
```
which uses the defined USB soundcard as a PulseAudio output.
That is working great.
However, when I define a new combined output with

`pacmd load-module module-combine-sink sink_name=vSink sink_properties=device.description=CombinationSink slaves=alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo,alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_DAC-00.analog-stereo.2`

and then move the stream to that sink

`pacmd move-sink-input 0 4`

I hear stuttering audio output on the newly created sink.

However, if I define the combined sink before starting Shairport and use that sink in Shairport's configuration file, everything works fine. It seems like this is just an issue with moved sinks.

If I do the same with mplayer playing a MP3 file, everything works as expected so I guess it might be related to Shairport?

Thanks for your help!
Freddy

**Comment by mikebrady** [comment]
Thanks for the intriguing post.

Offhand, I don't know the cause of the issue. For a bit of background, Shairport Sync is more demanding of the output than, say, `mplayer`, because it is constantly checking the output device latency -- the length of time it will take to output a frame of audio through the output buffers, etc. Applications like `mplayer` do not need to monitor device latency, since they are not concerned with synchronisation. So an obvious question is whether the `PulseAudio` system does a good job reporting device latency.

When you change the configuration of the output sink while Shairport Sync is using it, there could be a step change in the device latency. Shairport Sync _should_ be able to handle that, but I'll see if I can look into it.

**Comment by mikebrady** [comment]
Hi there. I may have discovered an issue that might be what you are detecting, and I have pushed out an update in the `development` branch with a potential fix. If you got a chance to try it out and let us know if the problem has been rectified, it would be appreciated.

**Comment by fm1234** [comment]
Hi Mike,

thanks for fixing the issue.
I just pulled the development branch so I got:
`3.3.7d16-OpenSSL-Avahi-pa-sysconfdir:/usr/local/etc`
and tried the abovementioned steps again - it's working perfectly!

Thanks a lot - is there a way to at least donate a beer to you? I'd be more than happy to do that 👍 

Take care and thanks again!
Freddy

**Comment by mikebrady** [comment]
Great. I’m glad to hear that it worked — I came across it in relation to an issue with the `alsa` back end. FYI there is a Sponsor button on the main Shairport Sync, but it’s really not necessary.
