### ISSUE TITLE
Network visibility issue on a Rasp. Pi (piCoreplayer) installation

### ISSUE THREAD

**Issue by skrzyp6** [mikebrady/shairport-sync#1098]
I apologize in advance if this issue has been addressed, but I have gone through the troubleshooting tips as well as searches here and on the piCoreplayer support forum.

I am running version 3.3.7rc2 on a Raspberry Pi 3b+ running piCoreplayer v6.1.0 (also running the squeezelite player). All wired connections (wifi off). Here's the issue: on initial boot (or anytime I restart the shairport daemon),  airplay is visible on the pi and plays normally through my system (USB DAC). After a brief period of inactivity, or seemingly anytime I browse network-available airplay devices (I have some Apple TVs & Airport Express units), the pi player disappears from the airplay device list on computers & my iPhone. It doesn't re-appear without restarting the service. Shairport-sync keeps running, and the standard log doesn't reveal any issues. I just can't see the player on the network. Here's the the start-up command string:

```
/usr/local/sbin/shairport-sync -a SPlayer-Airplay -o alsa -S soxr -d -- -d
```

I'd appreciate any thoughts. I realize that piCoreplayer use may not be too prevalent.

**Comment by rstcologne** [comment]
I have the same issue with a similar setup just a raspberry zero w. Happy to support any troubleshooting or testing.

**Comment by idlira** [comment]
I have the exact same problem, and made some extra digging: hope it can be useful.

When it disappears, I can no longer ping the host using the `hostname.local`, as it would stop advertising itself after 1 minute or so. Restarting the service makes it visible again. While it's visible, I can play music through it.

`avahi-browse -a` shows the service in the right interface.

I'm running on a fresh install: 3.3.8rc1-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc on a pi zero w + USB ethernet adapter. Only `eth0` available. The network connection do not drop as while this happens, I'm constantly connected to it via ssh.

On the same router I also have an AppleTV (which never disappears), and since the pi shows up after restart, I can assume that is not a router-multicast problem.

I can reproduce it at pretty much anytime, so appreciate if I can help with any troubleshooting.

**Comment by idlira** [comment]
One more update: using the `wlan0` interface always work. Seems to be strongly related to this USB Ethernet adapter.

**Comment by aahlberga** [comment]
I'm having a very similar issue that's been persistent for several months. Running 4x Pi 4s and 1x Pi 0W.  All have been updated to PiCorePlayer v 7 and all the latest Shairport and Squeezelite versions.  All running wireless, as wired is not an option for most of these endpoints).  

Airplay visibility drops off a few minutes after a shairport/squeezelite restart.  Squeezelite still works instantaneously when playing off LMS.  

I've tried `sudo iwconfig wlan0 power off` and have confirmed that `Power Management:off`.  I've also tried putting that command into the "User Commands" under "Tweaks" in the PiCorePlayer's settings so that this command is run on every startup.  

I've also tried setting the "Close output setting" to 0 in Squeezelite settings to keep output on, but am unsure if this is getting at the root of the problem.  

Per @idlira I have also tried `sudo ifconfig wlan0 promisc` with no success.  However, I will note that upon restart, promiscuous mode is no longer on.  

Happy to help with more testing or ideas, I have just enough terminal experience to be dangerous.

**Comment by chincheta0815** [comment]
Hej there,
I got the same issue.
After starting shairport-sync with the command-line
`/usr/local/sbin/shairport-sync -a TEST-Airplay -o alsa -S soxr -vvv -- -d hw:CARD=sndrpihifiberry` (I added most verbose)
I got some error messages that deal with tinysvcmdns.
The most prominent one
         `0.000860000 "tinysvcmdns.c:1341" skipping unicast query
         0.001151000 "tinysvcmdns.c:1386"
         1.004858000 "tinysvcmdns.c:1504" data from=192.168.47.88 size=369
         0.003429000 "tinysvcmdns.c:756" rr_data_len goes beyond packet buffer: 4500 > 254
         0.003192000 "tinysvcmdns.c:894" error parsing answer #0
         0.298273000 "tinysvcmdns.c:1504" data from=192.168.47.88 size=90
         0.003210000 "tinysvcmdns.c:1326" flags = 0000, qn = 4, ans = 0, add = 1`
(192.168.47.88 is the iPhone with iOS 14.4)

I thought of changing the mdns backend, bit piCorePlayer simply comes with tinysvcmdns...
And as it seems declaring that backend manually via the command-line "-m tinysvcmdns" did not work at all...

Is there any hint for a possible solution?

**Comment by mikebrady** [comment]
Thanks for the reports, and apologies for neglecting this issue. If people could report the configuration string that results from:
```
$ shairport-sync -V
```
that would be very helpful.

@chincheta0815, thanks for your logs and some useful ideas. It does look like `tinysvcmdns` has reached its limits; it doesn't seem to have been designed for more recent uses of mDNS. If there was a way of transitioning to Avahi, it would be a step forward. (BTW, is Avahi not supported in piCorePlayer?)

**Comment by mikebrady** [comment]
> One more update: using the `wlan0` interface always work.
> Managed to fix it for the `eth0` adapter by setting it in promiscuous mode.
> 
> ```
> # ip link set eth0 promisc on
> ```

Apologies for coming to this so late. Does this fix continue to work?

**Comment by chincheta0815** [comment]
> @chincheta0815, thanks for your logs and some useful ideas. It does look like `tinysvcmdns` has reached its limits; it doesn't seem to have been designed for more recent uses of mDNS. If there was a way of transitioning to Avahi, it would be a step forward. (BTW, is Avahi not supported in piCorePlayer?)
First of all thank you for your help and time.  I appreciate your help a lot.
Here is the configuration string of piCorePlayer: 3.3.7rc2-libdaemon-OpenSSL-tinysvcmdns-ALSA-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc

Concerning piCorePlayer and shaiport-sync I also thought of using avahi. Especially as the devs of PiCorePlayer compiled their own shairport-sync (without avahi) and their own lightweight mdnsd. I assume it's because they want their system as lean as possible.

After your comment I will contact them and link to this issue here. Anyways, there is a different application to shairport-sync that also uses tinysvcmdns. This one works well. Maybe this helps you: https://github.com/philippe44/TinySVCmDNS

What do you think: Does it make sense to change the PiCore extension package as this seems to be more future-proof?

**Comment by skrzyp6** [comment]
I never solved this, and was reluctant to try the "promiscuous" ethernet option. Here's my current config string:


shairport-sync -V
3.3.7rc2-libdaemon-OpenSSL-tinysvcmdns-ALSA-stdout-pipe-soxr-metadata-sysconfdir:/usr/local/etc

**Comment by mikebrady** [comment]
Thanks. Further to the most recent comments, have you tried it with `Avahi` rather than `tinysvcmdns`?

**Comment by chincheta0815** [comment]
On a plain raspberry pi os with a raspi zero it works like a charm now using avahi. I just installed via apt. Although the rest was quite an effort and I hope that overlayfs allows just pulling the plug...

Anyway: shairport-sync's debian raspi package for buster should just install the systemd service. There is also a SysV script that was not needed and simply confuses the system and the user. In the systemd service file the Unit-Type (=forked) must be deleted to make it finally startup.

**Comment by mikebrady** [comment]
Thanks for the update.

**Comment by chincheta0815** [comment]
@mikebrady Just as an info: I wrote with some PiCorePlayer dev. The thing why they do not (want to) use avahi is that avhi os too big and has too much dependencies. That is why they compiled their own mdns daemon based on tinysvcmdns and why they use tinysvcmdns. Do you see any chance that you can/want to fix that bug/issue I encountered? Or do you tink the time for the tinysvcmdns backend has come?

**Comment by fesc2000** [comment]
I have the same issue on an embedded setup (using buildroot and with version 3.3.5). The issue was that whenever i switched on my AppleTV, the shairport service vanished as audio option from the devices, and i had to restart shairport.

When enabling logging i noticed error messages like "rr_data_len goes beyond packet buffer". Lokking at the packet, all the parsing in mdns_parse_rr seemed to be shifted by 2 bytes (the two name bytes where not being taken into account).
This patch resolved it.

--- shairport-sync-orig/tinysvcmdns.c   2021-06-20 15:33:08.354377744 +0200
+++ shairport-sync-3.3.5/tinysvcmdns.c  2021-06-20 15:34:22.182620523 +0200
@@ -737,6 +737,7 @@
 
   // parse the MDNS RR section  p += label_len(pkt_buf, pkt_len, off);
   rr->name = name;
+  p += sizeof(uint16_t);
 
   rr->type = mdns_read_u16(p);
   p += sizeof(uint16_t);

**Comment by skrzyp6** [comment]
Follow-up: I have upgraded my players to PCP version 8 (including reinstalling all packages), and this issue remains for my IOS devices. I can see that a patch has been posted, but since I don't have the facilities to build & patch shairport-sync from source, I guess this won't help until the "official" package is patched. I have Volumio running on local players and shairport-sync works flawlessly for those, so I'm pretty sure it's a PCP issue...
