### ISSUE TITLE
Since iOS 14, Airplay not showing on iphone and ipad.

### ISSUE THREAD

**Issue by bangelischan** [mikebrady/shairport-sync#1101]
Everything seems to be installed right, the service is started, but for some reasons, the pi is not showing in the airpplay menu on iphone, ipad.

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync is working fine with iOS 14. Let me suggest you check out the Troubleshooting page.

**Comment by nupfel** [comment]
I have the same issue on iOS 14.2.1, no shairport-sync is showing anymore

**Comment by minix1234** [comment]
you should post more detailed info regarding your setup and shairport-sync build.

it will assist in more people lending their experience to help resolve your issues.

**Comment by brycied00d** [comment]
I seem to be suffering the same issue.

* shairport-sync 3.3.7
  * Same issue with shairplay and RPiPlay
* shairport-sync is running on my desktop (Arch Linux), connected directly by Ethernet.
  * `shairport-sync -v --name Desktop --output pa --use-stderr -m avahi --statistics`
  * I've also tried with `-m dns-sd`
  * There is no firewall running on my desktop.
  * `systemd-resolved.service` is disabled
* iPadOS 14.3 and 14.4
  * No idea about previous versions.
* Still works with iTunes 12.8.2.3 (OSX El Cap, 10.11.6 - Yeah, it's old, it's an 12 year-old laptop)
  * Shows up in the list, no issues with playback.
  * Tested with both wired Ethernet, and WiFi (same network).
* iPad does see, and works fine with other AirPlay devices on my network, specifically a set of Sonos speakers.
* Home network is dual-stack (IPv4 and IPv6)
* WiFi AP is a Unifi AP AC-Lite, firmware 4.3.24.11355
* `avahi-daemon` is running with a stock configuration.
  * I've also tried enabling the reflector (just trying random ideas), no luck.
* tcpdump and Wireshark both show the expected mDNS announcements from `shairport-sync`, as well as queries from the iPad and responses
  * The announcements from `shairport-sync` appear, at first glance, essentially identical to the announcements from the Sonos device.

The really puzzling thing is that it has appeared in the AirPlay list twice (out of looking a few hundred times). Unfortunately, both times that I tried, it spun for about 30 seconds and gave a connection error. There was no output from `shairport-sync` during this.

So maybe iOS is looking for something specific in the mDNS announcement, something it didn't used to.

Any other suggestions on what to look at? The issue seems to be squarely on the device itself which is unfortunate as it's a black box, no extra details or logs to be had beyond "it's not listed."

**Comment by brycied00d** [comment]
Following up to say that I tested a few other ideas specifically focused on determining why iOS was happy with the Sonos announcements (I assume it's happy, it lists it). I attempted to reproduce the mDNS announcements from the Sonos identically using `avahi-publish` with just the names and guid values changed. Sadly, no luck, iOS did not list my "spoofed" announcements so there's apparently something else still missing. (iTunes did, in fact, list my `avahi-publish`ed entry)

Commands:
```sh
avahi-publish -s DesktopTest _airplay._tcp 5000 model=Shairport-Sync deviceid=70:85:c2:d5:69:80 serialNumber=70-85-c2-d5-69-80 "acl=0" "features=0x445F8A00,0x1C340" "rsf=0x0" "fv=p20.61.1-83220" "flags=0x404" "manufacturer=Sonos" "protovers=1.1" "srcvers=366.0" "pi=7f6d9ee5-ffff-4216-bbb3-c461bd425896" "gid=7f6d9ee5-ffff-4216-bbb3-c461bd425896" "gcgl=0" "pk="
avahi-publish -s 7085C2D56980@DesktopTest _raop._tcp 5000 "cn=0,1" "da=true" "et=0,4" "ft=0x445F8A00,0x1C340" "fv=p20.61.1-83220" "md=0,1,2" "am=SYMFONISK" "sf=0x404" "tp=UDP" "vn=65537" "vs=366.0" "pk=28b4f019ec430e19eb6be0fd441adbf24296b559a17dd7fa609b2ca3128037e3"
```

**Comment by brycied00d** [comment]
My issues turned out to be rooted in my Unifi UAP, see #1116.

**Comment by arobertn** [comment]
I too have been experiencing this issue. Things worked fine on iOS 14.1 and 14.2, then failed intermittently on 14.3 (and usually a reboot of the iPad or at worst, Reset Networking, would fix it), and now fail completely and irretrievably on iOS 14.4. My Apple TV 3 also fails to show up, so I suspect it's not a problem with Shairport, but rather with Apple dropping support for (or at least not testing) Airplay 1. I am reporting an issue to Apple Feedback now, but don't expect any response. I don't know what is different in the Airplay 2 protocol; is there any chance Shairport[-sync] will support it?

**Comment by koningskruid** [comment]
I had the same problem, you guided me to the cause: Upgrade to iOS 14.3 in combination with a quite buggy access point (Cisco E2000). 

Using an other access point for the iOS device (my rpi is connected wired) solved the problem.

**Comment by arobertn** [comment]
Hmm. In my case I also found another factor. My iPad Air 2 on iOS 14 fails to see the Airplay devices but my 2018 iPad Pro running the same OS sees them fine. Not sure if it's a hardware thing or some kind of configuration state the older iPad has gotten into. But iOS 14 must have made some part of the Airplay discovery process more brittle.
