### ISSUE TITLE
Issues with PulseAudio running on boot on Raspberry Pi 4

### ISSUE THREAD

**Issue by techwiz001** [mikebrady/shairport-sync#1124]
Hello, 
I have attempted to install Shairport-Sync on a Raspberry Pi 4 using the newest release of Raspbian, which utilizes PulseAudio. 
The program works correctly when I execute it on the command line, but the systemd service fails with "fatal error: failed to connect to the pulseaudio context -- the error message is "Connection refused"". 
What would cause the program to run differently in these two contexts? I have tried changing the user and group to my own user and group in the systemd unit file, but still encounter the error.
Thank you for your help!

**Comment by mikebrady** [comment]
Thanks for the post.

Unfortunately, the problem lies with the way PulseAudio is set up. For [security reasons](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/), PulseAudio is normally set up to run as a user daemon rather than a system daemon, so it is not running on boot up.

Apparently you can set it up to run in system mode, but I haven’t tried it.

See also the [README.md](https://github.com/mikebrady/shairport-sync#configuring-shairport-sync).

**Comment by techwiz001** [comment]
Thank you for the feedback! 
I was also investigating ways to automatically run Shairport-sync as my user. When I run the command manually, it works, but when it is part of a systemd unit file I get the same error as before, even when the unit file is set to use my user and group. Not sure what's causing this, but appreciate your input! If I don't have luck setting things up in the next few days, I'll probably just set Shairport-sync to use ALSA mode instead of PA.
