### ISSUE TITLE
Shairport-sync and alsaequal

### ISSUE THREAD

**Issue by naorunaoru** [mikebrady/shairport-sync#115]
On Raspberry Pi, when alsaequal is set as default audio output, I'm getting no sound at all with errors such as this:

    Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -4793.

If I force `-d` to be `hw:0`, everything is ok.

Is it possible to use any system-wide equalizer with shairport-sync?

**Comment by mikebrady** [comment]
Hi there. I'm afraid it is not possible. The synchronisation feature of Shairport Sync requires it to have be able to frequently measure the size of the output device's output buffer.

**Comment by naorunaoru** [comment]
@mikebrady well, sync is more important, so I'll try to find another way to circumvent my somewhat crappy acoustic system. Thank you for your support.

**Comment by LuckyLukeCH** [comment]
Hello Mike,
First thank you for your very nice work; I appreciate it!
I fall into the alsaequal problem as well.. do you have any news on that? How could we achieve some equalization with shairport-sync -> HifiBerry Amp+, since there ist no audio-line between.

Thank you and regards from Switzerland
Lukas

**Comment by SirVer** [comment]
I am running into the same issue. @naorunaoru Roman, how did you solve the issue on your end? My bass is drowning everything else out :)

**Comment by mikebrady** [comment]
Apologies for not responding to this, Lukas. The solution is to do equalization before synchronization, so there would be a chain of processing from packet reception through to synchronized output. We are making baby steps towards it, but it'll take quite a bit of time, I'm afraid.

**Comment by naorunaoru** [comment]
@SirVer I'm using an amplifier with EQ settings. Problem solved.

**Comment by SirVer** [comment]
@naorunaoru That works :).

I reverted to using shareport for the while being. I will miss synchronizing my music across rooms, but equalizer is more important because my boxes are so bad and bass heavy. Maybe I can find better audio equipment in my budget and use shairport-sync again in the future.

Or maybe routing through alsa plugins comes to shairpoirt-sync eventually. That would be awesome.

**Comment by SirVer** [comment]
@mikebrady You said there were babysteps towards equalization + sync. Has this maybe been solved in the last few months?

**Comment by nbgl** [comment]
There is now a built-in convolution filter that can be used for equalisation.

Alsaequal also works if you set it up correctly: you need to create a home directory for the shairport-sync user, symlink your own .alsaequal.bin file to that directory, and set the correct permissions.

**Comment by mikebrady** [comment]
Very interesting – the `alsaequal` thing is new to me.

**Comment by jshep321** [comment]
@nbgl Could you explain a bit more?  I have created an asound.conf file that explicitly points to the user directory for control.   That file is readable by all.    If I make a shairport-sync home dir and symlink from there to my .alsaequal.bin it will then work?  
```
#asound.conf
ctl.equal {
type equal;
controls "/home/pi/.alsaequal.bin"
}

pcm.plugequal {
type equal;
#slave.pcm "plughw:sndrpihifiberry,0";
slave.pcm "plughw:0,0";
controls "/home/pi/.alsaequal.bin"
}

pcm.equal {
type plug;
slave.pcm plugequal;
}
```

**Comment by jshep321** [comment]
FYI, I have gotten this to work with other programs (mpg123), but not shairport-sync.

**Comment by nbgl** [comment]
@jshep321 It’s been years since I played with this so I don’t 100% remember what I did. From recollection though, the Shairport-sync daemon runs on a separate user account (the `shairport-sync` user). Now, Alsaequal settings are stored per-user, so your levels don’t automatically apply to Shairport-sync.

You thus need to manually ensure that the levels that you set as the `pi` user also apply to the `shairport-sync` user. You can do that by making a symbolic link in the Shairport user’s home directory (`/home/shairport-sync/.alsaequal.bin`), pointing to `/home/pi/.alsaequal.bin`. You also need to set (`chmod`) permissions so that `shairport-sync` can read `/home/pi/.alsaequal.bin`.

I think the above is right, anyway. Again, it’s been a long time.

**Comment by jshep321** [comment]
@nbgl Excellent advice, thanks and makes perfect sense.  Will attempt that soon!
