### ISSUE TITLE
iTunes Lossless

### ISSUE THREAD

**Issue by kdubious** [mikebrady/shairport-sync#1194]
When iTunes goes lossless in June, do we expect things to "just work."

**Comment by mikebrady** [comment]
Thanks for the post. Well, the "lossless" stuff must refer to AirPlay 2 or a variation of it, because AirPlay 1, which Shairport Sync uses, is already lossless.

AirPlay 1 uses ALAC to do lossless compression of the venerable CD standard: 44.1k, 16-bit LCM stereo for the transport of audio from, say, the macOS Music app to the playing device.

So, let's hope that they continue to support AirPlay 1.

**Comment by kdubious** [comment]
@mikebrady I was referring to this:
https://www.apple.com/newsroom/2021/05/apple-music-announces-spatial-audio-and-lossless-audio/

"Lossless Audio
Apple Music will also make its catalog of more than 75 million songs available in Lossless Audio. Apple uses ALAC (Apple Lossless Audio Codec) to preserve every single bit of the original audio file. This means Apple Music subscribers will be able to hear the exact same thing that the artists created in the studio.
To start listening to Lossless Audio, subscribers using the latest version of Apple Music can turn it on in Settings > Music > Audio Quality. Here, they can choose different resolutions for different connections such as cellular, Wi-Fi, or for download. Apple Music’s Lossless tier starts at CD quality, which is 16 bit at 44.1 kHz (kilohertz), and goes up to 24 bit at 48 kHz and is playable natively on Apple devices. For the true audiophile, Apple Music also offers Hi-Resolution Lossless all the way up to 24 bit at 192 kHz."

**Comment by kdubious** [comment]
I suppose ALAC support is "enough" to get things to work with higher rez files.

**Comment by mikebrady** [comment]
Yeah, it's really hard to know.

One scenario is that Apple supports the CD-quality lossless tier to AirPlay 1 devices, in which case you would get lossless from steaming source all the way through to the DAC at CD quality (16/44.1/stereo).  In that scenario, ALAC support in AirPLay 1, and hence Shairport Sync, would be "enough". Although technology has moved on, as a long-time hifi enthusiast, lossless CD-quality from source to DAC would make me pretty happy.

ALAC supports other formats, but AFAIK it has never been use in AirPlay 1 at other than CD quality.

**Comment by TheOldPresbyope** [comment]
[note, I'm a pessimist who always assumes the worst that can happen will happen. I'd be happy to be proven wrong here.]

I suspect Airplay 2 will not support hi-resolution streams.

Let's look at the Apple announcement. There's this sentence in the paragraph from it cited above

> Apple Music’s Lossless tier starts at CD quality, which is 16 bit at 44.1 kHz (kilohertz), and goes up to 24 bit at 48 kHz **_and is playable natively on Apple devices_**. 

The phrase I've highlighted suggests to me that Airplay 2 only goes up to 24 bit at 48 kHz because that's all that current Apple devices support and all that has been posted to the Internet by various hackers exploring Airplay 2 for the last 4 years.

Next, compared to the original [press release](https://www.apple.com/newsroom/2021/05/apple-music-announces-spatial-audio-and-lossless-audio/), there's a footnote 1 missing from the end of this sentence in the paragraph cited above.

> For the true audiophile, Apple Music also offers Hi-Resolution Lossless all the way up to 24 bit at 192 kHz.

Footnote 1 in the original press release says

> Due to the large file sizes and bandwidth needed for Lossless and Hi-Res Lossless Audio, subscribers will need to opt in to the experience. **_Hi-Res Lossless also requires external equipment, such as a USB digital-to-analog converter (DAC)_**.

The highlighted sentence suggests to me only local hi-res playback is possible.

**Comment by sosickstudio** [comment]
After testing it out it seems the connection to the airplay 2 HomePod mini shows lossless when lossless is enabled. The lossless logo is shown. However it doesn't show up when I'm using my PI with shaiport. What's more it refuses to play songs downloaded as lossless :/

**Comment by mikebrady** [comment]
@TheOldPresbyope, I think you are 100% right, but (optimist that I am 🙂) I hope that Airplay 2 will support high resolution streams in future.
