### ISSUE TITLE
Pipe out/stdout to ecasound

### ISSUE THREAD

**Issue by Odal3** [mikebrady/shairport-sync#126]
Hi, 
Thanks for sharing the great software. I have the 2.4 version installed and I'm struggeling getting a second program listening to stdin or the pipe I define. I'm trying to get the audio to Ecasound for processing. I tried aplay as well, but couldn't get any sound out. It looks like shairport-sync is streaming the audio. I have tried both command line and using the config. Any help with the syntax to get it working with ecasound (or an example with aplay) would be appreciated. 

Also, where can I find the log files?

(2.4-openssl-Avahi-ALSA-stdout-pipe-soxr-metadata)

BTW: is this the best forum for questions?

**Comment by mikebrady** [comment]
Here is an example from Raspbian:
```
sudo shairport-sync -v -o stdout | aplay -f cd
```
The `-v` turns on some debug information, which goes to the console or the logfile.
```

**Comment by Odal3** [comment]
Many thanks!!! Got it working. I tried to run the ecasound listening to stdin first, but when running them together with | it works! Do you always have to call it from the command line or can it be set in the config file as well?

Where can I find the logfile?
Separate question: Is the sync consistent enough to maintain a stereo image if used with two rasberry pi feeding left and right speaker over wifi or will it likely be drift spikes?

**Comment by mikebrady** [comment]
You can use the config file to specify that the output should go to stdout, but you can't use if to specify what happens next. I suggest you write a small shell script instead -- any decent linux book will show you how. The logfile in Raspbian is at `/var/log/syslog`. It's location may vary from distribution to distribution, but again, a linux reference will help with that.

I have never tried to drive left and right speakers from separate machines, because I never thought it would work. A timing inaccuracy or drift of one millisecond would move the sound source about 30 cm (about a foot). A Shairport Sync device could routinely drift much more than that. Remember also that if you're using `stdout`, even this level of synchronisation is not available. So, the numbers are not encouraging. Still, I've never actually tried it.

**Comment by Odal3** [comment]
Thanks again for your help. Shairport-sync is great! I haven't use the actual sync yet, but the ability to pipe out is great! Now it only would be able to do the same thing from an android phone...

BTW: There has been a lot of discussion on diyaudio.com about using ntp to sync two speakers. See post 221 for a summary: http://www.diyaudio.com/forums/pc-based/274331-ladspa-plugin-programming-linux-audio-crossovers-23.html#post4449711

One set-up that seems to show promise is using a media server that syncs via NTP, and then use client raspberry Pis to locally sync up to the music server resulting in "synchronized to better than 1 msec, often to within 500 usec"

It would be intersting to hear your thoughts over there too.

**Comment by mikebrady** [comment]
Interesting. With Shairport Sync on a wired network, the drift can comfortably be set down to 33 frames -- 0.75 milliseconds. I am dubious about using NTP because of the way it adjusts the local clock. From the point of view of stability, these adjustments would be seen as inaccuracies.
