### ISSUE TITLE
Airplay from iOS/iPadOS devices works, Airplay from MacOS does not

### ISSUE THREAD

**Issue by adamreis** [mikebrady/shairport-sync#1283]
Hey folks,

First off, I'm really grateful for all the hard work put into this project; it's been a blast to play with. Thanks in advance for your help on this.

I recently set up shairport-sync for the first time, following the [Airplay 2 custom build guide](https://github.com/mikebrady/shairport-sync/blob/development/BUILDFORAP2.md). It worked with relatively little fiddling, which was awesome. I decided to level up by using my USB audio interface (Audient iD14 mkII) as an output from the Raspberry Pi, which is where I've started running into a problem: This works just fine if I stream audio from my iPhone or iPad, but not if I try to stream audio from my M1 Macbook Air. If I try to stream audio from my mac I hear no sound and see this shairport-sync log message:

```bash
shairport-sync[22081]: ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL plughw:CARD=iD14,DEV=0
```

Streaming from my other devices works as expected and doesn't output any logs. Any idea what's up? Are there more logs I should be looking at? I doubt my mixer config is incorrect, as it works as expected from my iPhone + iPad. Very strange.

Hardware specs (all software up-to-date):
* 2018 iPad Pro
* iPhone 12 Pro Max
* M1 Macbook Air
* Raspbery Pi 3B

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest you take a look at the TROUBLESHOOTING page.

The main thing I see is that you are outputting to an `alsa` pseudo-device rather than the real hardware. A device name starting with `plug…` could be doing all manner of strange things, so look for the real hardware device — it’ll begin with `hw…`. You’ll also get a readout of the hardware devices available at the end of the help text from `$ shairport-sync -h` . 

OTOH, I don’t see what that would only affect audio coming from the Mac.

More generally, if you set the `log_verbosity` to 1 in the configuration file and restart, you might get some more information in the system log.

Finally — and this is really a general comment — AirPlay 2 on M1 Macs is, in my experience, very buggy. In particular it doesn’t work properly if the Mac has been woken after being asleep. Again, not sure how this might affect your situation, if at all, but worth keeping in the back of your mind.

**Comment by adamreis** [comment]
Thanks for the quick response @mikebrady. 

**TROUBLESHOOTING** - I did a quick once-through before posting, but will take a closer look right after I send this.

**device name** - I started with `hw:iD14` and `hw:CARD=iD14,DEV=0` but always got the following error message. The only way I found to fix it was to switch to the `plughw` virtual device. Is there another workaround I should try? I did explicitly set `output_format` to `"S32_LE"` and `output_rate` to `44100`; no dice:

```
0.041297297 "audio_alsa.c:289" Failed to attach mixer
0.001271772 "audio_alsa.c:486" *fatal error: audio_alsa: Channels count (2) not available for device "hw:CARD=iD14,DEV=0": Invalid argument
```

**log_verbosity** - good call, should have tried this. 

**M1 Airplay 2 flakiness** Welp, AFAICT looks like this is the culprit. I also read the same about M1 macs and Airplay 2 somewhere (maybe in docs here, maybe on reddit, maybe from you?), but thought I had already repro'd the same issue after a fresh restart so thought this was unrelated. Alas, when I did a fresh restart just now everything worked (although that original error message still shows up). How embarrassing. I'll close this issue for now, but will keep an eye on it and reopen if I have any new ideas/make further debugging progress.

**Comment by mikebrady** [comment]
Good stuff. I confess that, until now, I didn’t check out the output device you mentioned. It looks like it is a four channel (or six channel?) output device. Shairport Sync looks for a two channel device, hence the error when you connect directly. The plugin must be converting for you.
