### ISSUE TITLE
iTunes any support yet Shareport-Sync development 

### ISSUE THREAD

**Issue by petcol** [mikebrady/shairport-sync#1459]
hi,

Just checking if there are any changes yet to allow iTunes to connect to a device that's running the development Shareport-Sync.

All working fine from an iOS device such as iPhone or Apple TV but still getting "this Airplay device <DEVICE_NAME> is not compatible with this version of iTunes"

Also when I do sudo apt Update and sudo apt full-upgrade is this update the Shareport-Sync and the nqptp?

Col

**Comment by mikebrady** [comment]
Thanks for the post, Col. Am I correct in guessing you are referring to iTunes on Windows?

Unfortunately there is no work that I know of under way to make Shairport Sync’s AirPlay 2 implementation work on iTunes for Windows. This is because encryption and authentication used in iTunes for Windows have not, to my knowledge, been reverse engineered.

As regards  an `apt` package, I hope that will come when AirPlay 2 support is merged into the `master` branch and a release is made. That should be fairly soon.

**Comment by petcol** [comment]
thanks for the update, question, I assume the build would then either need to be changed from development flag to master flag?  Or a full rebuild?  And, how do we know?  keep checking here or?

**Comment by mikebrady** [comment]
Thanks, yeah, the best thing to to check here.
