### ISSUE TITLE
Possible to expose "virtual" airplay devices?

### ISSUE THREAD

**Issue by icanhazpython** [mikebrady/shairport-sync#1474]
Apologies if this has been asked before. I'm trying to theorize how I might utilize AirPort in my whole-home audio setup. The thing about my setup is that it is centralized - all speaker wires run to a cabinet, and I have an amplifier that is multi-zone, and has a built in matrix. So I can essentially take one input and switch it to multiple output zones. I'd like to leverage this to reduce the amount of airplay devices I need to achieve multi-zone audio. So if I have 8 zones, instead of needing 8 unique players, I'd ideally like to use maybe 2 unique players and rely on the amp to switch those into multiple output zones. Thus my idea is to have "virtual" airplay devices. I'm wondering if it's possible to have shairport running on one device, but shairport expose say 8 different virtual players that I can group as I see fit. Shairport would simply then expose the selected devices via some sort of interface that I can then take and use to control the switching on my amp. 
Thanks!

**Comment by mswoff** [comment]
I'm trying to do something similar. The approach I'm doing now writing the output of shairpoint-sync to a pipe and then trying to setup a vlc process which takes pipe and creates a local http stream. Then any number of speakers can attach to this http stream via additional vlc processes.

Currently running into issues though with going from pipe to http stream, which I think are due to the output format of the shairpoint-sync pipe/input format vlc expects, but I'm not positive.

I'll update if I get it working.
