### ISSUE TITLE
Iphone 6+ cannot find shairport-sync

### ISSUE THREAD

**Issue by ericwongcm** [mikebrady/shairport-sync#15]
Do you have any idea why Iphone 6+ running iOS 8.0.2 cannot find shairport-sync using airplay?
Iphone 6 probably have the same problem.

Strangely, Iphone 5S and 4S, also running iOS 8 can find shairport-sync without any problems..
Latest windows version of Itune also works fine with shairport-sync without any problems..

**Comment by mikebrady** [comment]
Thanks for that. The weird addresses beginning with FE80: are automatically-assigned local IPv6 ip addresses and the 169.254... address is a self-assigned IPv4 address. They are all good. I can't see anything unusual there, TBH. There's no need for the TXT records thanks. Let's hope it stays stable – if not, see if there is any pattern to it.

**Comment by mikebrady** [comment]
Just wondering if some of this is similar to #29?

**Comment by mikebrady** [comment]
Oops – didn't mean to close the issue.

**Comment by senthor** [comment]
One question to all of you: What other Apple hardware do you have on the network? I used to have similar problems since upgrading to Yosemite while using an AirPort Express as router. There seem to be problems with distributing multicast packets (for Apple TV and AirPorts), as I suddenly was unable to find shairport, the AirPort Express AirPlay, and my Mac started changing names every few hours (always "[Name] n+1").
Solution was to remove the AirPort Express and use other (non-Apple) networking hardware.

**Comment by soulchild** [comment]
I only have a couple of iPhones and a Yosemite Macbook Pro on the network. I have the feeling that some lower level networking issues are at play here as well.

I had a DD-WRT Linksys WRT54GS and was very happy with it. Then came iOS 8 with which (presumably) the airplay connection dropping started. Everything went downhill after an upgrade of my internet connection, because my ISP forced me to use a new combined and utter crap cablemodem/router combination (Technicolor TC7200U) which totally broke mDNS, thus Airplay stopped working completely. It turned out that with WMM enabled, the router just wouldn't route multicast DNS between WiFi and LAN, so my devices wouldn't even see shairport. How silly is that? I switched to a Netgear Nighthawk R7000 and Airplay has been MUCH MORE reliable since then, but I do get the occasional connection drops.

**Comment by kjellpell** [comment]
Hi, I used to have a lot of problems with iPad Air, having to re-connect to wifi all the time to get Airplay to show up. I bought Raspberry Pi 2 right after the release and upgraded to the last version of Shairport Sync. I have not had any problems with Airplay since...

**Comment by mikebrady** [comment]
Thanks for the report. I've noticed a gradual improvement over the last few months, but I'm not sure what's causing it.

**Comment by soulchild** [comment]
I guess under the hood changes in the Airplay implementation of the various minor iOS revisions since iOS 8.0 ... ;-)

**Comment by mikebrady** [comment]
This looks interesting: http://appleinsider.com/articles/15/05/26/latest-os-x-beta-ditches-buggy-discoveryd-dns-service-replaced-with-mdnsresponder.

**Comment by mikebrady** [comment]
This seems to be entirely fixed by OS 10.10.4 and later and iOS 9. Closing the issue.
