### ISSUE TITLE
What is the output format of piped audio?

### ISSUE THREAD

**Issue by mswoff** [mikebrady/shairport-sync#1503]
Sorry if this is obvious, but I'm trying ti pipe the audio into a vlc process and vlc can't recognize the input. I figure I need to do some sort of transcoding first but don't know what format the piped data is in.

**Comment by mikebrady** [comment]
Thanks for the post. It’s raw “CD quality” PCM. That is, 44,100 frames per second, each frame consisting of two 16 bit signed little-endian integer linear PCM audio samples, one for the left channel and one for the right channel. There is no other formatting — no headers or trailers, since it’s a stream.

**Comment by mswoff** [comment]
Makes perfect sense thanks!
