### ISSUE TITLE
[Problem]: AirPlay 2 loses master clock when single speaker stopped

### ISSUE THREAD

**Issue by martinoneutrino** [mikebrady/shairport-sync#1547]
### What happened?

Setup consists of multiple Airplay 2 instances on a single server (different ports) with output to multiple speakers.
Use Music app on iOS 15.7 or macOS 12.5 to play and:
* Change to first speaker - no problem.
* Add second speaker - no problem (both playing).
* Disable either speaker - sound output stops, although Music app thinks it is still playing.

I expect the output to continue on the speaker that was not disabled.

I suspect the cause is the loss of the master clock, as shown in the log extract.

I'd be happy to write some code to correct this, but am not exactly sure which part (shairport-sync or NQPTP, or both) should be updated...

### Relevant log output

```shell
19:28:00 shairport-sync[110065]:  0.000300822 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T fe80::1834:38e9:952b:3dd4"
19:28:01 shairport-sync[110065]:  0.000493086 "rtp.c:1409" Connection 1: NQPTP master clock b08c755cf64b0008.
19:28:11 shairport-sync[110034]:  0.000303549 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T fe80::1834:38e9:952b:3dd4"
19:28:11 shairport-sync[110034]:  0.000414841 "rtp.c:1409" Connection 1: NQPTP master clock b08c755cf64b0008.
19:28:21 shairport-sync[110034]:  0.000007271 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T"
19:28:21 shairport-sync[110034]:  0.000026472 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T"
19:28:21 shairport-sync[110065]:  0.425578773 "rtp.c:1428" Connection 1: No NQPTP master clock.
19:28:30 shairport-sync[110065]:  0.000007467 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T"
19:28:30 shairport-sync[110065]:  0.000019862 "ptp-utilities.c:176" Send control message to NQPTP: "/nqptp T"
```

### Operating System?

Fedora 36
Linux 5.19.12-200.fc36.x86_64

### Version?

4.1-rc0-AirPlay2-OpenSSL-Avahi-ALSA-pa-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the interesting post. If you could give us more detail about the speakers, it would be useful. Are they all Shairport Sync ("SPS") devices? Are all the SPS speakers running on the same system, as your post seems to imply? Are there any non-SPS speakers, and if so what are they? Apologies for all the questions! 

In recent testing, there have been no problems adding and removing multiple speakers, but maybe there is something about the speaker systems you have.
SPS is routinely tested with up to four sets of SPS-powered speakers (all on separate Linux/FreeBSD/Mac OS systems), one or two HomePod minis, an AppleTV 4K and a couple of M1 Macs providing AirPlay 2 service. Clients are mostly Intel and Apple Silicon Macs, iOS, iPadOS and occasionally OwnTone.

If you have multiple instances of SPS running on the same system, that could be the problem --  we have had no success in having multiple instances of the AirPlay 2 version of SPS running on one system, unless some form of virtualisation is used.

Even when you ensure that the instances of SPS offer different Device IDs, the Avahi system seems to combine all the IPs of the system together so that all instances of SPS on the same system appear to reside at the same set of IP numbers. Whether this is a feature of Avahi or the Bonjour protocol itself, AirPlay 2 clients confuse the separate instances with one another.

(Another issue arises if two separate instances of SPS are playing from two different clients, the PTP timing signals must be segregated. This was done in a previous version of NQPTP but has been dropped.)

The `Discovery` app from TildeSoft (for Mac and iOS) is very useful for seeing what services are being advertised using Bonjour.

**Comment by martinoneutrino** [comment]
Yes, they're all SPS speakers, all running on the same server, each with its own config file, port and service (config differences: name, port, udp_port_base, airplay_device_id_offset and output_device). There are no others on that server, only AppleTVs elsewhere on the same network.

I haven't had any problems with multiple instances (in either Airplay 1 or 2), other than this occurrence. I just tried streaming from macOS and iOS at the same time to two different pairs of SPS speakers without any issues (until I disabled a speaker, then all stopped).

I tested from iOS to SPS and an AppleTV and it had a noticeable sync difference. (Not my concern right now really.)

What info relating to Bonjour would be relevant?
Here are two `_airplay._tcp` entries:
```
Master Bath
duo.local.
192.168.1.250:5001
[fe80::a60:6eff:fe79:9d6b]:5001
srcvers=366.0
deviceid=08:60:6e:79:9d:6c
features=0x405FCA00,0x1C340
flags=0x804
protovers=1.1
acl=0
rsf=0x0
fv=4.1-rc0
model=Shairport Sync
pi=833d144e-87ad-45b9-8d43-d82fedce9cb2
gid=F6706419-1D31-4FB7-B851-72413E720FD4
gcgl=0
isGroupLeader=0
pk=d20aacaace69fb8c030becd63faba15def1dba761448480ca64c51464897b13c
```
```
Master Bedroom
duo.local.
192.168.1.250:5002
[fe80::a60:6eff:fe79:9d6b]:5002
srcvers=366.0
deviceid=08:60:6e:79:9d:6d
features=0x405FCA00,0x1C340
flags=0x804
protovers=1.1
acl=0
rsf=0x0
fv=4.1-rc0
model=Shairport Sync
pi=0d7ffea3-0a2f-43eb-8acf-0b9954fc6a98
gid=F6706419-1D31-4FB7-B851-72413E720FD4
gcgl=0
isGroupLeader=0
pk=21ad28eedb62c1e38a2e307abe7765d4a0ef0fc4cbc25cc3695b7b7e8e00a1b3
```

**Comment by mikebrady** [comment]
Thanks for the update.

As you can see, both SPS players appear to occupy the same IP numbers. This seems to confuse AirPlay 2 clients.

It has always been possible to run multiple instances of classic (i.e. AirPlay 1) SPS players on one system, but it just doesn't seem to be possible with AirPlay 2.

> I tested from iOS to SPS and an AppleTV and it had a noticeable sync difference. (Not my concern right now really.)

If the sync difference is constant, it may be caused by a delay in the audio processing in whatever is connected to the AppleTV. If so, you can delay the SPS output to match it using the `audio_backend_latency_offset_in_seconds` setting.

**Comment by martinoneutrino** [comment]
I'm not seeing the confusion with the AirPlay 2 clients that I've been using. The issue I'm having is that when I stop one speaker, that the remaining speaker stops because it has "No NQPTP master clock".
I think this is due to the interaction between SPS and NQPTP, rather than anything the client is observing..

Thanks for the tip on the AppleTV sync; I will try that out.

**Comment by martinoneutrino** [comment]
Excellent! This appears to have been resolved with the change in nqptp to smi version 10 (https://github.com/mikebrady/nqptp/commit/10969eaa0ba71287efd46252910701809b50fb36) to remove master_clock_ip.
