### ISSUE TITLE
config general.interface is ignored in airplay2 mode.

### ISSUE THREAD

**Issue by martinlindhe** [mikebrady/shairport-sync#1599]
### What happened?

When using airplay2 compiled build, the general.interface configuration is ignored.

The airplay2 code appears to ignore the interface setting, instead chosing the first interface and picking their mac address:

https://github.com/mikebrady/shairport-sync/blob/6240fd83707b77fe2fb2250f8136e530e36010d2/shairport.c#L1944-L1945

The airplay2 code picks the first interface, even one without a uplink, resulting in 100% broken setup if you have for example one ethernet and one wifi card in your machine, and the first one does not happen to have a uplink.

There seems to be no way of overriding this behavior.

### Desired solution
Ability to specify what interface the airplay2 would listen to, eg using `interface = "wlan0"`  (desired as it already works with the airplay1 support) or `hw_addr = "mac"`

### Relevant log output

```shell
Dec 19 09:49:27 box systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Dec 19 09:49:27 box shairport-sync[50077]:          0.000048839 "shairport.c:2204" Startup in AirPlay 2 mode, with features 0x405fca00,0x1c340 on device "58:11:22:33:44:55".



NOTICE THAT "ip link" reports the chosen interface as DOWN:


$ ip link
2: eno2: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 58:11:22:33:44:55 brd ff:ff:ff:ff:ff:ff
    altname enp5s0
5: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 2c:2d:2e:2f:20:21 brd ff:ff:ff:ff:ff:ff



additionally, `/etc/shairport-sync.conf` was configured with `interface = "wlan0";`  , which WORKS in airplay1 mode.
```

### Configuration Information.

I built from source with arch AUR https://aur.archlinux.org/packages/shairport-sync-git from latest git master, with and without `--with-airplay-2` configuration as the only change.

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post, but there seems to be a slight misunderstanding.

The Device ID could be based on anything, and the first MAC address is used for that purpose. It has nothing to do with which interfaces happen to be used.

If you _don't_ specify an interface with the `interface` setting, Shairport Sync ("SPS") will listen on all active interfaces, so that if `eno0` is down and `wlan0`, it will advertise and pick up activity on `wlan0`. This is a very common situation, for example in Raspberry Pis.

If classic SPS works and AirPlay 2 SPS does not work on the same device, I'd be looking for some other issue. 

1. Most clients, e.g. iOS, really dislike the same device switching from AirPlay 2 to classic AirPlay. It can take a few minutes for the clients to adjust. Alternatively, make sure the classic and AirPlay 2 services are given different service names.
2. AirPlay 2 operation requires NQPTP to be installed and running. NQPTP needs `root` access and it's important to ensure any firewalls, on the device or on the network, permit UDP traffic on ports 319 and 320.

**Comment by martinlindhe** [comment]
Thanks for your input.
Yes, I agree it seems I have come to some wrong conclusions here about how hw_addr was used.

Up until this point I had done the following:

	paru -S shairport-sync-git nqptp-git    # AUR installer for the git repos


set output_backend = "pw" in /etc/shairport-sync.conf


	sudo systemctl enable shairport-sync
	sudo systemctl start shairport-sync
    sudo systemctl enable nqptp
    sudo systemctl start nqptp

But I was not able to see my shairport device from an iOS device. After I recompiled without airplay2 support I got a connection and heard sound, but then addionally had to make the changes in  #1600 in order to hear crack-free sound.

I'm out of my comfort zone here being a new user of both pipewire and shairport-sync.

**Comment by mikebrady** [comment]
Okay, thanks. It might take me a little while to reply -- just await from my systems right now.

**Comment by mikebrady** [comment]
Just to keep things fairly simple initially, let me suggest that you try to get Shairport Sync working from the command line on the desktop, but with the `alsa` backend, even though it's a PipeWire system. To do this, you'll need to leave the `nqptp` service running, but stop the `shairport-sync` service (`$ sudo systemctl stop shairport-sync`) -- otherwise, the command-line version of `shairport-sync` will complain and stop working.

The thing about PipeWire (and PulseAudio) is that they are "sound servers" rather than sound subsystems. They provide audio services to the logged-in user. The user has to log in through the desktop GUI. Crucially, this means that PipeWire services are generally not available to background programs ("daemons") like SPS that are launched when the system boots up.

Therefore, as suggested above, run Shairport Sync from the command line, because PipeWire is only available when the desktop user logs in through the GUI. When you log in, the PipeWire user service is launched. When you then launch the Terminal program to give you command-line access, PipeWire is running and providing the fake `alsa` device (a "pseudo-device") that accepts `alsa` commands and data and sends audio to the default output device. Thus you don't really have to worry about the audio settings of PipeWire at this point.

It's probably a good idea to launch SPS with one level of verbosity:
```
$ shairport-sync -v
```
If you can get Shairport Sync to work in this way, then that's a good start. Any remaining issues are to do with PipeWire and suchlike.

**Comment by martinlindhe** [comment]
@mikebrady Thanks for your continued help.
I am really sorry for causing this noise. My initial conclusion was at fault.

I have started over from scratch, and now I have successful airplay 2 working!

**Comment by mikebrady** [comment]
Many thanks for the update, and I’m glad that you got it working properly!
