### ISSUE TITLE
[Problem]: can't hear sound from shairport-sync

### ISSUE THREAD

**Issue by bonds** [mikebrady/shairport-sync#1602]
### What happened?

I'm using pop_os  and apt. I installed avahi-daemon, enabled, and started it. I installed, enabled and started shairport-sync. I tried to connect and play something from my iPhone. I was able to connect, and it looked like it was playing on my iPhone, via my shairport-sync computer, but no sound came out. I'm able to play other music and sounds on my computer.

I noticed that whenever I start playing via shairport-sync, the log fills with 'connection refused' errors, see below.

### Relevant log output

```shell
scott@metanoia ~> systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
     Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-12-24 11:16:59 PST; 1h 52min ago
       Docs: man:shairport-sync(7)
             file:///usr/share/doc/shairport-sync/README.md.gz
             https://github.com/mikebrady/shairport-sync
   Main PID: 16143 (shairport-sync)
      Tasks: 19 (limit: 37605)
     Memory: 7.5M
        CPU: 16.812s
     CGroup: /system.slice/shairport-sync.service
             └─16143 /usr/bin/shairport-sync

Dec 24 13:09:22 metanoia shairport-sync[16143]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio:>
Dec 24 13:09:22 metanoia shairport-sync[16143]: warning: alsa: error -111 ("Connection refused")>
Dec 24 13:09:22 metanoia shairport-sync[16143]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio:>
Dec 24 13:09:22 metanoia shairport-sync[16143]: warning: alsa: error -111 ("Connection refused")>
Dec 24 13:09:22 metanoia shairport-sync[16143]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio:>
Dec 24 13:09:22 metanoia shairport-sync[16143]: warning: alsa: error -111 ("Connection refused")>
Dec 24 13:09:22 metanoia shairport-sync[16143]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio:>
Dec 24 13:09:22 metanoia shairport-sync[16143]: warning: alsa: error -111 ("Connection refused")>
Dec 24 13:09:22 metanoia shairport-sync[16143]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio:>
Dec 24 13:09:22 metanoia shairport-sync[16143]: warning: alsa: error -111 ("Connection refused")>
scott@metanoia ~>
```

### Configuration Information.

scott@metanoia ~ [1]> uname -a
Linux metanoia 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux
scott@metanoia ~> shairport-sync -V
3.3.8-libdaemon-OpenSSL-Avahi-ALSA-jack-pa-dummy-stdout-pipe-soxr-convolution-metadata-mqtt-dbus-mpris-sysconfdir:/etc

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Unfortunately, this is a problem with the way an audio system using PulseAudio is normally set up in a desktop Linux.

When a user logs in through the desktop Graphical User Interface (GUI) -- let's call that user the "desktop user" -- a PulseAudio "user service" is started to provide audio services to the desktop user's programs. The PulseAudio user service then interacts with the PulseAudio daemon on behalf of the desktop user to provide those audio services.

To offer compatibility to programs, such as Shairport Sync, that send audio to the `alsa` audio subsystem, audio sent by a program to the system's default `alsa` device is automagically routed into the PulseAudio system.

The problem is that a PulseAudio user service is not started for other users apart from the desktop user. So, when Shairport Sync starts up as a system service (i.e. when installed as a background daemon started when the system boots up), no PulseAudio user service is provided, so the automagical rerouting of audio from the default `alsa` audio device into the PulseAudio system can not happen and you get those error messages you have listed above.

You can still run Shairport Sync from a terminal window after you have logged in as the desktop user -- simply open a terminal window and type `$ shairport-sync`. Before you do so for the first time, however, you probably need to uninstall the `shairport-sync` service. You'll only need to do this once:

```
$ sudo systemctl stop shairport-sync
$ sudo systemctl disable shairport-sync
```
The first command stops the Shairport Sync service if it is running, and the second command stops the service trying to start on boot-up.

**Comment by bonds** [comment]
Got it, thanks! So, not a bug per se. I found this related, prior discussion, now that I understand what went wrong: https://github.com/mikebrady/shairport-sync/issues/1260
