### ISSUE TITLE
Firefox video lag

### ISSUE THREAD

**Issue by samer** [mikebrady/shairport-sync#161]
There is a 2 second audio lag when playing a video on YouTube. The video starts playing and two seconds later the audio track starts. The result is that the video is always out of sync. Tested on Firefox 42 and Mac OS X 10.10.5.

The problem could not be reproduced on Chromium or Safari.

PS: Thank you for the great work, Mike!

**Comment by mikebrady** [comment]
Thanks for the kind words. Actually, the problem is with Firefox. Let me explain:

There is always some delay when you send audio to an Airplay device such as Shairport Sync or the Apple Airport Express. The delay is set by the audio sender and is in the range of about 400 milliseconds to over two seconds. Most senders set the delay at two seconds, including the Mac, when you're routing system audio to an AirPlay device. To compensate for the delay, Safari and Chrome and the Quicktime Player delay video part of a movie by two seconds so that the video and audio are in sync. Firefox doesn't do it. Also, Safari and Chrome don't do it for all YouTube content.

I hope this clarifies the situation.

**Comment by samer** [comment]
Thanks for the explanation! Any idea if there's an existing ticket on bugzilla tracking this issue?
