### ISSUE TITLE
Change volume from RPi cmd line

### ISSUE THREAD

**Issue by smithjw** [mikebrady/shairport-sync#163]
I'm trying to figure out if there's a way to duck the audio level of Shairport-sync from the command line? Usecase is that our RPi is used as the office audio system so I'm AirPlaying tunes to it all day. But it's also used for notifications so I trigger an sound effect to play when a specific phrase is said in Slack via `aplay`.

Is there a command I can issue that will lower the volume when my script runs, then again at the end to raise it back up?

**Comment by mikebrady** [comment]
Hi there. Thanks for the interesting use case. This is a surprisingly tricky problem, and the solution isn't too elegant, IMHO.

Ideally, it should be possible to run the Shairport Sync output and the sound effects through a mixer to the output device. Unfortunately, [I think that] this isn't possible because Shairport Sync needs to be able to check the latency in the `alsa` device, and AFAIK the latency returned by a mixer is not reliable. (I'd love to be wrong about this, BTW, so if anyone can enlighten me, great.)

So, the only way I know to do this is got kick Shairport Sync off the `alsa` device when you need to send it a sound from elsewhere. One way to do this would be to send a command to the source of the music and ask it to pause. That would cause Shairport Sync to immediately release the `alsa` device, and you could then send the sound effect to it and then send a resume command to the source. Then, the latency time would elapse before the music programme resumed. This is hard to do -- you'd probably have to read the metadata stream from Shairport Sync to get information about the sender -- and not too elegant.

Another possibility which is implemented but not tested very much is, when you want to use the `alsa` device to play the sound effect, send a command to Shairport Sync to disconnect itself from the `alsa` device. So, the music source keeps sending data, but Shairport Sync dumps it silently.
Later, when the sound effect is over, you can tell Shairport Sync to reconnect to the `alsa` device and resume sending audio data to it.

Shairport Sync has the capability to do this. If you send it the unix `SIGUSR2` signal to the `shairport-sync` process, it will disconnect from the `alsa` device. If you send it the `SIGHUP` signal, it will connect to the `alsa` device.

It's not well tested, but AFAIK it works.

**Comment by rkam** [comment]
Are these sound effects audio files?  If so, maybe you can control iTunes and not Shairport Sync?

**Comment by smithjw** [comment]
Thanks for the reply Mike, I think dumping the audio would work in this situation. In my config I was also controlling HW volume with shairport, which meant if the volume was set low through iTunes, when an effect played, it was also quite low. 

I've changed my config to change SW volume instead so now when effects play, they're much louder. Will let you know how I go.

@rkam The sound effects are just WAV files on the Pi, but the stream of music is coming from iTune on my iMac
