### ISSUE TITLE
No sound from audio jack or hdmi

### ISSUE THREAD

**Issue by UncleClaude** [mikebrady/shairport-sync#1662]
### What happened?

Hi,

The airplay works, I see it on my network can connect to it, but there's no sound, I edited the config file to manually set the right output, rate, etc. Still doesn't work, I also tested the speakers with a few commands and they work, any one has an idea of I could check next?

### Configuration Information.

shairport-sync --displayConfig
>> Display Config Start.

From "uname -a":
 Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

From /etc/os-release:
 Raspbian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.1-dev-897-g32fddbfd-AirPlay2-OpenSSL-Avahi-ALSA-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Sonos 5";
   output_backend = "alsa";
 };
 alsa :
 {
   output_device = "hw:Headphones";
   mixer_control_name = "Headphone";
   output_rate = "48000";
   output_format = "S16_LE";
 };

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. There are quite a few things that could be going on here. The rate must be multiple of `44,100`, but you'd be better to drop the `output_rate` and `output_format` settings and let Shairport Sync pick them automatically.

Better yet, let me gently suggest you re-do the installation _exactly_ as laid out in the [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md) guide. In particular, spend a little time ensuring that Shairport Sync runs (and you can hear stuff) when started from the command line (use the `-v` and `--statistics` options as suggested, just to reassure yourself that it's working). When you get that far, you can be sure that both Shairport Sync and NQPTP are installed and working properly. Then, please that a look at issues caused by [PulseAudio or PipeWire](https://github.com/mikebrady/shairport-sync/blob/development/ADVANCED%20TOPICS/PulseAudioAndPipeWire.md), which may be applicable is you're running from a Linux with a desktop GUI.

**Comment by Dangoo** [comment]
Hey, recently I upgraded all my raspberries to the latest version of NQPTP ([5672c33](https://github.com/mikebrady/nqptp/commit/5672c33983ab0125cd067be2d004598c49bf45c3)) and Shairport-Sync ([69d3b02](https://github.com/mikebrady/shairport-sync/commit/69d3b02a2602af79b112eebfe98b14825a2cc329)). After these updates they stopped working. So today I found the time to setup one Pi from scratch - it had the same issue not outputting any audio.
When looking into the logs I got this message after starting a playback in Shairport-Sync :
```
         0.009072000 "shairport.c:2610" NQPTP is online.
         1.183295000 "rtsp.c:1422" Connection 1: rtsp_read_request can't find an RTSP header.
         0.043070000 "rtsp.c:1372" Connection 1: Connection closed by client.
         0.274209000 "shairport.c:254" "basic" interpolation has been chosen.
        10.007150000 "rtsp.c:2910" Connection 2: AP2 PTP connection from <Address1> ("Phone") to self at <Address2>.
         3.688311000 "rtsp.c:3272" Connection 2. AP2 Realtime Audio Stream.
         0.069411000 "rtp.c:1435" *warning: This version of Shairport Sync is not compatible with the installed version of NQPTP. Please update.
         0.070634000 "rtp.c:1741" AP2 Realtime Clock receiver initialised.
```

First I tried to use the `development` version of Shairport-Sync, but it returned the same error message.
So I went back by one commit for NQPTP ([ad384f9](https://github.com/mikebrady/nqptp/commit/ad384f9ed3b2cc31e97012ab6bfe5a214ffc65a2)) and it worked 🤔
