### ISSUE TITLE
[Problem] sound craking using VMware on windows

### ISSUE THREAD

**Issue by Noboxj** [mikebrady/shairport-sync#1772]
### What happened?

hello,
i'm running ubuntu on vmware on my windows pc and i can connect to Shairport sync but the sound sizzles a lot but no issue when playing a video from my web browser on the ubuntu vm.

### System Information.

i'm using ubuntu on vmware on my windows pc

### Configuration Information.

```shell
›> Display Config Start.

Fron "unane -a":
Linux noboxi-pc 6.5.0-14-generic #14-Ubuntu SMP PREEMPT DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86.

64 X86_64 GNU/LEnUx

Fron /etc/os-release:

Ubuntu 23.10

Shairport Sync Version String:

4.3.2-1-g90c03bf®-AirPlay2-smi10-OpenSSL-Avaht-ALSA-soxr-sysconfdir: /etc

Command Line:

shairport-sync --displayConfig

Configuration File:

/etc/shatrport-sync.conf

Configuration File Settings:

pw :
{
}

›> Display Config End.
```

### PulseAudio or PipeWire installed?

- [x] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Let me suggest that you build Shairport Sync with the PipeWire backend -- you might have better luck with it on that setup.

To do this, follow the [BUILD.md](https://github.com/mikebrady/shairport-sync/blob/development/BUILD.md) guide, but instead of the line:
```
$ ./configure --sysconfdir=/etc --with-alsa \
    --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
```
substitute:
```
$ ./configure --sysconfdir=/etc --with-pw \
    --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
```
You may have to install a pipewire library. If so, the name will be suggested. Simply install it and run the `./configure...` step again.

**Comment by Noboxj** [comment]
thanks works great now !
