### ISSUE TITLE
[Problem]: Stuck on resolving deltas when git cloning

### ISSUE THREAD

**Issue by hamisharms** [mikebrady/shairport-sync#1776]
### What happened?

I ran the command: 'git clone https://github.com/mikebrady/shairport-sync.git'
and it got stuck on the resolving deltas for 2 hours. 

### Relevant log output

```shell
hamisharms@peachyspeaker:~ $ git clone https://github.com/mikebrady/shairport-sync.git
Cloning into 'shairport-sync'...
remote: Enumerating objects: 20909, done.
remote: Counting objects: 100% (1465/1465), done.
remote: Compressing objects: 100% (639/639), done.
remote: Total 20909 (delta 948), reused 1273 (delta 789), pack-reused 19444
Receiving objects: 100% (20909/20909), 10.51 MiB | 3.22 MiB/s, done.
Resolving deltas:  16% (2246/14032)
```

### System Information.

Raspberry Pir 4 8GB

### Configuration Information.

```shell
Linux peachyspeaker 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

-bash: shairport-sync: command not found
```

### PulseAudio or PipeWire installed?

- [ ] Check if your system uses a Sound Server.

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the post. Cloning the Shairport Sync repository is only one step in building it from sources -- the full guide is [here](https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md). If it took a long time to resolve the deltas, then that could be a problem -- maybe a network problem -- between your system, the network connection and GitHub -- it really has nothing to do with Shairport Sync itself.

You can build Shairport Sync using the instructions above, or you can install it using `apt install...` or similar. Building is usually better because you'll have the latest version, but it's a bit more involved. Alternatively you can install a Docker image from [here](https://hub.docker.com/r/mikebrady/shairport-sync).
