### ISSUE TITLE
Daemon PID location

### ISSUE THREAD

**Issue by duncanleo** [mikebrady/shairport-sync#189]
Hi Mike,

Is it possible to have the daemon use a different PID file location? I'm trying to run the shairport-sync daemon as a non-root user but it won't start as /var/run/shairport-sync.pid is only writeable by the root user.

Thanks!

**Comment by mikebrady** [comment]
Hi Duncan. Yes indeed, you can compile Shairport Sync to use a different directory using the `--with-piddir=<pathname>` configuration directive.

**Comment by duncanleo** [comment]
Thanks mate, that works! May I ask, is there any reason to include that as a ./configure option rather than an option for the service itself (e.g. `shairport -d -pid /var/run/somefile.pid`)?

Thanks!

**Comment by mikebrady** [comment]
Good. Actually, TBH, I can't remember why it ended up as a compilation option. I was grappling with using `libdaemon` rather than the demonising code inherited from the original `shairport` and probably stopped when I got something working. See #2 for more... Anyway, enough history; is it a problem?

**Comment by duncanleo** [comment]
Nope, not a problem, was just curious about the option :) Thanks for your help Mike, I'll close the issue.
