### ISSUE TITLE
Use of LADSPA

### ISSUE THREAD

**Issue by fgatin** [mikebrady/shairport-sync#212]
Hi Mike,

Great software!
I am trying to use ladspa filters to build a crossover, by applying a low-pass filter on the left channel and a high-pass filter on the right channel. I am using a Hifiberry DAC+ on top of a Raspberry Pi 2.
I have tried to install LADSPA filters but couldn't get any results.
I have tried to use a LADSPA host such as Ecasound but didn't get any results either.

Any ideas?

Florent

**Comment by mikebrady** [comment]
Hi Florent. Thanks for the post. I've never looked at the LADSPA system, I'm afraid, so I can't offer you any guidance. When sending output to an `alsa` device, Shairport Sync requires a real hardware output device in order to be able to read the true time delay, so I would not think that using a virtual `alsa` device as an output from Shairport Sync will work out well. Instead, a possibility might be to take the output from Shairport Sync via the `stdout` backend and route it into, say, Ecasound, for further processing.

**Comment by fgatin** [comment]
Hi Mike,

Thank you for the fast response!
I have managed to get the LADSPA filters working using the following command:
$ shairport-sync -v -o stdout | aplay -Dplug:pass  -f cd (pass is my crossover)

However now the synchronisation doesn't work anymore. Would it be any different if I used Ecasound?

Cheers.

**Comment by mikebrady** [comment]
Hi Florent – it would be no different as far as synchronisation is concerned, I'm afraid, unless Ecasound could guarantee a fixed delay. If it can – e.g. if it was guaranteed to be 250 ms, then you could compensate for it using the relevant Shairport Sync setting.

**Comment by fgatin** [comment]
Hi Mike,

I got everything working with filters and synchronous audio. Thanks for the input!

If anyone is interested, using the command `shairport-sync -v -o stdout | aplay -Dplug:filters f cd` activated the filters but unfortunately synchronisation was lost.
By using instead `shairport-sync -v -c /etc/shairport-sync.conf -- -dplug:filters` everything works fine.

Florent
