### ISSUE TITLE
avahi _raop._tcp

### ISSUE THREAD

**Issue by mfauvain** [mikebrady/shairport-sync#237]
Hi Mike, this is a question not an issue. I usually turn off avahi service publishing using the option disable-user-service-publishing=no in /etc/avahi-daemon.conf and advertise only the services I want (like afpd, vnc etc) but doing so prevent shairport from starting. Do you see a way to set a service in /etc/avahi/services/ like shairport.service? Tried this below with no luck, certainly missing a part. Can you help?
and thank you for shairport-sync works great. Marc

<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_raop._tcp</type>
    <port>5000</port>
  </service>
</service-group>

**Comment by mikebrady** [comment]
Hi Marc. There are two parts, I think to answering your question.

The first part is that the `/etc/avahi/services/` is for static service descriptions. Applications that can't advertise on Avahi themselves can have service descriptions placed here. Shairport Sync uses another Avahi API to advertise its service dynamically. This is necessary because part of the information that is advertised is generated dynamically at run time, and can not easily be placed in a static service description. I don't know what would happen if you put a static service description for Shairport Sync in the `/etc/avahi/services/` folder, but it won't be good. It might supersede the dynamic one.

The second part is that if you set  `disable-user-service-publishing` to `"yes"` (is that what you meant to write?) you explicitly prevent Shairport Sync from advertising its service. The setting is `"no"` by default.

You can explore what's being advertised using something like `avahi-browse`, part of the `avahi-utils` package.

I hope this helps.

**Comment by mfauvain** [comment]
Thank you very much. Yes indeed I am setting disable-user-service-publishing to "yes". I tried avahi-browse and got some details. However, in a loop here b/c even if I get details right and advertise a static service succesfully, shairport-sync won't start with disable-user-service-publishing set to yes.
Oh well, I'll dig further, let you know what solution I find. Cheers

**Comment by mikebrady** [comment]
Hi Marc. I'm closing this issue for the present. Please feel free to reopen it if there are any developments.

**Comment by mfauvain** [comment]
Hi Mike, I sorted out my 'issue' removing vino-server that would show with its proper name in avahi, instead using tigervnc server (much faster to connect btw). And I am able to advertise/not advertise the services I want with proper names (including shairport-sync). Thank you very much, massive stuff this shaiport-sync.
