### ISSUE TITLE
Shairport-sync was installed via package, but included no startup script.  Possible to recreate?

### ISSUE THREAD

**Issue by ubermacin** [mikebrady/shairport-sync#320]
Hello, I am very excited to have it running in alpine linux (system V) but the package didn't include the startup script.  Shairport-sync runs great if I run it from the command line (and using the config file I built) .  I tried the following to pull in the startup script manually: 

```
curl -L https://raw.githubusercontent.com/mikebrady/shairport-sync/master/scripts/shairport-sync.in > /etc/init.d/shairport-sync
chmod +x /etc/init.d/shairport-sync

rc-update add shairport-sync
rc-service shairport-sync start
```

it doesn't return an error, and adding -v to rc-service shairport-sync start gives me no feedback

**Comment by mikebrady** [comment]
Hi Jared, and thanks for the post. Are you installing on a Raspberry Pi?

**Comment by mikebrady** [comment]
[Update] Jared, using `shairport-sync.in` as the startup script won't work, because `shairport-sync.in` is modified during the normal installation process to produce `/etc/init.d/shairport-sync`. However, if you edit it slightly, it should work.

First, you need to find out where the Shairport Sync application was installed into, so do:
```
$ which shairport-sync
```
This will return something like:
```
/usr/local/bin/shairport-sync
```
Take note of the part of the pathname that occurs before the `/bin...` part – in this example, it's `/usr/local`.

Open the file you created at `/etc/init.d/shairport-sync` with your favourite editor (you might need to `sudo`) and search for the string `@prefix@`. You'll find a line like this:
```
DAEMON=@prefix@/bin/$NAME
```
Replace the string `@prefix@` with the piece of the pathname you noted earlier so that, in our example, the line would read:
```
DAEMON=/usr/local/bin/$NAME
```
That is, the prefix we found – `/usr/local` replaces the `@prefix@` string. Save the file, do:
```
$ sudo update-rc.d shairport-sync defaults 90 10
```
and reboot. It should work.

**Comment by ubermacin** [comment]
Hi Mike, thanks for the quick reply!  I am trying to run this on a raspberry pi 3.  I have a USB sound card too.  I made the changes you mentioned (though I have to use a different rc-update command, rc-update add shairport-sync) but it still won't auto auto start (for the record, my shairport-sync is at usr/bin).  I have noted that I need to manually call d-bus and avahi-daemon before shairport-sync runs manually.  So here is what I do to start shairport-sync:

```
dbus-daemon --config-file=/usr/share/dbus-1/system.conf
avahi-daemon -D
shairport-sync

```
Alpine linux is a fork from Arch Linux too if that makes any difference, though it runs system V.  Thanks again for the help, I'm documenting how this was all done and will add to the Alpine Linux wiki.  Alpine is fantastic for the RPI because it runs in memory rather than slowly killing off the SD card.

**Comment by mikebrady** [comment]
Thanks Jared. It sounds like there are other issues with the startup sequence – maybe that's why a startup script wasn't included. It seems startup scripts for `dbus` and `avahi-daemon` are needed too.

**Comment by mikebrady** [comment]
Thanks for this contribution. Please open a new issue if necessary.
