### ISSUE TITLE
Video Mirroring

### ISSUE THREAD

**Issue by ImAnOwl** [mikebrady/shairport-sync#332]
Hi,

this is not an issue, but i want to ask if it is possible adding mirroring to shairport? 

LG from Germany!

P.S.:

It's difficult to contact you, can I get your email?

**Comment by roblan** [comment]
try http://www.instructables.com/id/AirPlay-Mirroring-without-Apple-TV-using-RPi/?ALLSTEPS
But it looks like rPlay is not developed anymore so it could not work with recent iOS/macOS

**Comment by mikebrady** [comment]
Thanks for the post. Two be honest, there are no plans for adding video support to Shairport Sync. The focus of the application is really audio, and besides, as @roblan has mentioned, there seem to be difficulties with recent versions of iOS/macOS because the protocols, which are not public, seem to have changed.

**Comment by jorio2311** [comment]
hmm, it would be a realy nice feature, because rPlay doesn't anymore
