### ISSUE TITLE
Support for Plex Media Server

### ISSUE THREAD

**Issue by talamihg** [mikebrady/shairport-sync#375]
As described by this article on Plex's site, it looks like Plex has support for airplay ready devices. 
https://support.plex.tv/hc/en-us/articles/207197467-Can-I-use-AirPlay-with-Plex-

When I open my Plex mobile app to see avaliable devices to cast/share to, I do not see my shairport-sync box (raspberry pi install). 

With airplay devices, either apple devices have dlna support for plex, or plex has daap support for airplay. Which protocol is shairport missing?

**Comment by Yannik25** [comment]
Do you use an iOS device?

I can play music in the app and open control Center, swipe to the right, to switch the audio output to shairport


Plex for iOS
To connect to an AirPlay device in the Plex for iOS app, you'll just use the regular iOS Control Center as normal. Swipe up from the bottom of the screen to bring up the Control Center, then select your AirPlay device there. When you do so, content will be played on the selected device rather than on the iOS app itself and you can then use the iOS app to control playback.

**Comment by Yannik25** [comment]
Also able to send audio from movie, while watching on iOS

**Comment by talamihg** [comment]
I have the android app installed. I will have to check when I get back home and look at the settings in the Plex app. I also have an old iOS device I could use, ill check that out and see if it shows shairport as avaliable.

**Comment by mikebrady** [comment]
Excellent! I'll update my misleading comment later. Thank you.

**Comment by talamihg** [comment]
I can confirm that iOS Plex app does see the shareport device as a receiver, and that the android version of the app does not see it. I guess this is a controller issue where the android plex app does not converse over airtunes but does over airplay.
