### ISSUE TITLE
Could not establish a service on port 5000

### ISSUE THREAD

**Issue by Agavus** [mikebrady/shairport-sync#385]
Setup:

RPi model B connected via eth0 running "Jessie"
(USB soundcard is currently somewhere between China and Europe)
IPhone IOS 9.3.5
Itunes (Windows)

I installed Shairport sync following the installation instruction from the Readme.md to the letter. And it worked briefly on both the Iphone and Itunes (Itunes recognized the Pi but was only able to stream music to it after a windows restart). A hour later I checked again but on both clients the Pi was not available any more. After a couple re-installs including a new Jessie image I got it working once again but again only briefly. 

The only adjustments to the config file are the suggested volume_range_db and drift  settings for the Pi.

output of shairport-sync -v:
`..`
`Unable to listen on IPv4 port 5000. The error is: "Address already in use".`
`Unable to listen on IPv6 port 5000. The error is: "Address already in use".`
`Could not establish a service on port 5000 -- program terminating. Is another Shairport Sync running?`
`Request to shut down all rtsp conversation threads`

Changing the port does not fix the problem. Disabling IPv6 also does not fix the problem. 

I am not sure what I am doing wrong but the fact it was working briefly twice makes it even more annoying because I am close but there is still a small issue that I am not able to solve. 

Help is very much appreciated. 

Thanks

Ronald

**Comment by mikebrady** [comment]
Thanks for the report. The diagnostic message indicates that Shairport Sync is already running, presumably because it has been started as a service – this is to be expected if you have followed the installation instructions carefully. If you restart the RPi and check that Shairport Sync is already running, using something like `$ ps aux | grep shair` , then you could get that issue out of the way.

The issue of the service disappearing from iTunes and the iPhone is likely caused by something else. Sometimes it's a firewall problem. Or, it could be a network issue, which could be caused by a faulty router. Sometimes routers don't maintain full connectivity between the wired and wireless domains, especially when it comes to multicast, which is used by Bonjour/Zeroconf.

You can use an app called "Discovery" on an iPhone to see whether the Bonjour/Zeroconf signals that advertise the AirPlay service provided by Shairport Sync are reaching the phone. Also, if you install `avahi-utils` on the RPi, you can see what Avahi/Zeroconf signals are being generated. If they are being generated on the RPi and not received on the iPhone, then there's a network problem.

**Comment by Agavus** [comment]
Hi Mike,

Thanks for you fast reply. 

This is what I got so far:

`pi@raspberrypi:~ $ ps aux | grep shair`
`shairpo+   532  0.0  1.2  24172  3020 ?        Ssl  23:05   0:00 /usr/local/bin/shairport-sync`
`pi         581  0.0  0.8   4268  1948 pts/0    S+   23:08   0:00 grep --color=auto shair`

`pi@raspberrypi:~ $ avahi-browse -a`
`+   eth0 IPv4 AF31192A3A11@Raspberrypi                      AirTunes Remote Audio local`
`+   eth0 IPv4 raspberrypi [b8:27:eb:45:87:80]               Workstation          local`

The "Discovery" keeps scanning forever but finds nothing :(

I will see if I can eliminate the router a the cause of the problem by switching some stuff around and using only wired connections.

**Comment by mikebrady** [comment]
Yes, that seems like a good idea. It looks like it's running properly on the RPi.

**Comment by Agavus** [comment]
Hi Mike,

You were right. As soon as I connect my laptop directly to the router the Pi is shown immediately in Itunes. Thus this seems to be a problem with my router or the AP.  Thanks

**Comment by mikebrady** [comment]
Cool!

**Comment by Agavus** [comment]
I will close this now because I need to wait untill the new router is up and running to see if this new router will allow me to use shairport-sync wirelessly. Thanks for the good work. I hope this solution will keep working in the future even if Apple updates the protocol. Cheers

**Comment by mikebrady** [comment]
Thanks.
