### ISSUE TITLE
mixer_control_name is not working

### ISSUE THREAD

**Issue by thueske** [mikebrady/shairport-sync#386]
Hey,
awesome project - thanks for your support!

I use shairport-sync @ my first gen banana pi.

The working configuration is:
```
general = {
  name = "Tobi AirPlay";
};

alsa = {
  output_device = "hw:0";
}
```

With mixer_control_name = "Master" I get errors like:
```
Open Mixer
Mixer device name is "hw:0".
Mixer Control name is "Master".
Setting volume db to 0.000000.
Can't set playback volume accurately to 0.000000 dB.
Failed to set playback dB volume
avahi: avahi_unregister.
```

Any ideas? Here is my alsamixer output:
<img width="1245" alt="alsamixer" src="https://cloud.githubusercontent.com/assets/436986/19212131/6859f424-8d4b-11e6-9231-de512c11bbde.png">

Thanks! 😊

**Comment by mikebrady** [comment]
Let me check it out...

**Comment by mikebrady** [comment]
Is if possible that you're getting a debug message earlier on: 'note: the hardware mixer specified -- "Master" -- does not have a dB volume scale, so it can't be used. Trying software volume control.' or possibly 'Cannot get the dB range from the volume control "Master"'?

**Comment by thueske** [comment]
Oh, yes, I get:
```
note: the hardware mixer specified -- "Master" -- does not have a dB volume scale, so it can't be used. Trying software volume control.
Cannot get the dB range from the volume control "Master"
```

**Comment by mikebrady** [comment]
What it means is that the mixer in the card does not offer decibel-based settings, so Shairport Sync can't use the mixer as a volume control. You can still use the card though, simply by not specifying any mixer name in your configuration. In that case, Shairport Sync will do software volume control.

You should, however, set the "Master" mixer's value to 100%, so that the output from Shairport Sync is not attenuated by the mixer as it goes through. You can do it manually, or via a script like:

```
$ /usr/bin/amixer -D hw:0 set "Master" 100% > /dev/null 2>&1
```
Something like it should work on your machine.

**Comment by thueske** [comment]
Thanks! Yes, without the mixer_name it works, but I hoped that the hardware is supporting decibel-based settings as well.
