### ISSUE TITLE
Delay between pausing & sound stopping

### ISSUE THREAD

**Issue by dbenamy** [mikebrady/shairport-sync#39]
I just set up shairport-sync on raspbian with a usb audio device like this:
```
sudo apt-get --yes install autoconf libtool libdaemon-dev libasound2-dev libpopt-dev avahi-daemon libavahi-client-dev libssl-dev
git clone https://github.com/mikebrady/shairport-sync.git /package/shairport-sync/
cd shairport-sync
git checkout 2.2
autoreconf -i -f
./configure --with-alsa --with-avahi --with-ssl=openssl
make
sudo ./shairport-sync -a AirPi --statistics -- -d hw:0 -t hardware -c PCM
```

On osx 10.8 it shows up as an audio output device and I can send sound to it, but I see pretty close to 2s of delay in response with (un)pausing, and with the osx volume change clicks (although the actual volume changes immediately).

The statistics output looks like
```
Sync error: -45.8 (frames); net correction: 194.3 (ppm); corrections: 194.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6098, min and max buffer occupancy 208 and 235.
Sync error: 70.7 (frames); net correction: -110.4 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6088, min and max buffer occupancy 227 and 235.
Sync error: 73.1 (frames); net correction: -121.7 (ppm); corrections: 121.7 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6057, min and max buffer occupancy 224 and 236.
```

I previously had abrasive/shairport running on this machine. When I saw this delay with shairport-sync, I thought maybe it was loading a shairport lib so I reinstalled shairport to see what files it copies over so I could remove them, and it looks like shairport's make install just installs the binary (no libs).

I also had pulseaudio set up via apt but uninstalled all those packages:
```
The following packages will be REMOVED:
  gstreamer0.10-pulseaudio gstreamer1.0-plugins-bad{a} libasound2-plugins{a} libdirectfb-1.2-9{u} libfluidsynth1{a} libmad0{u}
  libmikmod2{u} libportmidi0{u} libpulse0 libsdl-image1.2{a} libsdl-mixer1.2{a} libsdl-ttf2.0-0{a} libsdl1.2debian{a}
  libsmpeg0{a} libts-0.0-0{u} libvorbisfile3{u} pulseaudio pulseaudio-module-x11 pulseaudio-module-zeroconf{a} pulseaudio-utils
  python-pygame{a} python3-pygame{a} tsconf{u}
```

Thanks so much for an awesome project and for your help!

**Comment by mikebrady** [comment]
Thanks for your interest in Shairport Sync. Actually it sounds like it might be working as expected. Let me explain.
* If you connect to AirPi from within iTunes, then there will be a delay of around 2 seconds between when sound data is emitted by iTunes and when it comes out of the AirPi speakers. However, iTunes itself delays the sound going to the Mac's speakers by the same amount so that the Mac's output and the AirPi's outputs are in sync. This is by design.
* The same thing happens with a movie you play through iTunes or Quicktime Player or from the Video app on the iPhone – the video is delayed for two seconds to match the delay in the audio.
* However, if you just add AirPi as an extra sound output through the Audio MIDI Setup app, then a delay of exactly two seconds will be audible. Again, this is the way Airplay and iTunes have been designed. 

Am I on the right track – is this explaining there behaviour you're hearing?

**Comment by dbenamy** [comment]
Interesting!

To be clear: I was changing the sound output device in system preferences and then listening to pandora in chrome. Ie, on this screen:
![dwellclick](https://cloud.githubusercontent.com/assets/354611/6011276/d4574244-aaee-11e4-95bf-e79d986d801c.png)

I wasn't also sending sound to the local speakers. I didn't know you could send to multiple outputs!

This all makes sense although seems like funny UX. An an easy example, if Apple knows that the system volume change clicks are going to be delayed, I'm surprised they still play them. It'd be nicer to not have them rather than having them be delayed.

But if that's how the protocol and/or existing parts of the stack work, I don't imagine you can do anything about it.

Thanks for explaining!
