### ISSUE TITLE
USB Audio Interface Playback

### ISSUE THREAD

**Issue by aspina2009** [mikebrady/shairport-sync#435]
Hi. Shairport-sync is working perfectly for the dedicated audio card, but I can't get the alsamixer to use my usb audio interface. Shairport-sync is being forced to output audio through the monitor via HDMI. How do you make shairport-sync switch to the audio interface?

**Comment by mikebrady** [comment]
Hi there. What computer? What USB device?

**Comment by aspina2009** [comment]
I'm using a raspberry pi running ubuntu mate and a focusrite 2i2

**Comment by mikebrady** [comment]
Thanks – that sounds nice. So, you can use `aplay -l` to figure out what audio devices the Pi can see, as it were. This is what I get – I have an IQaudIO device connected, and you can see it is card 1:

```
pi@kitchen:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
So, the output device setting I use for Shairport Sync is: `hw:1`. Can you post the output from you setup please?

**Comment by aspina2009** [comment]
Here's what aplay printed out for me

`**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: USB [Scarlett 2i2 USB], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

**Comment by aspina2009** [comment]
Here's what play printed out.

**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: USB [Scarlett 2i2 USB], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by mikebrady** [comment]
Super. So, it looks like you should tell Shairport Sync to use output device `hw:2`. Do this by editing the setting `output_device="default"` to `output_device="hw:2"` in the alsa section of the configuration file. Make sure you uncomment the line by ensuring the `//` as the start of the line is removed. The line should look like this:
```
  output_device = "hw:2"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
```
Does this work for you?

**Comment by aspina2009** [comment]
It's still choosing the monitor output. 

How come it's not "hw:1"? Are they not 0 indexed like they are in the aplay output?

**Comment by mikebrady** [comment]
Hi there. Yes indeed – it should be `hw:1`. I updated the post (FWIW, the mail you get does not contain any corrections, so it's always worthing coming back to the web page).

**Comment by mikebrady** [comment]
If this isn't working, then the next step would be to get Shairport Sync to leave information in the logs. To do this, set `log_verbosity=2` in the configuration file. Then, in the log file, you'll get stuff from Shairport Sync that might help us find out what's happening.

**Comment by johnheaven** [comment]
Hi there. I had a problem with getting shairport-sync to play from my Raspberry Pi's USB soundcard. It was only a problem when only booting into CLI (i.e. no graphical interface). Killing the shairport-sync process and then restarting it worked fine, so it seemed it was not waiting for ALSA to load before starting up the shairport-sync process.

I edited /lib/systemd/system/shairport-sync.service and added "alsa-restore.service" after Requires and that seems to have solved it. No idea whether this is the right thing to do (I'm no great expert on systemd) but it seems to be working for the time being.

Thanks for shairport-sync by the way! Such a great piece of software. :)

**Comment by mikebrady** [comment]
Thanks for the kind words, and for the clarification!

**Comment by beinaendi** [comment]
Hi everybody,

first of all, many thanks to Mike Brady for this software. I really enjoy it.

I came to this post because I have a similar problem. Four raspis, everything works perfect with 3.5mm jack or with HDMI output, but I cannot get any sound on my USB soundcard.

Already tested the USB soundcard with "speaker-test -Dhw:Device,0 -c2 -twav" and it works fine.

I tried setting 'output_device = "hw:1"' in the shairport-sync.conf what didn't change anything, although my USB card is card 1.

First of all, what is strange at the moment, my shairport-sync.conf file is located in /usr/local/etc/ and not in /etc. Is this correct?

I set "log_verbosity=2" but cannot find a log file. Where should it be located?

Thanks for your help

**Comment by mikebrady** [comment]
Thanks for the post.

First, you can make Shairport Sync use `/etc/shairport-sync.conf` by using the configuration flag `--with-sysconfdir=/etc` before doing the `make` – see the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md) guide for more on this.

Secondly, there is a contradiction in what you report about the USB device: if `$ speaker-test -Dhw:Device,0 -c2 -twav` is correct, then the USB device would not be `hw:1`, so that needs to be resolved. IMHO the output of `speaker-test` is confusing – I use `alsamixer` and it's much simpler.



Thirdly, use the command `journalctl` to view the logs.

**Comment by beinaendi** [comment]
Thank you for the quick answer.

1) I found out how to install configuration files in /etc. In earlier times this happened automatically without flag. That's why I was surprised about not finding the files.

2) When I look for speaker-test options it says you need to insert the name, then the number of the device, so "Device,0" should be correct.

aplay -l returns as follows (sorry, it's German):
**** Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: ALSA [bcm2835 ALSA], Gerät 0: bcm2835 ALSA [bcm2835 ALSA]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7
Karte 0: ALSA [bcm2835 ALSA], Gerät 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: Device [USB Audio Device], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

Thus, it should be hardware 1, device 0 ("hw:1,0" or "hw:1") and if you use the name in speaker-test, it should be "Device,0". So this is not confusing for me, except if I understood something wrong.

3) I will test journalctl later on and report the results.

**Comment by beinaendi** [comment]
I finally solved the problem. FYI, I followed the instructions on [http://www.redsilico.com/multiroom-audio-raspberry-pi](url)

It says you need to edit the file /etc/init.d/shairport-sync, search for this line
`start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d || return 2`
and replace it with
`start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Kitchen" -- -d hw:0 -t hardware -c "PCM" || return 2`

I guess this is higher prioritized than `output_device = "hw:1"` in /etc/shairport.conf

The solution was to change it to
`start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d -a "Kitchen" -- -d hw:1 -t hardware -c "Speaker" || return 2`

**Comment by mikebrady** [comment]
Thanks. That a fine write-up, but it's a bit outdated, and I think that's where the confusion is coming from. In his blog, he uses and modifies a System V initialisation script. The RPi now uses `systemd` but has backwards compatibility with System V stuff. The real issue, though, is that he hard-wires the device number into that script instead of using the configuration file. For new installations, I'd suggest you follow the instructions in the README exactly – beware of the mix-and-match approach.
