### ISSUE TITLE
no log file when running as deamon (systemd)

### ISSUE THREAD

**Issue by ddittmar** [mikebrady/shairport-sync#450]
Hi,

first of all thanks for this greate software. It runs like a charm.

I've followed your install instruction to compile and run `shairport-sync` as a deamon (systemd) on a raspberry. I have sometimes trouble with the alsa volume control (it does not work sometimes) but I can't find the log. When I look in `/var/log` I can not find the log file of the deamon.

Version: `2.8.6-OpenSSL-Avahi-ALSA-sysconfdir:/etc`

Config: 
```
general =
{
	name = "%H";
	output_backend = "alsa";
	mdns_backend = "avahi";
	statistics = "yes";
	drift = 352;
	resync_threshold = 0;
	log_verbosity = 1;
};

alsa =
{
	output_device = "default";
	mixer_control_name = "PCM";
};
```

**Comment by mikebrady** [comment]
Thanks for the post. Shairport Sync logs to the regular system log. If it's a recent version of standard Raspian – and it seems to be since it's got `systemd` –  then you can access the log with the `journalctl` command. For example `$ sudo journalctl -f -n 100` will display the last 100 lines (`-n 100`) of the log file and will follow (`-f`) any updates to the log. To see volume changes, it might be necessary to set the `log_verbosity` of Shairport Sync to 2 (I'm not near a machine now, so I can't check).

**Comment by mikebrady** [comment]
Okay to close this issue?
