### ISSUE TITLE
One shairport-sync instance multiple service name?

### ISSUE THREAD

**Issue by srb37** [mikebrady/shairport-sync#452]
Any possibility of running one shairport-sync instance with multiple service names?  I'd like to be able to leverage the "run_this_before_play_begins/ends" to run a different script depending on which service name was selected.  This could allow me to have one service named "Kitchen" the other "Living Room" and have a script tell my matrix amplifier to switch outputs depending on which script/service was activated.

**Comment by mikebrady** [comment]
Thanks for the interesting post. I can't think how you could do this, but have you tried running two instances of Shairport Sync? Connecting to one could activate the switch outpouts one way, whereas connecting to the other could switch outputs the other way, perhaps.

**Comment by mikebrady** [comment]
Can I close this issue please?

**Comment by ccutrer** [comment]
I'd agree with this. I plan of have a 6x18 matrix amplifier, with 2 or 3 inputs of shairport-sync. But shairport-sync needs to be able to change its output device dynamically. A more detailed use case:

I have a raspberry pi with 3 usb sound cards: c1, c2, c3. I have a matrix amp, with 6 inputs, and inputs i1, i2, and i3 are each connected to the corresponding sound card on the pi. The matrix amp has 18 outputs - I'll just name a few - Kitchen, Living Room, Master Bedroom, Deck, Child's Bedroom. In order to get shairport-sync to advertise a separate speaker for each actual audio zone, I run a separate instance of the service for each one. Now, when I select Kitchen on my iPhone, shairport-sync run_this_before_play_begins script will fire, and with my own management I decide to use i1, and tell my amp to turn on the kitchen zone, and switch it to input i1. Then I need to tell shairport-sync to use output c1. The next person that connects to Living Room, my script will choose i2/c2 the same way. If I statically assign 6 of my shairport-sync instances to each sound card, then it's pretty much guaranteed that at some point two zones will be active wanting to play different things that shairport-sync has configured to use the same card, and it won't work. Doing the output assignment when a zone starts playing allows multiplexing a small number of active inputs to a large number of possible outputs. I could even do a virtual zone ("All Basement Zones", "Common Areas") by just telling my amp to turn on multiple zones all tuned to the same input.

The workaround is to get one sound card per zone (which I currently do for a smaller 6 zone setup), but that has issues in itself (my raspberry pi starts to cut out with 4 or more zones active, not due to CPU, but presumably from current draw, even though I have a powered USB hub. It also means that I can't use my matrix to allow other inputs into the system (such as TVs), because each output maps 1:1 with a shairport-sync zone, and I can only build either 18 1x1 zones, or a 6x18 matrix. 6 distinct inputs is more than sufficient if I can properly multiplex them.

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
