### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jbunce92** [mikebrady/shairport-sync#469]
HI, Sorry to ask such a basic question but the file /etc/shairport-sync.conf can't be found on my RPi, as such I cant now edit the name or settings of shairport-sync which is running! Any ideas on how to find it!?

**Comment by mikebrady** [comment]
Thanks for the post. I can think of two possibilities. First, did you do the `make install` step? Alternatively, when you were configuring it prior to `make` and `make install`, is it possible that you omitted the `--sysconfdir` option? If so, the configuration sample would be placed in `/usr/local/etc` rather than in `/etc`.

**Comment by mikebrady** [comment]
Hi there. Did you have any luck with this?

**Comment by jbunce92** [comment]
Hi, So sorry for the delay in replying! I've found the sample at /usr/local/etc. Unfortunately shairport-sync was my first RPi project so I somewhat fumbled my way through it and so don't really remember missed out steps. I was just thrilled it was working suddenly so have been using it ever since. I only wanted to get back into the config setting to change the name from default. I guess this makes it more complicated?

**Comment by mikebrady** [comment]
That great. It would be worth trying to change the name in the file `/use/local/etc/shairport-sync.conf` and restart.

**Comment by jbunce92** [comment]
Thats worked perfectly! Thanks Mike!

**Comment by mikebrady** [comment]
Closing the issue – please open a new one if necessary.
