### ISSUE TITLE
Question: Apple vs Hammerton decoder

### ISSUE THREAD

**Issue by moodeaudio** [mikebrady/shairport-sync#483]
Hi Mike,

Really great 3.0 release !!!

Any benefit to using Apples ALAC decoder?

-Tim

**Comment by mikebrady** [comment]
Thanks Tim. I haven't been able to detect any difference, TBH. Also, there doesn't seem to be much difference in processor load. However, it's nice to be able to try it out, IMHO.

**Comment by moodeaudio** [comment]
Always good to have options :-)

**Comment by nettings** [comment]
Can I suggest to leave this open and maybe tag it as "discussion" or "documentation"? I had the exact same question and a standard github search in this repository didn't find it - I only stumbled on this issue when I tried to open a new one.
Since this is a lossless codec, if there isn't any difference in CPU load _and_ the Apple implementation doesn't offer any additional benefits to the user (such as more supported sample rates or sample formats), they should yield the same result bit-for-bit (unless one is buggy).
