### ISSUE TITLE
Please support the feature, handle the RTSP OPTIONS's PAUSE request.

### ISSUE THREAD

**Issue by lujnan** [mikebrady/shairport-sync#495]
Hi, Mike, Can you support the `PAUSE` request, Let the `PAUSE` request to make a metadata item. That we can update us app's UI quickly.

**Comment by mikebrady** [comment]
Unfortunately, the PAUSE request isn't used, as far as I know. Instead, what happens when iTunes pauses is that a "FLUSH" is issued. When a YouTube video playing in Safari is paused, a "TEARDOWN" is issued, no FLUSH. Metadata is sent for any flush that occurs during play, but some flushes happen for internal reasons. I could add a special metadata item just for a FLUSH request, if it was any use.

**Comment by lujnan** [comment]
Can you add just for a FLUSH request not with internal reasons.

**Comment by mikebrady** [comment]
OK, I've just pushed an update with the FLUSH request metadata in place. The code is `flsr`. Also, at log verbosity 1 or greater, it prints out the initial  `fmtp` data. If you got a chance, would you be kind enough to run it using the `doubleTwist` program and let me see what comes back. (Thanks for this idea, BTW!)

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
