### ISSUE TITLE
shairport-sync > fifo > pifm

### ISSUE THREAD

**Issue by mezhinsky** [mikebrady/shairport-sync#506]
Trying to stream music from iphone to vintage radio and having issue with shairport-sync buffer.
Im using pipe backend as communication between shairport-sync and pifm. CPU warmup to 100%

```
Too-short retransmitted audio packet received in control port, ignored.
Too-short retransmitted audio packet received in control port, ignored.
Player: packets out of sequence: expected: 10499, got: 11011, with ab_read: 11012 and ab_write: 11136.
Aliasing of buffer index -- reset.
Player: packets out of sequence: expected: 11192, got: 11704, with ab_read: 11705 and ab_write: 11828.
Aliasing of buffer index -- reset.
Player: packets out of sequence: expected: 11895, got: 12407, with ab_read: 12408 and ab_write: 12440.
Output sample ratio is 1
Aliasing of buffer index -- reset.
Player: packets out of sequence: expected: 12523, got: 13035, with ab_read: 13036 and ab_write: 13161.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.
Buffers exhausted.

```
pifm play .wav file normal and shairport-sync play alsa backend good as well but non with both sides. maybe anyone knows what is this?

**Comment by mikebrady** [comment]
That looks awfully like a bad network connection. If it's WiFi, it might be worth checking that power management is off...

**Comment by Mezhinsky** [comment]
well this is rpi2 and im using ethernet connection

**Comment by mikebrady** [comment]
Just looking at  PiFM [here](http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter) it looks like it needs sound at 22,050 samples per second, not the 44,100 samples per second provided by Shairport Sync. Am I reading it correctly?

**Comment by Mezhinsky** [comment]
im try 22050 but no difference  - in one widow im running shairport and in the other Pifm, just after pifm starts working shairport begins purge, and in the radio music flows very slow :(

**Comment by mikebrady** [comment]
Thanks for the update. The thing is that Shairport Sync does not provide audio at 22,050 samples per second, only 44,100 or higher.

**Comment by Mezhinsky** [comment]
Pifm can 44100 too i think

**Comment by mikebrady** [comment]
Is there any way to check? Maybe try to play a track, without Shairport Sync, that's encoded as 44,100 samples per second stereo?

**Comment by mikebrady** [comment]
Seems to be 22,050 only – see http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter.

Okay to close this issue?

**Comment by sumi104** [comment]
Hi, Mezhinsky, 
I also thought that I stream iPhone music to a vintage radio.
I found the [PiFmRDS](https://github.com/F5OEO/PiFmRds.git) is better than the original PiFm. You can use 44,100 sample rates per second stereo.
But the PiFmRds cannot play RAW audio data because it use the sndfile library. 
I've transferred  music from a iPhone to a vintage radio. I use stdout option of Shairport-sync and 
I converted RAW audio data to WAV data with sox.
I could stream iPhone music to the radio with  the following command:

 sudo shairport-sync | sudo sox -r 44100 -e signed-integer -b 16 -c 2 -t raw - -t wav - | sudo pi_fm_rds -audio -

Here is the config file for stdout: 

general = 
{
name = "Air2Radio"
output_backend = "stdout";
}

I used the Stretch and Raspberry Pi 1 model B.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
