### ISSUE TITLE
 udp_port_range config option

### ISSUE THREAD

**Issue by kingosticks** [mikebrady/shairport-sync#508]
This might be my misunderstand rather than a bug (and hardly a big one at that) but is it supposed to be a preincrement rather than a postincrement at https://github.com/mikebrady/shairport-sync/blob/development/rtp.c#L565 ? 

I ask because the comment in the config file specifies at least 3 udp ports are needed so I left udp_port_base at 6001 and changed udp_port_range to 3. I would have thought this would restrict the ports used to 6001, 6002 and 6003 but the way that loop condition is written it'll also use 6004. Is this the intended behaviour? I've been opening udp ports 6001-6003 (as well as tcp 5000) on my firewall and run into some intermittent problems. I was wondering if it could be due to this.

**Comment by mikebrady** [comment]
Hi Nick. Thanks for the post. Let me check this and figure it out.

**Comment by mikebrady** [comment]
Just looking at the code now, I'm pretty sure that postincrement is correct. If none of the ports were in use, it would return the `port_base` as the first one, so long as it's not zero. If it is zero, an arbitrary port will be chosen.

The code is in a `do ... while` loop, and the condition is checked at the end. Furthermore, the order of evaluation of the components of the condition expression means that the `desired_port` will only be incremented if its value pointed to a port that was already in use or otherwise in error.

So, as I say, I *think* it's okay, but would welcome your comments. Also, if you could nail down any of the intermittent issues, I'd be delighted to investigate them.

**Comment by kingosticks** [comment]
I really hope I'm not wasting your time with something stupid here but maybe I haven't explained very well:

1. audio_socket's `bind_port()`:
    * desired_port=6001; bind succeeds; use 6001 - all done!
2. control_socket's `bind_port()`: 
    * desired_port=6001; bind fails (still in use); check 6001 < 6004; inc desired_port = 6002
    * desired_port=6002; bind succeeds; use 6002 - all done!
3. timing_socket's `bind_port()`:
    * desired_port=6001; bind fails (still in use); check 6001 < 6004; inc desired_port = 6002
    * desired_port=6002; bind fails (still in use); check 6002 < 6004; inc desired_port = 6003
    * desired_port=6003; bind succeeds; use 6003 - all done!
4.  If you then get another call to `bind_port()` ??!!!?:
    * desired_port=6001; bind fails (still in use); check 6001 < 6004; inc desired_port = 6002
    * desired_port=6002; bind fails (still in use); check 6002 < 6004; inc desired_port = 6003
    * desired_port=6003; bind fails (still in use); check 6003 < 6004; inc desired_port = 6004
    * desired_port=6004; bind succeeds; use 6004 - all done!
5.  If you then get yet another call to `bind_port()` ??!!!?:
    * desired_port=6001; bind fails (still in use); check 6001 < 6004; inc desired_port = 6002
    * desired_port=6002; bind fails (still in use); check 6002 < 6004; inc desired_port = 6003
    * desired_port=6003; bind fails (still in use); check 6003 < 6004; inc desired_port = 6004
    * desired_port=6004; bind fails (still in use); check 6004 < 6004; NO!

The point of all that is to show it ends up using port 6004. Maybe that's intended behaviour but I expected the 4th call to have failed to bind when using `udp_port_base = 6001` and `udp_port_range = 3`.

But having said all that, after looking some more at the rest of the code, now I'm not sure why `bind_port` would be called more than three times. Does that happen when another client connects? I mean, presumably there's a reason why the default config has `udp_port_range = 100`, right?

**Comment by mikebrady** [comment]
Hi Nick. Many thanks for this commentary and analysis.

At the end of 5. above, the code would find that it can not allocate a port because they are all busy and, upon exit from the `do ... while` loop it should emit an error message "error: could not bind a UDP port!" and die. That's not a very friendly behaviour, TBH, so I'll see about changing that.

To the substance of your question – could more than three ports be needed. The answer is, oddly, "yes". Here is a scenario; I wonder if it jibes with your experience and I hadn't thought of it until now.
1. When a play session is terminated, if may take a little while for everything to be correctly closed down.
2. While the player thread is closing everything down, the ports may remain allocated to it for a while, 3. During that time, if a new play session is starting up, the new player thread will look for ports, and, depending on timing, may be unable to use the ports used by the previous play session. (This can happen when, of instance, you switch from one YouTube video to another – the play session is abruptly stopped and a new one started very quickly afterwards. It is one of the scenarios I had in mind during the recent push to make all this code properly re-entrant and thread-safe.)

The take away messages so far are:
1. Allow more than three ports please – I suggest 10. (The 100 was just a number big enough not to worry about while I was developing the code...)
2. I will try to modify the code so that Shairport Sync doesn't die but does something a little more graceful.

**Comment by kingosticks** [comment]
Yes, i think we'll certainly be increasing the port range. In retrospect it seems pointless to constrain it like I've done, but once you start playing with firewall settings you can lose perspective! 

The remaining intermittent issue we have is likely to be related to starting shairport-sync before the network is quite ready. So that's certainly my issue to resolve.

I think we can close this issue. Thanks for your help and patience.

**Comment by mikebrady** [comment]
Thanks Nick. You might be right about the postincrement. I'll check when I get a quiet moment.

**Comment by mikebrady** [comment]
Hi Nick. You were right about that off-by-one problem. I've push an update.

**Comment by kingosticks** [comment]
Oh nice, thanks for taking a look. And thanks for this great software.
