### ISSUE TITLE
For all raspberry pi user (Raspbian Jessie)

### ISSUE THREAD

**Issue by T0b145** [mikebrady/shairport-sync#547]
I had some struggles getting the shairport-sync started and couldn't find a solution on github. Finally I found a solution on http://komputermaschine.blogspot.de/2015/03/raspberry-als-shairport-empfanger-2015.html. 

After the described installation process I didn't reach my device via the Airplay option from my phone.
In my case, I had to create the following start-up file after the installation via:

nano /etc/systemd/system/shairport-sync.service

with the following content:

```
[Unit]
Description=Shairport AirTunes receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
[Service]
Type=simple
ExecStart=/usr/local/bin/shairport-sync -a "MyShairport"
Restart=always
[Install]
WantedBy=multi-user.target
```

MyShairport is the name that is shown on my Phone and can be changed. 

After a reboot the service worked fine for me. Unfortunately, the service does't start on startup every time and a new startup is required (sometimes a hard restart). I still don't know why this is the case. Anyway, I hope this helps some of you.

**Comment by mikebrady** [comment]
Thanks for this contribution, but I'm afraid I do think there are some problems with it. 

* Your script starts Shairport Sync as `root` and not as the less-privileged user `shairport-sync`.
* The Service Name is hardwired into the script instead of being specified in the configuration file. 

Both of these are undesirable features of the script.

I can't help thinking that there is some other problem with your setup which you script is working around. Maybe some other contributors might have some views...

**Comment by T0b145** [comment]
Thanks for your comment. I figured that it is just a simple workaround, but I couldn't find another solution. Improvements are appreciated.

**Comment by mikebrady** [comment]
Yes, indeed – it's always good to get new ideas and improvement. Thanks again.

**Comment by mikebrady** [comment]
Thanks for this contribution. Closing the issue. Please open a new one if necessary.
