### ISSUE TITLE
Crash with pulse 11

### ISSUE THREAD

**Issue by CesareVin** [mikebrady/shairport-sync#595]
Hello Mike,
thank you for shairport, it's an awesome software!
I have some issue trying to use the latest pulseaudio 11 as streamer.
Pulse 11 enhance module-raop-sink and now i'm able to send stream from pulse to shairport, awesome!
It work great if I stream to a single shairport endpoint.
Now i'm trying to setup a multiroom scenario, i will try to explain this scenario:

-  2 speakers (shairport endpoints), SPK_1 and SPK_2.

- i would like to stream BT (or any other stream supported by pulse like mpd or pipe or jack) to SPK_1 and then play audio also to SPK_2, in sync.

To meet the needs i load pulse module as follow:
below the first endpoint
> pactl load-module module-raop-sink server=[{speakerIP}]:5000 sink_name=SPK_2 protocol=UDP encryption=RSA codec=ALAC channels=2 format=16 rate=44100

and the localhost endpoint (to play stream in sync i need to play also SPK_1 trought shairport)
> pactl load-module module-raop-sink server=[127.0.0.1]:5000 sink_name=SPK_1 protocol=UDP encryption=RSA codec=ALAC channels=2 format=16 rate=44100

now to stream pulse sink-input i load the combine-module as below

> pactl load-module module-combine-sink sink_name=combined slaves=SPK_1,SPK_2 adjust_time=0 channels=2 format=16 rate=44100

and then set this sink as default (pacmd set-default-sink {sinknumber}) or moving existing sink-input to combined (pacmd move-sink-input {sinknumber}) if stream is just started.
At this point, after some minutes shairport crash (randomly either SPK_1 or SPK_2).
Looking at logs i see some FIXME messages, these messages seem to be related to the hammerton decoder, an example is 

> FIXME: Not enough space if the output buffer for audio frame - E3.\n

this leads me to think that the problem is related to the frame decoding, i never see these messages in one shairport endpoint scenario.

I tried to play with _audio_backend_buffer_desired_length_in_seconds_ and _audio_backend_silent_lead_in_time_ but without success.
Now i would like to try with the apple decoder [https://github.com/macosforge/alac](url) to understand if problem really dependes on it but i use a custom (buildroot based) distro and i need to make a buildroot package to support libalac. (i need more times to do that)

I try with alsa and pulse audio backend, same issue.

I use shairport 3.1.2 --with-alsa --with-ssl=openssl --with-soxr --with-metadata --with-pipe --with-stdout --with-avahi --with-pa (--with-apple-alac soon  ;-) )
if I can give you more information or do other tests...
Thank you again.

**Comment by mikebrady** [comment]
Thanks for the interesting report.

I’m not sure of the physical setup: Is it the case that one of the Shairport Sync instances (SPK_2) is a separate machine and the other (SPK_1) is running on the same machine as those three PulseAudio modules?

It does seem to be the case that the Hammerton decoder is incomplete, so it would be worth trying the ALAC decoder. However, my experience is that these messages show up when the data to be decoded has been corrupted in some way.

If my understanding of the setup is correct, I would be concerned that the pulse to raop converter is not reentrant, so that two instances of it running at the same time might be interfering with each other and causing incorrectly formed packets to be sent.

**Comment by CesareVin** [comment]
Yes you understand the setup but i also tried out with 3 devices (SPK1,SPK2,SPK3) where shairport run only on 2 of these, SPK1 and SPK2.
In this scenario SPK3 work only as "streamer" with pulse and three modules.
Same result, shairport crash with segmentation fault.
I compile alac decoder but configuring shairport with --whit-alac something fails (it's so strange configure has problem with libsoxr, problem disappearing removing --whit-alac flag) i will investigate on this and eventually i will open a dedicated issue.
I will investigate on your suggestion looking at not reentrant code in the pulse module-raop.
My goal would be to play music in sync also from the "streamer" (which would be a speaker itself), i tried out foorked-daap, it's quiet simple and work fine with remote speaker, but the "streamer" is out of sync.
Would you have any suggestion on how i can do that with shairport?
Thank you again.

**Comment by mikebrady** [comment]
Thanks. So, we know that the Hammerton decoder is incomplete, so that for some sequences of data, it will fail. My experience is that the only time these sequences occur is when they are faulty — typically they have been corrupted in some way. (I could be wrong about this, of course.) But for the moment, it seems at least possible that the crashing of Shairport Sync indicates that something is wrong with the source data. If crashing does not occur when only one `module-raop-sink` module is used, then it suggests to me that the fault is associated with having two or more of them on the same system. The setup you describe would still have two `module-raop-sink` modules running, so it could still be suffering from some kind of interference between them; in that sense, it’s a similar situation to the first situation you describe.

**Comment by mikebrady** [comment]
Closing the issue. Please open a new one if necessary.
