### ISSUE TITLE
Mute not working when volume is turned all the way down.

### ISSUE THREAD

**Issue by charlesomer** [mikebrady/shairport-sync#643]
I have just installed Shairport Sync on my Raspberry Pi Zero W and it's working well. I had to delay the start of the service by a few seconds though because when the Pi rebooted, the USB audio card was not ready and so Shairport failed to start. Is this a common issue?

My main bug though is that when I turn the volume down fully on my iPhone, it does not mute the sound coming from the Raspberry Pi. I have set up Shairport so it is changing the hardware volume. When monitoring the sound via AlsaMixer it is shown as not reducing fully?

I may have missed a setting somewhere but I couldn't work out what it would be.

Any help would be greatly appreciated!

**Comment by mikebrady** [comment]
Thanks for the post. I haven’t tried that combination of a Pi Zero W with USB. As a matter of interest, how do you physically connect up to the USB card?

Anyway, the need for a delay is not uncommon — there have been other reports of a need for it, especially on lower-powered machines such as the Pi Zero or the original Pis. Maybe it should be added to the TROUBLESHOOTING page...

Regarding the muting, there is a setting in the `alsa` group called `mute_using_playback_switch`. Set it to `”yes”` (and remember to uncomment the line) and restart Shairport Sync. It might help.

**Comment by charlesomer** [comment]
Thanks for your help!

The USB sound card is connected by using a micro usb to full USB adapter. Is this what you mean?

Okay thanks you for clarifying that, it would probably be useful adding it somewhere. I also found that setting up the hardware volume settings to be slightly confusing but that might just be me (maybe an example of a usb sound card with hardware control?) Here's my setup...
```
output_device = "hw:1,0"; // the name of the alsa output device. Use "alsamixer" or "aplay" to find out the names of devices, mixers, etc.
mixer_control_name = "Speaker"; // the name of the mixer to use to adjust output volume. If not specified, volume in adjusted in software.
mixer_device = "hw:1"; // the mixer_device default is whatever the output_device is. Normally you wouldn't have to use this.
```

That has now partially fixed the muting issue by the looks of it, when monitoring the volume with AlsaMixer it still does not show the slider reducing completely to the "mute" position though? When adjusting the volume with AlsaMixer, I can move the slider lower than what Shairport seems to be taking it to.

**Comment by mikebrady** [comment]
Thanks for the clarification -- I'll get an adapter and try your configuration.

The reason Shairport Sync doesn't use the lowest volume control setting as advertised by `alsamixer` is that the DAC is advertising that the lowest setting is a mute rather than an actual volume. In other words, the usable part of the mixer's range starts just above it.

Unfortunately, the muting logic of Shairport Sync does not (yet) use that particular mute capability; instead it uses the playback switch mute, if available and opted for.

Slightly separately, my guess is that the range of attenuation offered by your USB DAC (i.e. the difference between the highest output level and the lowest level above mute) is only about 30 dB. (am I right?) Thus, if you set the volume of your stereo so that the maximum output is so loud as to be barely tolerable, then the minimum output will be too loud, or alternatively if you set the minimum output to be barely audible, the maximum output will not be loud enough. Again, there is a setting in Shairport Sync (`volume_range` in the `general` group) to allow you got add software attenuation to the hardware level to give you a wider total attenuation range, e.g. 70 dB.

**Comment by charlesomer** [comment]
I see what you mean now, by the sounds of it this is something that might be added in the future?

You're right about the attenuation range, the USB DAC only offers 36dB so after playing around with the `volume_range` setting I have been able to alter this nicely. My current setting is 45 which is working well. I presume this just works by placing more control of the volume to software rather than the hardware - judging by AlsaMixer again.

**Comment by mikebrady** [comment]
Dang -- I just added an entry. I'll have a look at yours though, thanks.

Yes, it would be nice to take advantage of that mute facility where it exists -- it's not as awkward to use as the playback switch, which can cause compatibility problems with other audio applications using the sound card.

**Comment by charlesomer** [comment]
I am unsure if it's the correct way to do it but using `ExecStartPre=/bin/sleep 5` as I noted in my pull request seems like a cleaner solution because it does not require any additional modification (i.e. disabling the service and using the timer)? I'm not sure if it does the same thing though.

Hopefully this is something that can be implemented in the future.

**Comment by mikebrady** [comment]
I'll certainly add it as a possible approach. I seem to remember somewhere thought that it is recommended not to put a delay in the service itself, but I could be wrong... Thanks again.

**Comment by charlesomer** [comment]
Yeah you're probably right, it's working for what I need at the moment though so I'll probably leave it for now.

Thanks for your help.

**Comment by mikebrady** [comment]
Is it okay to close this now?

**Comment by charlesomer** [comment]
Yes that's fine. Thank you.
