### ISSUE TITLE
Pops at start/stop when using basic interpolation

### ISSUE THREAD

**Issue by mklein9** [mikebrady/shairport-sync#683]
First of all, I love the software and am very happy I found it.  I have it running very well on a Raspberry Pi 3 B on Raspbian Stretch and using a HiFiBerry DAC+ Pro into a high-end amp and speakers. I am using the default alsa back end.

The one thing that I've considered an issue is loud pops when starting or stopping a stream.  It's annoying but I am concerned about the health of my ($$$$) speakers.  Some experimentation leads to the conclusion that the interpolation = "basic" setting causes this due, I suppose, to stuffing frames.  When I set interpolation = "soxr" the popping is gone.  On the RPi 3B soxr, along with S24 output format and 88200 output rate, does not show any higher than 20% CPU usage (averaged over 1 second, as shown by top), with an average around 13%, so I'll probably just keep it with these options, but I am considering adding a convolution filter in the future so CPU cycles may be at a premium.

Is this an issue that can be addressed at some point, or is it fundamentally incompatible with the lowest-cost interpolation scheme?

**Comment by mikebrady** [comment]
Thanks for the interesting post. I don't have the same DAC, but I do have a few Pimoroni DACs and I also have a couple of IQaudIO Pi-DigiAMP+. The Pimoroni PHAT DACs use a HifiBerry profile so they must be somewhat similar.

What I notice with the Pimoronis is that there is always a faint click when the DAC is opened for output by Shairport Sync. That would be at the start of a play session, around two seconds before the first audio actually is heard. Is that the time you notice the sound? I have tried really hard to figure out if that click can be avoided, but I haven't succeeded. It's volume-level independent too, which kinda makes sense because the Pimoronis don't have a mixer.

While it is definitely noticeable it is not, IMHO, dangerous, and is reduced when I use S32 (or S24) rather than S16. I don't believe that it is affected by using `soxr` or `basic`, however, so it might be a different phenomenon to what you're experiencing.

The DigiAMP+ is an integrated amplifier, so not directly comparable, but exhibits no such noise at all -- it is absolutely silent. (Now, I haven't done a forensic check on it, but in normal attentive listening at high volume in a quiet room , I haven't noticed any starting clicks or suchlike.)

I have not come across clicking when the music stops though, ever.

It would be very interesting to see if there was anything else going on. If you could enable the `statistics` option in Shairport Sync and post some of the resulting log, we might get an idea if there is anything untoward. The thing is, at the start of a stream, there should be no interpolation going on. I wonder if there are losses in your network or something of that nature; the `statistics` log would help there. Also, let us know what version of Shairport Sync you are using please. (Use: `$ shairport-sync -V` to find out.)

A possible alternative approach is to have a separate digitally-controlled volume control for the amplifier, allowing the output from the DAC into the preamp to be at full scale. Shairport Sync has a hook which should permit the driving of a digital volume control, though I have not personally tried it.

**Comment by mikebrady** [comment]
A slightly wacky thing to try is to use one of those $5 USB DACs and see if they suffer from the same problem (they all seem to use the same chips). Limited and all as they may be, in my experience they don't suffer from clicks.

**Comment by mikebrady** [comment]
Thanks Mike. This shows that there is no interpolation whatever happening, which is impressive and good, and no packet loss, also good. One quick thing to try is to compile Shairport Sync without convolution support and see if the issue persists. I really have no idea if it will, but it might just be worth a try.

Perhaps there are other users out there with direct experience of the DAC.

**Comment by mklein9** [comment]
I wonder if the recent discovery of 80 ms of noise on a track change might be an explanation for this problem as well?

**Comment by mikebrady** [comment]
Hmm, the 80ms noise is very noticeable when it happens; there's nothing subtle about it. BTW, there's a reference to a slight popping noise at the end of [this](https://learn.pimoroni.com/tutorial/sandyj/streaming-airplay-to-your-pi) article.

**Comment by mikebrady** [comment]
Hi there. We've been doing some related work that might make a difference, if you're still interested. Please see [here](
https://github.com/mikebrady/shairport-sync/blob/development/RELEASENOTES.md#version-33d39-to-version-33d38).

**Comment by mklein9** [comment]
I have been running for some time now with the default settings (possibly because recent installations overwrote the config file), with interpolation = basic and it has been fine.
With the latest development commit 87f3de2 it seems to be the same. I have not done any significant further testing. There is a highly muted pop, more like the sound of a puff of air, when shairport-sync first starts and, I think, very occasionally when starting to play. It is certainly not an issue to me.

**Comment by giggywithit** [comment]
Hello
In my system, I use the IQaudio driver with my own custom built DAC based on the PCM5242. I had to switch to the 5242 because it offers differential outputs, in contrast to the 5122 type that I had used prior. The issue with the single ended output DACs is that you will experience clicks and pops when the audio device is accessed. With the balanced output DAC 5242, these anomalies are eliminated, with the caveat, that you now must return the differential outputs back to single ended for your amplifier. I chose in my system to use Jensen audio transformers and the results are spectacular. She is quiet! I did originally have issues mostly because my amplifier is directly connected with no attenuation, clicks and pops often. Were good now. I would suspect that most issues are related to this.

I also have just recently been playing around with 'soxr' and would appreciate some input as to what the benefits are, if any, in using such. I am in and out of these forums and am lead to believe that theres no benefits to using anything more than S16 while having a hardware mixer either. Does soxr deliver better performance in any ways? Any advantages in increasing the bit depth?

Thanks for the great software
S

**Comment by mikebrady** [comment]
Thanks for the interesting post, and thanks for the interesting explanation of the cause of the popping and clicking noises. I must say, I envy your ability to construct a custom-built DAC -- that would be well beyond my meagre hardware abilities.

The `soxr` feature relates to how Shairport Sync does synchronisation. In order to keep time with the source's audio feed, Shairport Sync will insert or delete frames of audio to or from the output stream from time to time. If the interpolation mode is `"basic", to insert a frame, Shairport Sync will generate a frame based on the average of the frame before and the frame after. To remove a frame, it will simply delete a frame. This is crude but computationally inexpensive. On regular audio material, it's almost inaudible. By contrast, if `"soxr"` interpolation is chosen, a packet of a 352 frames is resampled to generate 353 or 351 frames as required, and is audibly much less noticeable. Unfortunately, it is computationally very expensive, and is beyond the power of many low-powered devices, including the Raspberry Pi, and due to the way it operates, advantage can not directly be taken of multiple cores.

Regarding bit depth, the obviously best situation of all is for the audio to pass through Shairport Sync unchanged. If you use a hardware mixer, then the volume is controlled by that and the audio passes through unchanged, except for the occasional interpolation.

Now, if any processing needs to be done to the audio as it passes through Shairport Sync, then dither will be added to the result. So, for example, if you use the software mixer (either by itself or to extend the range of a hardware mixer), or if you mix to mono, then dither will be added at the lowest level in the dynamic range of the output. If the output is 24-bit, that will be 256 times lower than if it's 16-bit, and if it's 32-bit then it will be 65,536 times lower. These differences are very noticeable indeed if you are driving a powerful amplifier. In summary, if you are using a hardware mixer only and not mixing to mono, 16-bit is as good as it gets. For everything else, 32- or 24-bit is invariably better.

Finally, Shairport Sync translates to 24 or 32 bit losslessly and will not add dither unless it is required, so there is no particular reason not to select 32- or 24-bit output if it's available -- it will never be worse than 16-bit operation.

Returning to the subject of pops and clicks -- and coming at this from a software perspective -- as a kind of a work-around for the same issue, the forthcoming version of Shairport Sync has a new ALSA-only setting that allows you to minimise the generation of pops and clicks by ensuring the DAC is busy all the time, and doesn't transition between outputting frames and not outputting them, which is where much of the popping and clicking seems to occur. If you set the new `disable_standby_mode` to `"always"`, then there might be one click or pop when Shairport Sync launches for the first time (typically when the machine is powering up), and then there should be no more transitions, and so no more pops and clicks. I've tried this with a Pimoroni PHAT DAC and it is very effective.

The Pimoroni PHAT DAC does not include a hardware mixer, and so relies on Shairport Sync's internal software attenuator, which as detailed above introduces dither. Setting Shairport Sync's output to 24- or 32-bit operation means that the dither is added in at 256 or 65,536 times lower a level, resulting in a very quiet quiescent state and this, when combined with the `disable_standby_mode` gives very good results when driving a power amplifier with no attenuation.

**Comment by giggywithit** [comment]
Hi Mike

Thanks again for the great software and active development environment.
Below is an image of my system. You will see the audio transformers attached to the HAT top and not in view are the DAC chip and associated parts below it on the other side of the PC board. This way, I was able to make all the parts fit onto one PC board in Raspberry Pi HAT size format. The transformers are shielded and need to be grounded to be effective. I chose the transformers over alternatives, first, for experimentation, then because they are passive. There is no need for any additional power supplies or power conversion that is a typical requirement of many balanced line receiver IC's. Additionally, the transformers provide a natural filter, filtering the inaudible frequencies naturally and adding a buffer between the digital environment and the analog. Through each of the revisions, I have refined and reduced the number of parts required in the project, to experience very good results. This unit, using your software, can be stashed out of sight and is autonomous, needing no manual intervention for power cycling. It powers up and down based on usage, and your software is reliable beyond other solutions that occasionally crash and hang. The next revision will be SMD for each and all of the parts that are available in that format, and more condensed than in this view. Additionally, the output transistors in the next revision will be double-die, and the power transformers will be larger, effectively increasing the output power to about 250-300wRMS per channel @4ohm. The design is such that these can more easily be assembled for the occasional batch if you would like one yourself. Needless to say, getting rid of the pops and clicks that were once experienced was of big importance. It's the difference between a DIY project and professional IMO. I would consider it professional at this point.

On the topic of 'soxr', as far as I am aware, I have it enabled in the configuration on my raspberry Pi, yet I am seeing a CPU utilization of under 10%. How can I confirm that I am using soxr? 

Thanks Mike

![ghost_d](https://user-images.githubusercontent.com/36465355/53740168-d4341680-3e50-11e9-98e3-5408cd92674d.jpg)

**Comment by giggywithit** [comment]
snippet..

pi@raspberrypi:~ $ shairport-sync -vv
Looking for configuration file at full path "/etc/shairport-sync.conf"
alsa output device name is "hw:0".
Lowest dB value is a mute
Hardware mixer has dB volume from -103.000000 to 0.000000.
The processor is running little-endian.
Version: "3.2.2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Ghost!".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
userSuppliedLatency is 0.
stuffing option is "1" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.

**Comment by giggywithit** [comment]
Just a thought on the popping etc...

You would be the coolest guy on the block if you could resolve the issue with using hardware muting of the DAC itself. Create a way to open the device while the DAC is hardware muted, then unmute immediately before starting the playback. Do the opposite on playback closing or changing of tracks, muting immediately, then doing the work. My DAC has the ability to be remotely muted as well.. I use this feature to keep the DAC muted while the power of the amp is being initiated to keep from attempting to playback while the amp is settling. In the documentation, the analog portion of the DAC is apparently shutdown and any output signal is disabled.

Huge bragging rights coming your way
S

**Comment by giggywithit** [comment]
"Unfortunately, it is computationally very expensive, and is beyond the power of many low-powered devices, including the Raspberry Pi"

Hopefully you can clarify this, as many here, including myself have 'soxr' enabled (or think we do) on our raspberry pi machines. 

Scott

**Comment by mikebrady** [comment]
Thanks for the post, Scott. Maybe I overstated the problem a little. If the amount of interpolation is moderately low, say under about 70 ppm, then the Pi can cope with using `soxr`, but if the amount of interpolation is continuously high, then it will bog down the Pi. I run with it enabled on a Pi Zero W, but the interpolation averages around 60 ppm. I’ve edited the comment to be a little less categoric.
