### ISSUE TITLE
Distorted audio when using Mono playback

### ISSUE THREAD

**Issue by jakob** [mikebrady/shairport-sync#700]
**How to reproduce**:
1. Install shairport sync on a Chip `sudo apt-get install shairport-sync`
2. edit `/etc/shairport-sync.conf` and set `playback_mode = "mono"`
3. restart shairport-sync with `sudo systemctl restart shairport-sync`
4. play this audio file [quelquun.mp3.zip](https://github.com/mikebrady/shairport-sync/files/2015983/quelquun.mp3.zip)

**What happens?**
The vocals are extremely distorted (should be immediately obvious). When reverting to "stereo", everything works as normal.

**Version**
`shairport-sync --version` outputs the following:
`2.8.4-OpenSSL-Avahi-ALSA-pulse-dummy-stdout-pipe-soxr-metadata`

**Comment by mikebrady** [comment]
Thanks for the report. It would be very helpful if you could update to the latest version of Shairport Sync -- 3.2. Some time ago, possibly after 2.8.4 (which is pretty ancient now, BTW) a bug affecting the way mono was generated was fixed. The effect of the bug was to combine the left and right signals, potentially doubling the amplitude and thereby introducing the possibility of clipping. This might be the cause of the distortion you hear. Since you just installed a binary version of Shairport Sync from the repository, you'd have to do a full installation as described in the [README.md](https://github.com/mikebrady/shairport-sync/blob/master/README.md). BTW, I have a C.H.I.P. myself and I can tell you it's straightforwards, if a little tedious.

Another question is what settings are you using? I guess it's the (default) `alsa` backend. Also, it would be good to know whether you using the hardware volume control or not; if you could list the changes you have made to the settings file, that would  be very helpful.
