### ISSUE TITLE
Arch Linux ARM - Community Repo 2.2.3-1

### ISSUE THREAD

**Issue by joaodriessen** [mikebrady/shairport-sync#75]
Hi Mike,

I found shairport-sync version 2.2.3-1 in the community repo of Arch Linux ARM yesterday (trusted users, not aur).
installed the package but there is a problem with it.
running shairport-sync as a daemon (-d) outputs this message
```
Daemon returned 2 as return value.
```
Starting shairport-sync via it's systemd unit doesn't start shairport-sync. possibly because It starts it as a daemon?
```
[joao@alarmpi ~]$ which shairport-sync 
/usr/bin/shairport-sync
```
I don't know if It's better contacting the maintainer about this issue, will do if you don't think it's a bug in shairport-sync.

**Comment by joaodriessen** [comment]
actually, journalctl from last boot with shairport-sync.service enabled gives this 
```
[joao@alarmpi ~]$ sudo journalctl -b /usr/bin/shairport-sync 
[sudo] password for joao: 
-- Logs begin at Thu 1970-01-01 01:00:06 CET, end at Fri 2015-05-01 11:26:12 CES
May 01 11:08:10 alarmpi shairport-sync[200]: startup
```
but no airplay share available from any of my devices.

**Comment by mikebrady** [comment]
First, just a little thing – if you execute `shairport sync -d` and are not privileged, you may run into trouble because the application won't have permission to write its PID file, giving you the error 2. Try `sudo shairport-sync -d` instead.

I've begin running Arch Linux on a Raspberry Pi 2 and using Elia Cereda's installation package – see https://github.com/EliaCereda/shairport-sync-PKGBUILD. I have been really impressed with the stability of Arch Linux over Raspbian, and it seems to support very reliable WiFi and IPv6 better "out of the box".

Anyway, I've made so many changes that I can't be absolutely certain that the regular package installs flawlessly – AFAIR it does, but I'd prefer to check first.

What platform are you running? if `sudo shairport-sync -d` works (see above) then is it possible that shairport-sync is being started before the sound or network or avahi subsystems are ready? Just a thought.

Let me have a look at this – unfortunately, it'll take a few days – it's a long holiday weekend here...

**Comment by joaodriessen** [comment]
I've found the service does indeed start. something seems to be up with shairport-sync's visibility or stability from other devices on my network. I don't always see the service from my phone/iPad or macbook, sometimes a disconnect and a reconnect to the network will solve it. other times a reboot of my host device and client devices is also necessary. It's difficult for me to judge where the issue(s) lie. ie. shairport, avahi, my macbook, my router etc. etc.

by the way, configuring the settings like so:
```
# ShairportSync Daemon options
SHAIRPORT_ARGS="-a "alarmpi" -- -d hw:0 -t hardware -c PCM"
```
causes "alarmpi -- -d -- -d hw:0 -t hardware -c PCM" to appear as the name of shairport-sync on my other devices. do you happen to know what would be the proper syntax of SHAIRPORT_ARGS= to avoid the confusion regarding the inverted commas?

**Comment by mikebrady** [comment]
Should be able to check this later on today...

**Comment by joaodriessen** [comment]
My initial report of shairport-sync not starting was in error.
there does seem to be a problem regarding proper syntax of the /etc/conf.d/shairport-sync file.
But that's most likely due to my ignorance in not knowing how to edit the file properly, here's it's contents for reference:
```
# ShairportSync Daemon options
SHAIRPORT_ARGS="-a "alarmpi" -- -d hw:0 -t hardware -c PCM"
```

The connection issues ie. my devices (iPad, iPhone, Macbook) i not seeing the service, or disconnecting randomly are still of precedence. However, I haven't figured out a way to test this accurately/scientifically to narrow down the problem.
FYI Shairport-sync is not the only service affected. I'm unable to ssh into my raspberry pi via it's mdns .local name after the dropout occurs. - Could be a router issue, could be an avahi-daemon issue, could be a problem with my macbook running OS X 10.10.3... etc.

**Comment by mikebrady** [comment]
If you remove the extra quotes it should work – I can't test it right now, but this might work:

```
# ShairportSync Daemon options
SHAIRPORT_ARGS="-a alarmpi -- -d hw:0 -t hardware -c PCM"
```

**Comment by joaodriessen** [comment]
Thank you that did the trick.

Follow up on my connection issues:

none of my apple devices were discovering the shairport-sync service.
I left the airplay device selection menu open on iPhone and subsequently rebooted my macbook, after the reboot of my macbook, the shairport-sync service appeared on my iPhone and all other devices.
I assume a device leaving/joining the network causes a rebroadcast of all avahi services(?)
Not presuming to ask for technical support here, just posting info that may be useful to you.

**Comment by mikebrady** [comment]
Yeah, I think you're right. There have been visibility issues for quite a while, not just associated with Shairport Sync, but with AirPlay in general – see https://github.com/mikebrady/shairport-sync/issues/15. They seem to be gradually improving though.

**Comment by mikebrady** [comment]
Hi. I just checked with Elia Cereda's script and everything worked. It is a Raspberry Pi 2 with a "WiPi" WiFi adapter.
```
[mike@alarmpi ~]$ uname -a
Linux alarmpi 3.18.11-4-ARCH #1 SMP PREEMPT Tue Apr 21 21:52:58 MDT 2015 armv7l GNU/Linux
[mike@alarmpi ~]$ git clone https://github.com/EliaCereda/shairport-sync-PKGBUILD.git
[mike@alarmpi ~]$ cd shairport-sync-PKGBUILD/
[mike@alarmpi ~]$ makepkg -sfi
```
I had to put in a `sudo` password and agree to the final installation.

**Comment by joaodriessen** [comment]
Maybe: http://arstechnica.com/apple/2015/05/new-os-x-beta-dumps-discoveryd-restores-mdnsresponder-to-fix-dns-bugs/

**Comment by mikebrady** [comment]
Yes indeed, it's intriguing!

**Comment by joaodriessen** [comment]
updated to 10.10.4 beta 4 (14E26a). It's bonjour/mDNSresponder seems more stable. my airplay devices are showing up more regularly now and I'm issuing "sudo systemctl restart avahi-daemon.service" on my linux system much less frequently.
(still problems with random disconnects and loosing visibility of bonjour/avahi devices on the network)

**Comment by mikebrady** [comment]
Yeah, that's been my experience too. Connection to AirPlay devices from iTunes is instant again. I understand that the defective `discoveryd` code is still in iOS, so it may take some time for the fix to be in for all devices.

I have never had to restart avahi on any of the systems on my network, however, and arch linux on a Raspberry Pi 2, connected over WiFi, is the most solid of all.

Separately, my WiFi network is based on a Linksys WRT1900AC which has 5GHz and regular 2.4GHz networks running simultaneously. Until the latest firmware update, connectivity between the 5GHz and 2.4GHz bands was unreliable, particularly with regard to mDNS. The problem was exacerbated because even after connectivity to an mDNS device was lost, another mDNS device on the network would (correctly) supply cached information about the disconnected device, so the disconnected device would still appear to be visible even though it was gone. The latest firmware seems to have fixed the problem, but it was so bad that I disabled the 5GHz part.

**Comment by joaodriessen** [comment]
ugh glad to hear your router is handling mDNS properly now. makes me wonder how much trouble a badly written firmware for a router can cause, and if many other (potential) shairport-sync users are effected by bad routers.

restarting avahi-daemon.service just seems the most practical thing to do in my case since it remedies almost all the issues I have. not very elegant, but does the trick.
Considering setting up a script to do it with the -E option.

**Comment by mikebrady** [comment]
I think we concluded this issue, so I'm going to close it. Feel free to reopen..
