### ISSUE TITLE
limitation of latency time range [being resolved]

### ISSUE THREAD

**Issue by YIN-Renlong** [mikebrady/shairport-sync#756]
Hi Mike, I would like to let you know that, since I have discovered  the latency between input & output at a Raspberry Pi 3 based on DietPi, I have setted `audio_backend_latency_offset_in_seconds` in `-1.5`, unfortunately it indicates `fatal error: Invalid audio_backend_latency_offset_in_seconds "-1.500000". It should be between -1.0 and +1.5, default is 0 seconds` when I try to restart it. 

I have searched on Google but got no case regards to this issue, would it be possible to resolve this problem? Would it able to set as `-1.55s`? Thank you so much, both for the great patient and the great realized project.  
```
root@DietPi:~# shairport-sync -v
alsa output device name is "default".
Version: "3.1.7-mbedTLS-Avahi-ALSA-stdout-pipe-soxr-convolution-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file is "/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "DietPi".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is -1.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 3.
use_apple_decoder is 0.
alsa_use_playback_switch_for_mute is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
convolution is 0.
convolution IR file is "(null)"
convolution max length 8192
convolution gain is 0.000000
loudness is 0.
loudness reference level is -20.000000
Successful Startup
Unable to listen on IPv4 port 5000. The error is: "Address already in use".
Unable to listen on IPv6 port 5000. The error is: "Address already in use".
fatal error: Could not establish a service on port 5000 -- program terminating. Is another instance of Shairport Sync running on this device?
Request to shut down all rtsp conversation threads
asking playing threads to stop

```

**Comment by mikebrady** [comment]
Thanks for the post. I will change the limit, but there is a hard limit which depends on the total latency. The `audio_backend_latency_offset_in_seconds` is added to the negotiated latency, which is normally about 2 seconds, to give the overall latency of the system. Out of that must come the `audio_backend_buffer_desired_length_in_seconds` allocated to the DAC itself, which is normally 0.15 seconds.

Thus, with a `-1.55` second backend latency offset and a `0.15` second buffer length, the overall amount of software buffering is `2.0 - 1.55 - 0.15` or `0.3` seconds. This is all the time that Shairport Sync can use for missing packet detection and synchronisation. If your network is very good and if the CPU is lightly loaded, this might work.

I will change the limit in the `development` branch and let you know when the update is posted.

**Comment by mikebrady** [comment]
Hi there. As promised above, I have updated the `development` branch to allow a `audio_backend_latency_offset_in_seconds` setting of up to ± 1.75 seconds. Note that absolutely no checking is done -- you may well crash the application.

Instructions for updating, including updating to the `development` branch, are at [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md).

**Comment by YIN-Renlong** [comment]
> Hi there. As promised above, I have updated the `development` branch to allow a `audio_backend_latency_offset_in_seconds` setting of up to ± 1.75 seconds. Note that absolutely no checking is done -- you may well crash the application.
> 
> Instructions for updating, including updating to the `development` branch, are at [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md).

By the way, would it be possible to create a demonstrate configuration at `/etc/shairport-sync.conf`, so as to have a best audiophile quality of Airplay output? (more than the parameter of `output_rate` and `output_format`. )

**Comment by mikebrady** [comment]
Thanks for the suggestion. It really depends on the DAC and amplifier, but my best experiences would be:

1. Use `soxr` interpolation if possible.

2. If your amplifier has a computer-controlled volume control, then send audio straight though Shairport Sync, with `ignore_volume_control` set to `"yes"`. Attach a program to control the amplifier to the `run_this_when_volume_is_set` command. 

3. Otherwise, if the DAC has a mixer, use it for volume control.

4. Otherwise, if the DAC has no mixer, then if it accepts 24- or 32-bit samples, select them using the `output_format`, as the dithering noise floor will be 48 or 96 dB lower.

To be honest, I don't think there is much to be gained in changing the output rate, except where a DAC will not accept 44,100 frames per second but only a multiple of it.

Also, try to use a computer for Shairport Stnc that has an accurate clock. For instance, most Raspberry Pi's have pretty accurate clocks, but many older machines – especially old laptops and many routers – have clocks that are way off. They cause lots of interpolation (aka "stuffing"), and that is never good. There is a little discussion of this [here](https://github.com/mikebrady/shairport-sync#some-statistics) in the [README.md](https://github.com/mikebrady/shairport-sync#some-statistics).
