### ISSUE TITLE
Buffer underrun in alsa

### ISSUE THREAD

**Issue by jebeaudet** [mikebrady/shairport-sync#76]
Hi!

I bought some wireless speakers (http://www.veho-world.com/main/shop_detail.aspx?article=212) and I'm trying to make them work with shairport-sync on a raspberry pi. The speakers come with a USB soundcard that streams the music. 

I'm currently running the pi on the volumio distribution. I've manually installed shairport-sync on it. I use ALSA with a software mixer because the bass is way too high with the default settings (no hardware mixer). 

I'm getting buffer underruns in ALSA when streaming from shairport-sync. Music play fine when playing from mpc of a local mp3. I've ran shairport-sync with the `-vvv` option, anything I could try to fix this?

Thanks!

Here is the log file (I've stripped irrelevant content)
```
usr/local/bin/shairport-sync -vvv -a AirPi-sync -- -d equal &> logs
statistics_requester status is 0.
daemon status is 0.
rtsp listening port is 5000.
Shairport Sync player name is "AirPi-sync".
Audio Output name is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
mdns backend "(null)".
latency is 0.
AirPlayLatency is 88200.
iTunesLatency is 99400.
forkedDaapdLatency is 99400.
stuffing option is "(null)".
resync time is 2205.
busy timeout time is 120.
tolerance is 88 frames.
password is "(null)".
startup
avahi: avahi_register.
avahi: register_service.
Avahi without metadata
culling threads.
new RTSP connection.
    CSeq: 1.
    User-Agent: iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4.
    Client-Instance: 0B385C0F22FE1393.
    Content-Type: application/sdp.
    Apple-Challenge: XQ9Gc+5T6qVTlmPlPcDwiw.
    Content-Length: 572.
Play connection from "iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4".
    Apple-Response: AlyAP+vi64y/gLFb80BGZVIfL/i+/lXaq6AW3N+ufCtHsagoQi96mTCI9rW1lFrkCXCpiHVU/RMEam8X4anaj1uMg/bS7hQ8DgbcmXlb/xHoAzWbL7jRsST58W+Fzh0v+EpWiIbH0w5Bcf83NMI9/WTuoP+Psfj2ckWIb04yzd67sHP+Y6vc5QqkAInAwWxD1yyV5lvVOH6RLQdPbvuXCvpDKnYwmbiaEltJ0EIbDf6P7FOcbsuIY5HLqNuXF40bd6DvX+idyCDLNmLctK9yTbLqJO5vRf5Y/3JFRodzMyIRRC0A201UWCKSW5bfSd+uCMDtKo/XLt6h+N7h6X9Ltg.
    CSeq: 1.
    Audio-Jack-Status: connected; type=analog.
    Client-Instance: 0B385C0F22FE1393.
    CSeq: 2.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002.
    User-Agent: iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4.
User-Agent is iTunes 10 or better, (actual version is 11); selecting the iTunes latency of 99400 frames.
rtp_setup: cport=6001 tport=6002.
Connection from IPv4: 192.168.0.245:38359
listening for audio, control and timing on ports 58990, 51883, 38549.
    CSeq: 2.
    Audio-Jack-Status: connected; type=analog.
    Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=51883;timing_port=38549;server_port=58990.
    Session: 1.
    CSeq: 3.
    Range: npt=0-.
    User-Agent: iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4.
    Client-Instance: 0B385C0F22FE1393.
    RTP-Info: seq=1137;rtptime=315812.
    Session: 1.
    CSeq: 3.
    Audio-Jack-Status: connected; type=analog.
    Audio-Latency: 88200.
    CSeq: 4.
    User-Agent: iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4.
    Client-Instance: 0B385C0F22FE1393.
    Content-Type: text/parameters.
    Content-Length: 20.
    Session: 1.
SET_PARAMETER Content-Type:"text/parameters".
received parameters in SET_PARAMETER request.
volume: -15.000000

    CSeq: 4.
    Audio-Jack-Status: connected; type=analog.
syncing to seqno 1137.
---------
---------
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 22853.
syncing to seqno 1468.
+++++++++
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Error -32 writing 353 samples in play() Broken pipe.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 67371.
syncing to seqno 1944.
---------
---------
RTP: Packets out of sequence: expected: 2583, got 2584.
requesting resend on 1 packets starting at 2583.
---------
---------
    CSeq: 5.
    User-Agent: iTunes/11.3.1 (Macintosh; OS X 10.9.4) AppleWebKit/537.77.4.
    Client-Instance: 0B385C0F22FE1393.
    Content-Type: text/parameters.
    Content-Length: 20.
    Session: 1.
SET_PARAMETER Content-Type:"text/parameters".
received parameters in SET_PARAMETER request.
volume: -13.500000
---------
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Error -32 writing 351 samples in play() Broken pipe.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 47804.
syncing to seqno 11314.
+++++++++
---------
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
Error -32 writing 351 samples in play() Broken pipe.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 22636.
syncing to seqno 13752.
---------
```

**Comment by mikebrady** [comment]
Thanks for your report. I'm just wondering if the Pi is busy doing something else – for instance, do you have some kind of equaliser running. The reason I ask is that (a) a busy Pi might explain the symptoms and (b) you mention using a software mixer. Could you say a little more about the mixer. You say you are using a software mixer because the default has too much bass. I don't understand this. Are you routing the audio through some kind of equaliser on the Raspberry Pi? (BTW, `-vv` gives almost as much info as `vvv`.)

**Comment by jebeaudet** [comment]
Yes I'm running an equalizer plug-in, sorry I've mixed terms, I'm still not completely familiar with all the audio stuff in Linux. I'm running this plug-in :http://www.thedigitalmachine.net/alsaequal.html
On the first line on the previously attached log, you can see the command I use to run shairport-sync. 
Here is my asound.c of in case it'd help:
```
ctl.equal {
 type equal;                                                                 
}                                                                            pcm.plugequal {                                                                type equal;                                                                  slave.pcm "plug:dmix";                                                     }                                                                            pcm.equal {                                                                    type plug;                                                                   slave.pcm plugequal;                                                       }  
```

Nothing else is running on the pi. I've tried a couple of distros and they all exhibit the same problem. You think it might be the equalizer? Thanks

**Comment by mikebrady** [comment]
Thanks for the information. It's interesting to find out about the equaliser – I hadn't heard about it. So, yeah, I guess the computational demand of the mixer may be the problem.

You can check this in a couple of ways:
* If you direct the output of shairport sync directly to the [real] output device, does the problem disappear?
* If you run the `top` command, does it show a very high CPU utilisation rate?

Of course, it is possible that the computational demand of the equaliser is not too great on average, merely too intermittent, so that sometimes it starves shairport sync of processing time needed to keep the output buffer full. To check this out will take a little effort: you should install the development version of shairport sync in place of the standard one. To do this, go back to the shairport-sync site on github and switch branches to the development branch where you'll see instructions. The thing is, the development branch allows you to lengthen the buffer queue, and I'd suggest you change it to half a second – 22050 frames, so see if the larger buffer allows the whole system to work. IMHO it's worth a try.

**Comment by mikebrady** [comment]
Oops, didn't mean to close the issue – sorry.

**Comment by jebeaudet** [comment]
Cool thanks for the tips, I'll try them once I get back home and I'll post back tomorrow morning.

**Comment by jebeaudet** [comment]
Nothing stands out with the `top` command, no process hoggering the cpu.

Tried with the audio out of the pi and didn't get the same exception however I get some of these (even with the buffer increased to 22050): 
```
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: -8389.
syncing to seqno 22765.
Lost sync with source for 4 consecutive packets -- flushing and resyncing. Error: 8430.
syncing to seqno 22903.
RTP: Packets out of sequence: expected: 22975, got 23016.
requesting resend on 41 packets starting at 22975.
```
Same errors with the USB audio card however I don't get the underrun I was getting so I guess it's progress!

I don't have these problems when running in windows with Shairport4w on my desktop (obviously much more powerful). Everything is on a 1Gbps network wired (except the airplay player of course).

Anything else I could try? I don't mind the audio being delayed as long as it's working.

Thanks again

**Comment by mikebrady** [comment]
Thanks for the updates.

I hope I am correct in understanding that you are routing the output from shairport-sync to the Pi's audio output, that is, to the headphone jack, and you're getting the errors noted above, and that the Pi is connected over an ethernet link to the rest of your system. If so, then your system is very "normal" and should work, so this is a real puzzle!

It does remind me of a problem I had with a Pi connected over wired ethernet in my kitchen. Occasionally – maybe every 15 or 20 minutes or so – it would lose sync and resynchronise. Eventually I replaced it with a real Airport Express. This did not lose sync, but every 15 or 20 minutes or so it would generate an unbearably loud click. My conclusion was that the ethernet cable was picking up electrical interference from a nearby refrigerator motor and was causing the noise on the Airport Express and was causing the Pi to lose sync. Changing the settings of the Airport Express so that it connected to the network wirelessly and disconnecting the ethernet cable fixed the clicking problem. Also, moving to WiFi for the Raspberry Pi stopped the resyncing. 

So, it's a very long shot, but is there the the possibility of electrical interference in your setup?

BTW, getting WiFi to work very reliably on a Pi is a very tricky problem. It is often the case that a Pi will maintain a link for a week or so and then just drop it. Even so, it might help isolate the problem.

**Comment by jebeaudet** [comment]
I tried routing the audio to the headphone jack and I got these errors. I then tried to route the output to the usb sound card and I got the same errors. This is always with the equalizer plugin.

Interference shouldn't be an issue I believe, the pi is alone in it's corner and I just tried with a brand new ethernet cable... 

I've raised the buffer to 32050 and I still get some sync lost problems but they seem less frequent.

I'll close this for now, I'll experience some more but maybe I'll fallback on my windows htpc. Feel free to reopen if you have any ideas and I'll do the same if I find the golden solution.

Thanks again for your time and good job with all of this!

**Comment by mikebrady** [comment]
Will do, thanks.
