### ISSUE TITLE
Can't apply Airplay password with RPi Zero W [Can't replicate]

### ISSUE THREAD

**Issue by tinyreminder** [mikebrady/shairport-sync#760]
Hello,

I tried to set AirPlay password for RPi Zero W
but RPi denied AirPlay connection with password.
Without password, RPi zero and shairport-sync worked well.
Also RPi 3 worked with password.

Kind retards,
Takeshi

**Comment by mikebrady** [comment]
Thanks for the report. Let me check it out and get back to you.

**Comment by mikebrady** [comment]
A quick question: did you build each installation with the same `./configure` options?

**Comment by tinyreminder** [comment]
I installed with apt-get command.

**Comment by mikebrady** [comment]
Many thanks. Could you enter the command:
```
$ shairport-sync -V
```
and post the results please? (Note that the V is uppercase!)

**Comment by tinyreminder** [comment]
The result is:

$ shairport-sync -V
2.8.6-OpenSSL-Avahi-ALSA-pulse-dummy-stdout-pipe-soxr-metadata-sysconfdir:/etc

**Comment by mikebrady** [comment]
Thanks. I'll check it out over the next few days.

**Comment by mikebrady** [comment]
Hi there. I have tried out 2.8.6 and also the latest version -- 3.2.2 -- and the password works alright. So, I can't replicate your problem.

I know that sometimes the player, e.g. iTunes, sometimes gets confused when a device changes from needing no password to requiring one -- maybe that's the problem you have run into.

(BTW, I am assuming passwords are encoded in UTF-8.)

**Comment by tinyreminder** [comment]
I see.

I will try to create new environment.

Thank you very much for your kind support,
Takeshi

**Comment by mikebrady** [comment]
Takeshi, there is something odd going on all right. Please let me experiment a bit more -- some kind of intermittent fault.

**Comment by mikebrady** [comment]
So, I had another look at this. There is a minor problem, fixed in the latest `development` branch, with the generation of a cryptographic "nonce", but it's effect would only be to make the exchange of authentication tokens slightly less secure. 

Coming back to your problem, iTunes gets confused if the password status of a device changes while it is selected. The next time you try to connect to it, error -15001 comes in. Similarly, iOS get confused in the same situation.
