### ISSUE TITLE
Manipulate audio stream with defined key codes. (MediaKeys) || request

### ISSUE THREAD

**Issue by Rastafabisch** [mikebrady/shairport-sync#776]
What about implementing a functionality to skip, rewind and pause the playing audio-stream. This should be possible, as it can be done when streaming to an AppleTV.

On a computer (keyboard) the media keys could be mapped accordingly. On a raspberry pi or similar this might be possible using the GPIO interface.

**Comment by mikebrady** [comment]
Thanks for the suggestion. Shairport Sync offers a D-Bus interface which you can send commands to -- maybe that would satisfy your needs? Also there's an MQTT interface in development.

**Comment by mikebrady** [comment]
BTW, see #223 for a usage of D-Bus...

**Comment by Rastafabisch** [comment]
great to see, that there already is support. however I could not get it to work on macOS even when I modified the home-brew formula to include dbus and dbus-glib, although it compiled fine.

**Comment by mikebrady** [comment]
Hmm, I suspect, but don't know, that the security settings for providing a system-wide D-Bus service on macOS might be different to Linux or FreeBSD. It might be worth trying as a "session" service rather than a "system" service -- the security requirements are much less. But I haven't looked at this on macOS.
