### ISSUE TITLE
Some dbus commands don't work

### ISSUE THREAD

**Issue by Giannie** [mikebrady/shairport-sync#777]
I don't seem to be able to access some dbus commands. Actions such as Play/Pause and VolumeUp/VolumeDown all work, but SetVolume and and Volume don't seem to function.

**Comment by mikebrady** [comment]
Thanks for the post. It depends on the audio player. If it's iTunes, the  advanced remote control group of properties and commands will work. If it's an iOS source, they are not available. The advanced remote control set includes an "Available" property.

**Comment by Giannie** [comment]
I see! Thanks for the quick response. Is this a limitation of iOS devices that means there is no way to set the volume if an iOS device is the source?

If so, is there any way to read the volume over dbus from an iOS source?

**Comment by mikebrady** [comment]
As best I understand it, it's a limitation of the iOS protocols. I haven't been able to get any more information or responses to any more commands beyond the basic set implemented in the D-Bus interface of Shairport Sync. If anyone has more information, I'd be glad to hear about it.

**Comment by mikebrady** [comment]
@gianni, @corrpel, it turns out that there _is_ a command to set the output level of an iOS device! The command is `"setproperty?dmcp.device-volume=<volume>"` where `<volume>` is the AirPlay volume, between -30.0 and 0.0.

Once you have started a session, you can try it with a `raw` D-Bus command to Shairport Sync, e.g:
```
dbus-send --system --print-reply --type=method_call --dest=org.gnome.ShairportSync '/org/gnome/ShairportSync' org.gnome.ShairportSync.CommandAndResponse string:"setproperty?dmcp.device-volume=-10.000000"
```

I will package it up properly and add a command to the native D-Bus interface...
