### ISSUE TITLE
Multiple instances (again)

### ISSUE THREAD

**Issue by dmikhalsky** [mikebrady/shairport-sync#794]
Has anything changed since issue #37 and the workaround described there?

**Comment by mikebrady** [comment]
No change AFAIK. Is there a problem?

**Comment by oscar-c** [comment]
I'd like to suggest some improvements to make launching and managing multiple instances easier:
1. Have `shairport-sync`'s configuration support "drop-in" folders, so that if you have two files: 
- `/path/to/shairport.conf` and
- `/path/to/shairport.conf.d/override.conf`, 
and `shairport-sync` is set to use the first config file, the config in `override.conf` (and any other `/path/to/shairport.conf.d/*.conf`) overiedes the config in the first one.

2. Have `shairport-sync`'s configuration support a inclue/import clause.
