### ISSUE TITLE
using libsoxr for time stretching changes pitch

### ISSUE THREAD

**Issue by christf** [mikebrady/shairport-sync#797]
when using soxr, the pitch changes when time stretching. libsoxr does not seem to support time stretching, just resampling adjusting pitch.

**Comment by christf** [comment]
shairport-sync uses soxr to help sync the audio playback by stretching the audio data, adding a frame or removing one. When this happens, the pitch of the audio changes.

soxr is meant to resample audio data while maintaining pitch. The use case is: you have pcm data with 44100 samples per second but playback will happen at 48000 samples per second. soxr will then re-calculate each sample while maintaining pitch.

The shairport use-case is this:
There is audio data with a specific sample rate, say 48000 / s. The playback sample rate expects this very sample rate. However to match the time at which a sample is played, it may be required to make it a little longer or shorter. soxr is used to resample chunks of audio from 48000 to say 48005, which it happily does. Since playback rate does not change, this leads to a audible change in pitch. It seems, it is not the appropriate library for the task. Even just dropping or duplicating a single frame is less audible than what is happening when using soxr.

I have been looking at librubberband for a similar use case (snapcastc) and it seems more suited.
I suggest to replace soxr with librubberband for increased perceived audio quality.

**Comment by mikebrady** [comment]
Thanks for the clarification.

My reasoning about this is different, and I wonder what you think of it. Here it is:

Let's say we are getting PCM data at exactly 44,100 samples per second but the DAC is playing them at 44,099 samples per second. Shairport Sync uses feedback to monitor the difference in rates and will occasionally (in this example) take a sequence of n frames and resample them to output n-1 frames. It would have to do this once per second in this example, a rate of around 20 ppm. Thus, as I see it, on average, `soxr` is indeed being used to transcode between 44,100 and 44,099 frames per second, and it works to actually maintain correct pitch, assuming the source clock is right, of course.

I've been doing some testing of source clock rates using on NTP-corrected clocks, and it seems that iOS devices play audio at very close to the correct rate, as do YouTube via Safari on Macs. However, and remarkably, iTunes on the Mac is usually a few fps off.

Most recent Raspberry Pis output at rates that are very close to nominal. Many older laptops, desktops and most embedded devices such as WiFi access points, etc. have wildly inaccurate clock rates. I'm not quite certain of my conclusions, but such as they are, I can't explain them any other way.

Finally, FYI, the `basic` interpolation used by Shairport Sync does what you suggest -- insert or delete a frame from time to time. In normal audio material, it's almost imperceptible, but the `soxr`-based interpolation is far superior.

**Comment by christf** [comment]
yes. I have looked at both implementations. In any case, I can hear that the pitch is changing when soxr is active. If you scale the audio (sacrificing synchronzation for this test only) by a factor of 1.3 or 1.4, the problem is revealed more easily because the change in pitch is more obvious.

**Comment by mikebrady** [comment]
Fair enough, but the normal corrections are in the range of 10s to 100 ppm, and I, for one, have never been able to hear pitch changes at those levels.

**Comment by mikebrady** [comment]
Thanks, yeah, that would be interesting.

**Comment by nettings** [comment]
I'm very new to shairport-sync, so I haven't listened that intensely. But from building another quite extensive audio infrastructure with adaptive resampling using zita-njbridge, I can say that the slight wobble in pitch (on the order of 1/100 of a cent or so) is not audible at all, and that adaptive resampling is indeed the correct technique to use. An audible pitch wobble only happens as the resampling ratio is adjusted. After a cold start, it would be very audible (which is why good implementations will take a few seconds to make sure it's stabilized), but after that, the correction is inaudible. I can't vouch for libsoxr, but in principle, it's the right way to go. Here's some measurements on the remaining jitter: https://kokkinizita.linuxaudio.org/linuxaudio/zita-ajbridge-doc/quickguide.html
On the other hand, time-stretching is horrible, horrible guesswork, and the artefacts you are getting for something that "looks correct on paper" are atrocious.

**Comment by mikebrady** [comment]
Thanks for your contribution, and that's an interesting paper that you link references!

**Comment by nettings** [comment]
Hi @mikebrady and @christf, I'm just starting on a week of intense listening tests to see how well shairport-sync is doing. But since it's not the only adaptive resampler in my chain, I thought I'd revisit zita-njbridge again. Here is some data about sample rate fluctuation:

23   -0.272  0.999967      384   0
 24   -0.493  0.999968      386   0
 23   -0.438  0.999969      402   0
 23   -0.397  0.999970      389   0
 24   -0.376  0.999970      392   0
 23   -0.319  0.999969      372   0
 24   -0.251  0.999969      388   0
 23   -0.238  0.999968      375   0
 24   -0.258  0.999968      377   0
 23   -0.159  0.999968      393   0
 24   -0.082  0.999967      380   0

These lines pop up about 3 a second. The interesting column is the middle one, sample rate ratio.
On a wordclock-synced system with identical sample rates, it would be const 1, on a synced system with different sample rates, some other constant.
Here it tries to guess at the sending side's sample clock by running a PLL over the network audio packets as they come in, i.e. a massively high-jitter "clock" source. You can see a worst-case fluctuation of maybe 0.00005 from moment to moment, superimposed with a slower oscillation at higher amplitude. Let's consider the short-term fluctuation: it resolves to a flutter of 0.01 cent, which is on the far side of just noticeable difference by two orders of magnitude, according to the nice table at the bottom of http://www.sengpielaudio.com/calculator-centsratio.htm
The longer-term oscillation is about ten times worse, but I guess it's still neglible. 
I haven't quite wrapped my head around how to map these values to standardized wow and flutter measurement techniques (might involve lots of derivatives and other scary shit), but with such small errors, it's an academic exercise anyway.
Now Fons' zita-njbridge is pretty much a textbook implementation. The question is if soxr is as good, reaching the 10-100ppm that mikebrady reports.
If it is, then what you're hearing is something else. My guess would be some obvious bug somewhere rather than a fundamental flaw in the design. But so far, I haven't been able to find any major issues.
Piano sounds do get a little more "gritty", but nothing dramatic. Definitely no pitch effects, just a tiny little bit of room for improvement.

Today was just on the studio speakers, but on Monday I'll move to a pair of electrostatic headphones, and then things will become more obvious.

**Comment by nettings** [comment]
@christf, above you suggested to "scale the audio" to a factor of 1.4 or so to make pitch issues audible. Can you explain in a few lines what you mean precisely? I'd like to verify this for myself.

@mikebrady, from your explanations above I seem to understand that soxr resampling isn't continuously adaptive, but looks at high and low buffer watermarks and then applies a short resampling sprint to bring the audio back to the center of the buffer. If that's true, here's a low-hanging fruit for improvement, I guess... I hope I can understand how soxr works in shairport-sync - my hope is that it will enable me to make the JACK backend work at other frequencies than 44k1 - it doesn't not make any computational difference whether you resample by a factor of 0.99995 or 0.91875+/-5 (the latter would give 48k).

**Comment by mikebrady** [comment]
Thanks for the very interesting post, @nettings. Shairport Sync does indeed work as you have outlined above -- see the [second paragraph here](
https://github.com/mikebrady/shairport-sync/issues/683#issuecomment-469206972) for a bit more detail. Unfortunately, [the link]( https://kokkinizita.linuxaudio.org/linuxaudio/zita-ajbridge-doc/quickguide.html) you reference above seems to be down right now. IIRC, it referenced a paper that I had a quick look at some time back. My memory of it was that the situation described was much more general than the situation within Shairport Sync (when it comes back up, I'll have another look at it and update this).

Is it possible that the "slower oscillation at higher amplitude" is caused by the PLL's control system? The experience I have had with Shairport Sync is that there can often be long term variations in the drift between the two clocks -- minutes to hours.

**Comment by christf** [comment]
On Sat, Mar 09, 2019 at 03:11:11AM -0800, Mike Brady wrote:
>Thanks for the very interesting post, @nettings. Shairport Sync does 
>indeed work as you have outlined above -- see the [second paragraph 
>here](
>https://github.com/mikebrady/shairport-sync/issues/683#issuecomment-469206972) 
>for a bit more detail. Unfortunately, [the link]( 
>https://kokkinizita.linuxaudio.org/linuxaudio/zita-ajbridge-doc/quickguide.html) 
>you reference above seems to be down right now. IIRC, it referenced a 
>paper that I had a quick look at some time back. My memory of it was 
>that the situation described was much more general than the situation 
>within Shairport Sync (when it comes back up, I'll have another look at 
>it and update this).
>
>Is it possible that the "slower oscillation at higher amplitude" is 
>caused by the PLL's control system? The experience I have had with 
>Shairport Sync is that there can often be long term variations in the 
>drift between the two clocks -- minutes to hours.
After some more listening I think I know what is going on a little 
better:
* I actually was hearing a changed pitch due to soxr
* but not in the range of 0.01 but much more. This was due to the player 
  IO being overloaded and scaling a lot in a bursty fashion. It sounded 
  like slowing down a vinyl record on the turntable and speeding it up 
  afterwards.

Illustrating the "scale by factor 1.4" part: Well, if you use libsoxr to 
apply a factor of 1.4 to say 960 samples that are meant to be played at 
48000 samples a second, this will lead to 1344 output samples that are 
meant to be played at 67200 samples a second. If you continue to play 
them back at 48000Hz then you will hear a change in pitch.

I cannot hear the tiny adjustments that happen during regular playback.  
OTOH if everything is perfect, then there would not be a need for 
adjustments at all.




-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments
