### ISSUE TITLE
MQTT main topic and status

### ISSUE THREAD

**Issue by ophilips** [mikebrady/shairport-sync#820]
I have multiple instances of shairport-sync running in my network and it is somehow confusing to organize all of them because they are not combined. At the moment the structure looks like this with shairport-sync:

`/generic.name/album`

`/Wohnzimmer/album`
`/Wohnzimmer/artist`
`/Wohnzimmer/cover...`

`/Schlafzimmer/album`
`/Schlafzimmer/artist`
`/Schlafzimmer/cover...`

As an enhancement I would suggest to add a main topic "shairport-sync" so that they show up combined under this topic. Also I would remove the first "/" and maybe convert topics to lower case to match the style of other systems:

**`shairport-sync/generic.name/album`
`shairport-sync/wohnzimmer/album`
`shairport-sync/schlafzimmer/album...`**

`homeassistant/sensor/xiaomi/state`
`zigbee2mqtt/bridge/config/permit_join`

As a second enhancement it would then be useful to publish the actual state instead of publishing empty messages to the topics `/play_start` or `/play_end` :

**`shairport-sync/generic.name/state`**
with payloads **playing, paused or stopped** so that it is always possible to read the status.

What do you think?

**Comment by mikebrady** [comment]
I wonder what Till Zimmermann @tillz thinks...

**Comment by tillz** [comment]
To the first part of your question: This is already possible by setting the topic for this instance manually, as shown in the [Example Config](https://github.com/mikebrady/shairport-sync/blob/development/scripts/shairport-sync.conf#L209):
```
topic = NULL; //MQTT topic where this instance of shairport-sync should publish. If not set, the general.name value is used.
```
It's ok to set multiple hierarchy levels here, for your requirements it could be
```
topic = "shairport-sync/wohnzimmer";
```
I'd like to keep the topic default to the instance's name, because every mqtt setup is different, and most setups would need a manual configuration anyway, so it's best to keep it simple.

To the second part: Yes, this would be indeed useful. However I don't fully understand the different states a connection can be in.
@mikebrady Do you have an idea where this could be implemented? Does the `activity_monitor.c` support these three modes/states, or only 'device connected' vs. 'device disconnected'?

**Comment by mikebrady** [comment]
Thanks @tillz. Shairport Sync ("SPS")  can get information via a DACP connection from the audio client. This includes the state of the audio client, is stored in a structure called the metadata_store, and is used by the D-Bus and MPRIS interfaces. However, DACP-originated information is not currently published as metadata tokens, so it is not available for the MQTT client to pick up. I could look at publishing it, so that the MQTT client could automatically pick it up, but it might take a little time to rationalise the code.

Meantime, SPS itself generates the metadata corresponding to `play_start`, `play_end`, `active_start`, `active_end` etc. to reflect the state of SPS itself, not the state of the audio client. It also generates metadata corresponding to `play_flush` and `play_resume` which, together with `play_start` and `play_end`, could be used to determine is SPS was in the `play`, `pause` or `stopped` mode. However, the data is a bit noisy -- you might get a pause without a corresponding resume, and so on.

**Comment by ophilips** [comment]
I think it would be best to just publish the state of shairport-sync and not the client.

**Comment by tillz** [comment]
@mikebrady So you mean one could (internally) send the metadata originated from [dacp.c, L520](https://github.com/mikebrady/shairport-sync/blob/master/dacp.c#L520)?
I started adding mqtt as a metadata watcher too, which should be possible, but the mqtt part also does metadata parsing on it's own. Therefore I think it's more concise to keep the parsing at one location instead of mixing the Metadata-Hub-Parsed and MQTT-Parsed together.
So if you're ok with that, I'd have a look at the code in dacp.c linked above and try to publish this like other metadata (then the traditional, FIFO/UDP metadata mechanism could use it as well)
@ophilips Did you manage to get the topic-prefix working?

**Comment by mikebrady** [comment]
@tillz Yes, agreed, you could try this. I'm not sure, but maybe the whole design is unwieldy.

**Comment by mikebrady** [comment]
Closing this issue. Please feel free to open another one if necessary.
