### ISSUE TITLE
stuffing with soxr-0.1.3 and clicks/distortions

### ISSUE THREAD

**Issue by mistepien** [mikebrady/shairport-sync#834]
The system is buildroot with musl 1.1.21, linux kernel 4.19.18 and alsa 1.1.7 running on x86 (32 bit).
Stuffing with soxr causes distortions, with basic stuffing everything is fine.
I attaches file log.
[noise.txt](https://github.com/mikebrady/shairport-sync/files/3076182/noise.txt)

**Comment by mikebrady** [comment]
Thanks. Could you tell us more about the hardware please? It looks like a Dell OptiPlex FX170 at 1.6 GHz, which should be more than powerful enough. However, the output rate, starting at 44,163.94  and ending at 44,141.69, is pretty far off. It also looks like there is a very large drift between the source, iTunes on a PC and the device – around 700 ppm.

Would you be kind enough to log the statistics with soxr interpolation off for a while, maybe 10 minutes, so that we can get an idea of the true drift.

**Comment by mistepien** [comment]
ntp is set up. is it possible that ondemand cpufreq interferes?

**Comment by mikebrady** [comment]
Thanks. If the ondemand stuff could be set to something static, e.g. `performance` to see if it makes a difference, that would be good, yeah. `soxr` interpolation takes lots of horsepower, and if the device has decided to run very slowly, it might be the problem. If it clears the problem, then it might be worth experimenting further.

**Comment by mistepien** [comment]
ok, I switched to performance but it didn't help. Frankly speaking I have no idea what is wrong. This time I used iphone (not windows in virtualbox) but the result is virtually the same. My network is gigabit, AP is running on openwrt, cpu usage on AP is very low.
[sox_performance.txt](https://github.com/mikebrady/shairport-sync/files/3076628/sox_performance.txt)

**Comment by mistepien** [comment]
libsoxr is built with such options: -DWITH_OPENMP=ON  -DBUILD_TESTS:BOOL=OFF -DWITH_LSR_BINDINGS:BOOL=OFF -DWITH_PFFFT:BOOL=OFF

mpd uses libsoxr extensively and the are no problems at all.

**Comment by mistepien** [comment]
what maybe the reason of drift? receiver (buildroot machine) uses ntpd, I believe that iphone too.

**Comment by mikebrady** [comment]
Thanks. I'll have to think of a way of trying to "zero-in" on the problem. Meantime, I notice that the output rate is much more stable and accurate, and the relative clock drift between the sender and receiver is a very satisfactory 2.63 part per million. When I have to [build libsoxr](https://github.com/mikebrady/shairport-sync/blob/master/LIBSOXR.md), I don't specify any options, but then, it's being built for the same platform – it's not being cross-compiled. When building [libsoxr for OpenWrt](https://github.com/mikebrady/libsoxr-for-openwrt/blob/master/Makefile), these are the options:
```
CMAKE_OPTIONS:= -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=0 -DBUILD_EXAMPLES=0
CMAKE_OPTIONS+= -DHAVE_WORDS_BIGENDIAN_EXITCODE=$(if $(CONFIG_BIG_ENDIAN),0,1)
```

**Comment by mikebrady** [comment]
To be honest, I don't know why the drift is there. Maybe it's within tolerance at both ends or something.

**Comment by mistepien** [comment]
But -DBUILD_SHARED_LIBS=OFF is nonsense, how such non-built library may be useful for mpd or shairport-sync?

**Comment by mikebrady** [comment]
Hmm. All I can say is that it works.

**Comment by mikebrady** [comment]
Actually, the official version of [libsoxr for OpenWrt](https://github.com/openwrt/packages/blob/master/libs/libsoxr/Makefile) drops that flag — I’m sure Ted Hess is right!

**Comment by mikebrady** [comment]
I have added some code to Shairport Sync to time how long it takes to do `soxr` interpolation, and to report it as a `soxr_delay_index` –  it is basically the time to do two `soxr` interpolations at full speed, expressed in milliseconds. Thus, the lower the `soxr_delay_index` the better. (BTW, in operation, `soxr` interpolations can take around twice as long as measured here, possibly due to other things going on in the application at the same time.)

Build Shairport Sync from the `transit` branch in the usual way an remember to include support for SoX interpolation with the `–with-soxr` interpolation flag. You'll get the `soxr_delay_index` at debug verbosity 1 or above. If the `soxr_delay_index` is 30 or less, `soxr` is probably okay; otherwise it's safer to select `basic`.

In addition to `basic` and `soxr`, you can now select `auto` interpolation.  If so, `soxr` or `basic` will be chosen on the basis or `soxr_delay_index` being 30 or lower. A first generation Raspberry Pi B has an index of about 22. A TP-Link WR710N running OpenWrt has an index of around 750!

**Comment by mistepien** [comment]
"auto" options works like a charm.

**Comment by mikebrady** [comment]
That’s great, thanks. Any idea of the `soxr_delay_index` of the device?

**Comment by mikebrady** [comment]
Closing this, as the issue has been resolved.
