### ISSUE TITLE
Help needed with basic install & with HifiBerry DAC+

### ISSUE THREAD

**Issue by UngluedChalice** [mikebrady/shairport-sync#849]
I'm trying to find the best place to post this (and I couldn't find how to tag this "Help Needed," as this is not a bug report). If there is a better place to get basic help, please direct me there!

I'm trying to get Shairport-sync running on my Raspberry Pi 3 B with Rasbian Stretch (with desktop and recommended software). I have updated rasbian after installation off of a wipe SD card. I have followed the [basic instructions here](https://github.com/mikebrady/shairport-sync/blob/master/INSTALL.md). The only part I'm not sure about is the config file. I used nano to edit the file and added these lines right below 
```
general =
{
```
Below is what I added:
```
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:0";
  mixer_control_name = "PCM";
```

And then there is a bunch of notes and at the very end a closing ```}```.

Then I finished the instructions step by step. When I open my iPhone or Macbook, no AirPlay device shows up. I know where to look on my iPhone to use AirPlay as I used to have some sort of AirPlay simulator running on my Pi until it just stopped working. I know the RaspPi is up and running and connected to wifi because I'm typing this on it right now. A month or two ago I was trying to install Shairport-sync and I was able to get it up and running but no sound. Now I can't get anything.

My network consists of some Ubiquiti eqipment:; USG 3P, CloudKey, 2xUAP-AP-PRO, and a two non-unifi switches. I am also running another Raspberry Pi with Pi Hole and OpenVPN and Wireguard (which doesn't seem to actually work). Not sure if any of this is relevant, but figured I should include it as I don't know what I'm doing here. 

I know very little about all this stuff, but I want to learn. I just don't even know how to troubleshoot at this point. I've read through the troubleshooting article but nothing there seems like it applies. I tried running ```sudo ufw disable```but i just got a ```command not found``` error.

Any ideas on how to figure out what I'm doing wrong?

**Comment by mikebrady** [comment]
Well, you need to investigate what's happening systematically. Here are a few steps, and we might expand these later:
1.  Is it running? Find out if Shairport Sync is actually running. If you enter the command:
```
$ sudo systemctl status shairport-sync
```
you should get something like:
```
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-05-11 14:17:12 IST; 1 day 1h ago
 Main PID: 480 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─480 /usr/local/bin/shairport-sync
```
... you can see that its status is `active (running)`. If it's not running, you should investigate why.

2. Is the Shairport Sync AirPlay service advertising itself? To find out if Shairport Sync's AirPlay service is being advertised to the network, you need to install `avahi-utils`. In there, there's a tool called `avahi-browse` which you can use to check that Shairport Sync is advertising. If you enter the command:
```
$ avahi-browse -art | grep -C 2 "AirTunes"
```
...you should see something like this:
```
   txt = ["pw=false" "txtvers=1" "ch=2" "cn=0,1" "ek=1" "et=0,1" "sv=false" "da=true" "sr=44100" "ss=16" "md=0,1,2" "vn=65537" "tp=TCP,UDP" "vs=105.1" "am=ShairportSync" "fv=76400.10" "sf=0x4"]
=  wlan0 IPv6 2D11D6B582C4@RaspberryPi3BP                   AirTunes Remote Audio local
   hostname = [RaspberryPi3BP.local]
   address = [fe80::9ca2:df6a:3cab:eb05]
   port = [5000]
...
...
=  wlan0 IPv4 2D11D6B582C4@RaspberryPi3BP                   AirTunes Remote Audio local
   hostname = [RaspberryPi3BP.local]
   address = [192.168.50.180]
   port = [5000]
```
In particular, you should see the Shairport Sync service provided by your device being advertised here. (In this case, the service is called `RasperryPi3BP`.) Once again, if this isn't happening, you need to find out why.

3. Is the AirPlay service visible on the iPhone, or whatever your music source is? There is a free app called "Discovery" from TildeSoft for both the Mac and iOS devices. Use it to look for `Remote Audio Output Protocol` `(RAOP)` records which should include your Shairport Sync service name, like this, for example:
```
2D11D6B582C4@RaspberryPi3BP
```

 If the Shairport Sync service is running and advertising (steps 1 and 2 above) but not visible at your player, then there is a connectivity problem that you need to fix. Some of those services you are running have the capability of making the network somewhat complicated, so I guess that's where the problem lies.

**Comment by UngluedChalice** [comment]
First off, thanks for this awesome project and the help you give to people like me. 

Well, that didn't take long. The first command I ran ```sudo systemctl status shairport-sync``` resulted in an error.

```
 sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-05-12 13:18:27 CDT; 2s ago
  Process: 9699 ExecStart=/usr/local/bin/shairport-sync (code=exited, status=1/FAILURE)
 Main PID: 9699 (code=exited, status=1/FAILURE)

May 12 13:18:27 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
May 12 13:18:27 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=exited, status=1/FAILURE
May 12 13:18:27 raspberrypi systemd[1]: shairport-sync.service: Unit entered failed state.
May 12 13:18:27 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'exit-code'.
```

Then I tried to start it using ```sudo systemctl start shairport-sync``` and I tried again but got the same error. I also rebooted the Pi and tried again, but same result. So for some reason it isn't starting up. This is on a clean install of Rasbian, so nothing else has been done to this Pi. I figure I'm doing something wrong,

**Comment by mikebrady** [comment]
Good stuff. The next thing is to try to figure out why it refuses to start. So, let's try to see what it says if you run it from the command line, asking it to get a little verbose:

```
$ shairport-sync -vu
```
The `-v` is asking for the first level of verbosity, the `u` is asking to display the log in the window.
Would you be kind enough to post the response please?

**Comment by UngluedChalice** [comment]
Done! And it doesn't look good...

```pi@raspberrypi:~ $ shairport-sync -vu
fatal error: -vu: unknown option
Request to shut down all rtsp conversation threads
asking playing threads to stop```

**Comment by mikebrady** [comment]
Agh – sorry, I'm thinking of the `development` version. Omit the `u` please.

**Comment by UngluedChalice** [comment]
Well now I know what the "Close and Comment" button does! Whoops...

```
pi@raspberrypi:~ $ shairport-sync -v
fatal error: Line 57 of the configuration file "/etc/shairport-sync.conf":
syntax error
Request to shut down all rtsp conversation threads
asking playing threads to stop
```

Line 57 just has this on it ```};```

Ok, deleted that and now it has an issue with line 72. I think I'm figuring it out! Where exactly in the config file do I put this?

```// Sample Configuration File for Shairport Sync on a Raspberry Pi using the built-in audio DAC
general =
{
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:0";
  mixer_control_name = "PCM";
};
```

Because I just put it at the top right after the ```general =```

I thought everything else was just comments. But do I need to put those specific lines in specific places that match in the config file? I'm going to answer my own question and say "yes." 

So I put the ```alsa``` stuff in the place that seemed to make the most sense in the ```config``` file. Then I re-ran that command, and it pointed out a syntax error on another line. That line just had a ```{``` or a ```};``` in it. After deleting it and re-running that command, it would give me another error for a different line. Rinse and repeat. 

Now the output is this: 

```shairport-sync -v
alsa output device name is "hw:0".
Lowest dB value is a mute
Hardware mixer has dB volume from -102.380000 to 4.000000.
Version: "3.2.2-OpenSSL-Avahi-ALSA-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Raspberrypi".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 60.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 1.
use_apple_decoder is 0.
alsa_use_hardware_mute is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
loudness is 0.
loudness reference level is -20.000000
disable resend requests is off.
diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
avahi: service 'AF31192A3A11@Raspberrypi' successfully added.
```

And now I see it in iTunes and on my iPhone! And it outputs to the headphone jack on the Pi! I have spent months brooding over this and trying to get it to work. I had a feeling it was that config file, I just had no idea what I was doing wrong because I misunderstood the instructions and just put 
```
// Sample Configuration File for Shairport Sync on a Raspberry Pi using the built-in audio DAC
general =
{
  volume_range_db = 60;
};

alsa =
{
  output_device = "hw:0";
  mixer_control_name = "PCM";
};
```
all at the top instead of moving the ```alsa``` stuff down. I wonder if anyone else has made the same mistake? It's hard to write instructions like these because you have such a huge range of skill in the people using them. 

Now I just gotta figure out how to output it to the XLR outputs. I know the XLR output, cable, and speaker works as I can use the pi to play a YouTube video and it works.

How do I get Shairport-Sync to output to the ```snd_rpi_hifiberry_dacplus```? When I look at the Audio Device Settings on the Rasbian desktop the sound card is listed as ```snd_rpi_hifiberry_dacplus (Alsa mixer) (Default)``` 

Thanks again for the help! This is making my day!

**Comment by mikebrady** [comment]
That's all good. To get the name to use, you need the program called `alsamixer`. If it's not on the system, install the package called `alsa-utils`. Launch it and then look at the cards sing the function key F2.
<img width="654" alt="image" src="https://user-images.githubusercontent.com/4265913/57587858-e80c9080-7503-11e9-9e0e-bbf5724dfd44.png">
You'll get something like this, where there are three soundcards:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/4265913/57587879-18ecc580-7504-11e9-88de-b4a29d7e908b.png">
To select the third one, card number 2, you would use the device name `"hw:sndrpihifiberry"`. You'll have to do something similar.
You can use `alsamixer` to see the names of the mixers (i.e. volume controls) by selecting the card using function key F6.

**Comment by UngluedChalice** [comment]
Ok, I was able open up the alsa mixer but no dice when I changed the ```hw``` in the ```config``` file. 

[Here's the screenshot.](https://imgur.com/2VDyZaD)

Here's the error:

```
pi@raspberrypi:~ $ shairport-sync -v
alsa output device name is "hw:sndrpihifiberry".
fatal error: Failed to find mixer element
Request to shut down all rtsp conversation threads
asking playing threads to stop
waiting for a mutex, maximum expected time of 10000 microseconds exceeded "audio_alsa.c:906".
```

**Comment by UngluedChalice** [comment]
Just to document what I'm doing:

1. I edited ```/boot/config.text``` and removed the ```dtparam=audio=on``` line per [the HifiBerry website](https://www.hifiberry.com/build/documentation/configuring-linux-3-18-x/). I also added ```dtoverlay=hifiberry-dacplus``` to the same file, per the same website. 

2. I also followed the steps to configure ALSA by putting this in ```/etc/asound.conf```

```
pcm.!default {
  type hw card 0
}
ctl.!default {
  type hw card 0
}
```
Now I get this:

```$ sudo systemctl status shairport-sync
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-05-12 19:57:38 CDT; 8min ago
 Main PID: 451 (shairport-sync)
   CGroup: /system.slice/shairport-sync.service
           └─451 /usr/local/bin/shairport-sync

May 12 19:57:38 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
May 12 19:57:38 raspberrypi shairport-sync[451]: fatal error: Failed to find mixer element
```
So there is something called "mixer element" that is missing. 

3. So I google "hifiberry "mixer element" shairport-sync" and[ONE result comes up](https://forums.pimoroni.com/t/pi-zero-phat-dac-shairport-sync-failed-to-find-mixer-element/3522/3). 

I edited the Shairport-sync ```config``` file and commented out the ```mixer_control_name.``

```
// These are parameters for the "alsa" audio back end.
alsa =
{
  output_device = "hw:sndrpihifiberry";
// mixer_control_name = "PCM";
};
```
### **And now it works!** 

Thank you SOOO MUCH for your help! If there is anything you see that I messed up or need to fix/adjust to get the full power of shairport-sync, let me know!

**Comment by mikebrady** [comment]
That's great. A couple of things:
1. Removing the `dtparam=audio=on` line from `/boot/config.txt` disables the built-in DAC. When you look at the list of devices using `alsamixer`, there is one less device, and the numbering of the devices may change. But since you are not using the built-in DAC, it's presence or absence makes no difference.
2. Configuring ALSA using `/etc/asound.conf` as you have done makes the `hw:0` the default output device. But you are not referring to the `default` output device in `/etc/shairport-sync.conf` – you are referring to the device called `hw:sndrpihifiberry`. So this configuration is not relevant to your situation.

Neither of these changes have any direct bearing on your Shairport Sync setup. So, if it was up to me, I would not make either change, simply on the grounds of leaving stuff alone where possible.

Now, regarding the `mixer_control_name` stuff, I'm glad you got past it. However, there may be something more you can do. Let me try to explain:
* As well as having an output Digital to Audio Converter (DAC), some sound cards also have a "mixer" or an "attenuator" – basically a volume control. If a card has a mixer, then it's a good idea to use it for two reasons:
1. If you hook it up to the AirPlay volume control, your AirPlay device directly controls the mixer that governs the maximum output level of your DAC. 
2. If you don't hook it up to the AirPlay volume control, then you have no control over the maximum level of your output card's output. Instead, the maximum output level will be determined by whatever arbitrary value the mixer happens to have from whatever used it before – not a good situation, you'll agree.

So, to hook up the mixer, you need to find out if it exists, and if so, what name it has. You can use `alsamixer` for this. Here are some screenshots:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/4265913/57605105-c809bb00-755d-11e9-91f5-f3f048be35e4.png">

The screenshot above shows the DAC that's built in to the Raspberry Pi, and you can see that it has a mixer called "PCM".
<img width="570" alt="image" src="https://user-images.githubusercontent.com/4265913/57605174-f8e9f000-755d-11e9-8fe2-ad5483bc68d6.png">

The screenshot above shows a DAC with no mixer at all.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/4265913/57605156-ecfe2e00-755d-11e9-9bef-900ba868db34.png">

The screenshot above shows a USB DAC with three controls in it – the mixer for output is called `Speaker`.

Shairport Sync can use a mixer that has a decibel (dB) scale. You can see that both the `PCM` and the `Speaker` mixers are reporting decibel gain values (`[dB gain:…]`), so they are suitable.

To use an output device's mixer, enter its name as the `mixer_control_name` in `/etc/shairport-sync.conf`, e.g.
```
mixer_control_name = "Speaker";
```
(The name is case-sensitive.)


One other important troubleshooting thing to look out for is to ensure that the output device is unmuted. Looking again at the screenshots, you'll see the bottom box below each mixer graphic is either `00` or `MM`. If the latter, it means that the mixer is muted – no audio can get through. Shairport Sync will not, by default, attempt to control the mute state of a mixer, so if it is muted, then it will stay muted. Therefore, make sure to unmute the device (select it and type `m` to toggle its mute state).

**Comment by UngluedChalice** [comment]
You and I think alike: if there is no need to muck with stuff, don't bother. I went back and undid the changes I made that you said don't matter. After each step I rebooted the Pi and tested the speakers, and they still work fine. 

I found [a little documentation from the HifiBerry people](https://www.hifiberry.com/build/documentation/mixer-controls-on-the-hifiberry-boards/) about their mixer controls. I have the DAC+. I'm not sure how to figure out what to set the "Digital" level at. Any tips on this? I basically have three ways to adjust the loudness: the gain knob on the back of the speakers, the volume buttons on my iPhone, and the AlsaMixer controls. How do I go about setting these properly?

The HifiBerry documentation (linked above) says the only thing I need to worry about is the one that says "Digital." There are a TON of controls on there - [they barely fit on my screen for a screenshot.](https://imgur.com/hgrRSlj) Sorry for the imgur links, I can't see a way to post an inline image here on GitHub.

You wrote:
> To use an output device's mixer, enter its name as the mixer_control_name in /etc/shairport-sync.conf, e.g.
>```mixer_control_name = "Speaker";```

So for mine I would just put ```mixer_control_name = "Digital";``` because it says "Digital" on that bottom row in my screenshot?

Thanks again for all your help, I really truly appreciate it. Any other settings in my AlsaMixer screenshot I need to worry about? 

Also, one of the Shairport-Sync features I've read about is:

>Better Volume Control — Shairport Sync offers finer control at very top and very bottom of the volume range. See http://tangentsoft.net/audio/atten.html for a good discussion of audio "attenuators", upon which volume control in Shairport Sync is modelled. See also the diagram of the volume transfer function in the documents folder. In addition, Shairport Sync can offer an extended volume control range on devices with a restricted range.

Am I taking advantage of this by default?

**Comment by mikebrady** [comment]
Okay. Taking the items in order.

First, it's good you reset those settings – less to have to worry about in the future.

Second, the HifiBerry documentation is good, but seems to have a slight error in it. So, this seems to be a bit misleading:
> While there are a lot of mixer controls on the DAC+, you only need to care about one named “Digital”.
> ```
> amixer sset PCM 90%
> ```
> All other mixer control allow access to low-level functions of the sound chip, you won’t need them. Unfortunately it is not easy to remove these controls as they are part of a kernel driver that is not maintained by us. 


I think it would make more sense if it read:
> While there are a lot of mixer controls on the DAC+, you only need to care about one named “Digital”.
> ```
> amixer sset Digital 90%
> ```
> All other mixer control allow access to low-level functions of the sound chip, you won’t need them. Unfortunately it is not easy to remove these controls as they are part of a kernel driver that is not maintained by us. 
>

Third, on a Mac at least, pasting a PNG image into the edit window will upload it and allow it to be displayed in line.

Fourth, that screenshot looks a lot like this one, from a very good [IQaudIO](http://iqaudio.co.uk) Pi-DigiAMP+. 

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/4265913/57831593-75264280-77ad-11e9-974d-d5435ffa929d.png">

The important control is indeed the one called `Digital`, and you can see that it offere a decibel scale, so you should – as you figured out – put the following line into the `alsa` group of settings:
```
mixer_control_name = "Digital";
```
When you do that, and have rebooted or restarted, open the same mixer in `alsamixer` and play some music, say from your iPhone, through Shairport Sync. If everything is set up correctly, when you change the volume control on the iPhone, you'll see the volume graphic change in the mixer graphic. You don't have to worry about setting it to any particular value – the full range will be used automatically.

Fifth, yes, if the mixer has been hooked up properly, then it will be using the fancy transfer function to make the volume control a little nicer at the top and bottom ends.

**Comment by UngluedChalice** [comment]
Thanks so much! Everything is all set and it all works as expected!
