### ISSUE TITLE
Pulseaudio as backend getting connection refused error

### ISSUE THREAD

**Issue by rsm123** [mikebrady/shairport-sync#850]
Thank you for the amazing work with the shairport-sync!
When i'm using pulseaudio as backend on raspberry pi3 (using output_backend = "pa";), I get:

fatal error: failed to connect to the pulseaudio context -- the error message is "Connection refused"

Is there any way to resolve this?

**Comment by mikebrady** [comment]
Thanks for the kind words. Regarding the problem, I don't know. However, remember that the pulse audio system by default provides a "user service" rather than a "system service" – see #843. Could that be the issue?

**Comment by master0v** [comment]
Here is a way to make it work: https://github.com/mikebrady/shairport-sync/issues/519#issuecomment-363803831
It was too complicated for me, so I just run it as a user from command line.

**Comment by Lyndwil** [comment]
> Here is a way to make it work: [#519 (comment)](https://github.com/mikebrady/shairport-sync/issues/519#issuecomment-363803831) It was too complicated for me, so I just run it as a user from command line.

I looked at the solution provided here but it wasn't applicable for my use. I want the service to run before logging in to the system, which would require shairport to continue to run as a system service as opposed to a user service. After some digging it looks like all the issue is an environment variable which is set when run manually which is unset when run by the system service.
To get shairport and pulseaudio to communicate without demoting shairport to a user service try this instead.

Run this as your user, the one that you can manually start shairport with:
```
echo $XDG_RUNTIME_DIR
```
This is the directory of where shairport will search for pulseaudio socket.

Now we need to modify the .service file provided by shairport:
```
sudo systemctl edit shairport-sync.service
```

Enter the following lines into the file (replacing with your username and the pulseaudio socket dir found above):
```
[Service]
Environment="XDG_RUNTIME_DIR=<PA SOCKET DIRECTORY>"
User=<USERNAME>
```

For example my override looks like this:
```
[Service]
Environment="XDG_RUNTIME_DIR=/run/user/1000" 
User=myusername
```

Save this conf and reload the systemd daemon:
```
sudo systemctl daemon-reload
```

and shairport should run as a system service without crashing now!
