### ISSUE TITLE
Shairport-Sync with IQaudio Rotary volume control

### ISSUE THREAD

**Issue by NickSutton** [mikebrady/shairport-sync#891]
Hi Mike,

Could you just confirm that there’s no reason a physical rotary controller shouldn’t be able to adjust the volume as per https://github.com/iqaudio/tools

Thanks very much,
Nick

**Comment by giggywithit** [comment]
I would imagine that you could easily setup a USB volume controller to control the mixer

**Comment by mikebrady** [comment]
Yes, it should work. You should probably tell Shairport Sync to ignore the volume control information data coming from the source so that audio is always passed through to the mixer at full volume.

Another recent possibility is to get the encoder to send `dbus` messages to Shairport Sync so that it will send `volumeup` and `volumedown` commands to the source and thereby implement remote control the source’s volume. I don’t have a rotary controller so I haven’t tried it, but it should work.

**Comment by NickSutton** [comment]
Ahh, but is there a way to retain control of the volume from the device but with a hardware ‘override’ on the speaker?

I thought it would be quite helpful if some starting playing something I didn’t like!

I’ll look in to the dbus messages when I next get a chance.

Thanks again,
Nick

On 11 Aug 2019, at 07:23, Mike Brady <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, it should work. You should probably tell Shairport Sync to ignore the volume control information data coming from the source so that audio is always passed through to the mixer at full volume.

Another recent possibility is to get the encoder to send dbus messages to Shairport Sync so that it will send volumeup and volumedown commands to the source and thereby implement remote control the source’s volume. I don’t have a rotary controller so I haven’t tried it, but it should work.
