### ISSUE TITLE
Sync issue with Kodi Live TV (TVHeadend)

### ISSUE THREAD

**Issue by SylvainCecchetto** [mikebrady/shairport-sync#893]
Hi,

First of all thank you for your work.
I use my linux server with Shairport-sync as a speaker for my MacBook, my iPhone and my Apple TV.

On my Apple TV and my MacBook I use Kodi. When I watch a local movie sound and video are synchronized but when I watch a live TV channel Kodi struggling to sync video and sound. Sometimes by waiting 10 seconds I have video and audio synchronized but sometimes I fall in an invite "play-pause" of the video and sound and Kodi never comes to sync audio and video.

My live TV channel stream come from my TVHeadend backend server (terrestrial television with HDHomeRun) then Kodi use the official TVHeadend client plugin to connect with the backend.

Do you know where the problem is coming from?
Also, who is responsable of the synchronisation ? Shairport-sync, the video player (kodi) or the video "streamer" (TVHeadend)?

I can provide log from any of the software if needed, I can also perform tests if needed ;-)

Thank you!

**Comment by SylvainCecchetto** [comment]
Thank you for your answer and for the details.
Just to be sure that I understand correctly, this is the player that send timing metadata with the audio stream, then Shairport Sync does the necessary to sync the audio output?
Shairport Sync has no way to pause or slow down the video playback of the player (Shairport Sync receive informations from the player but it can not send command to player to ask him something?).
BTW, (and maybe that can help me to understand), why VLC sound is delayed with the video when you play something on VLC?
Because this delay not exists with a video from youtube/Safari.
Thank you very munch!

**Comment by mikebrady** [comment]
in The case of the Mac, when the audio output is directed to an AirPlay 1 device such as Shairport Sync, it seems to be macOS that sends the audio and necessary timing and synchronization information to the player. 

AirPlay 1 introduces a delay of between 2.0 and 2.25 seconds. When an application like Safari or YouTube (or the QuickTime player) detects that it is playing audio via AirPlay, it delays the video by the same amount — 2.0 to 2.25 seconds — so that the video and audio are in synchronization. 

VLC does not do this, so the audio seems delayed. There is a setting in VLC that you can use to delay the video manually.

It seems as if Kodi doesn’t do this properly for a live stream.

**Comment by SylvainCecchetto** [comment]
Thank you very munch for the details. I will close this issue because is definitely not an issue of Shairport ;-)
I will continue my tests directly with Kodi.
