### ISSUE TITLE
WAN possibility?

### ISSUE THREAD

**Issue by jshep321** [mikebrady/shairport-sync#899]
Has anyone attempted to run this over WAN/internet?  I'm interested in syncing audio over a few sites and was wondering if it was feasible, perhaps with a VPN.  

My idea is to use an OpenVPN TAP and a maybe a slightly tweaked routing scheme (not sure this will be needed).  There might be other ways to make this work better such as VLAN, etc. but I plan to have only a pi zero at the remote site(s), so MIPS and functionality will be limited.

Additional buffer delays (>2.25s) are ok.

Thanks!

**Comment by lionep** [comment]
I never tried, but maybe have a look at mdns repeater, to allow the discovery over VPN.

**Comment by jshep321** [comment]
@lionep Thanks!  I was previously reading about that also.  Pro: That would keep the VPN traffic a lot cleaner (by not forwarding Data link layer messages).  Con: unclear about introduced delays (and even worse for this application--inconsistent delays).  From my googling, etc., I've not found anyone that has attempted this, much less had success.  If I get bored enough one day, I'll blaze the trail...

**Comment by jafd** [comment]
I've tried Avahi in reflector mode so that a NAT'd subnet could get to my speakers, and I was also setting up a VPN to my home and wanted the road warriors to be as transparently on the LAN as it got. It didn't quite work, and the local network got duplicate and triplicate entries for all my other hosts advertising over mDNS. I'm still unsure what exactly I did wrong. 

Later the lockdown kicked in, and being able to VPN to my home became kind of pointless... at least for the time being.

This is for the record about people who have attempted it so far. ;-)
