### ISSUE TITLE
DBUS volume int not working

### ISSUE THREAD

**Issue by corrpel** [mikebrady/shairport-sync#930]
Hi Mike,
I am trying to synchronize amixer hw volume with shairport sync hw volume using:

```
dbus-send --system --print-reply --type=method_call --dest=org.gnome.ShairportSync '/org/gnome/ShairportSync' org.gnome.ShairportSync.AdvancedRemoteControl.SetVolume int32:10
```
Simple remote `VolumeUp` and `VolumeDown` is working, but not if I try values like in the example used above.
If this bug cannot be resolved, can shairport-sync sync the client volume when changing volume in alsamixer or amixer?
Please note that I am using HW volume in shairport-sync. When I change the volume on the iPhone I can see in changing in alsamixer too.
Thank you.

Cornel

**Comment by corrpel** [comment]
I just saw #777 looking for something else :)
So, now i understand that is not working from IOS.
But, can we sync alsavolume to shairport?
Thanks.

Cornel

**Comment by mikebrady** [comment]
Thanks for the posts.

The core of the problem is that only iTunes provides the functionality to allow the `AdvancedRemoteControl` stuff to work. You can check to see if `AdvancedRemoteControl` is available using the command:

```
dbus-send --print-reply --system --dest=org.gnome.ShairportSync /org/gnome/ShairportSync org.freedesktop.DBus.Properties.Get string:org.gnome.ShairportSync.AdvancedRemoteControl string:Available
```
which will return a `true` or `false`.

Unfortunately, the new Mac `Music` app replacing iTunes appears to have no remote interface whatever (at least as far as is known).

Without the functionality needed for `AdvancedRemoteControl`, there is no facility whereby volume levels can be sent back to the client, so the possibility of synchronising a volume level set using `alsamixer` or `amixer` back to the client doesn't arise – it's a limitation of the client, not of Shairport Sync.

**Comment by mikebrady** [comment]
[Update] Some good news – the Music app on macOS has restored the old iTune remote interface, so Shairport Sync's `AdvancedRemoteControl` interface works again, now with macOS's Music app.
