### ISSUE TITLE
Video sync issues with new update

### ISSUE THREAD

**Issue by Aronkniseley** [mikebrady/shairport-sync#945]
Hey Mike - 

I recently updated to the latest Shairport-sync build and now I'm having a funny sync issue when sending audio from a video source over the network for shairport.

Every so often video playback will start without waiting for shairport-sync to sync up with it so I end up with video that's about 2 seconds ahead of the audio.  This happens most noteably when sending the audio from an apple tv (because it's what I use most) but will also happen when I'm watching a video in VLC and sending the audio straight from my computer to shair-port. 

Doing a reboot on the raspberry pi and restarting the video will solve the problem temporarily but after a few hours of up-time and/or pausing the video and restarting it will happen again.

Seems like there is some sort of handoff missing between the source and shairport-sync.

Has anybody else experienced this issue and solved it?

**Comment by mikebrady** [comment]
Thanks for the post.
As you probably know, AirPlay introduces a delay – a "latency" – between when audio is sent from the source and when it is played. The delay is negotiated between the audio source and the AirPlay audio player. Usually the latency is two seconds. Sometimes, it is around 2.25 seconds.
When a video is being played and its audio is being played via AirPlay, compatible video players will delay the video by the exact amount of the AirPlay latency so that the audio and the video are both delayed by the same amount and therefore appear in sync. Occasionally, this seems to get messed up, and of course some apps are not compatible with Airplay.
Anyway, overall, I haven't noticed any particular change in the recent update.
