### ISSUE TITLE
Low volume compared to raspotify

### ISSUE THREAD

**Issue by microfx** [mikebrady/shairport-sync#949]
Hey!

I am using your great implementation together with Raspotify. Sadly shairport is not as loud as raspotify so it can be dangerous because it can get too loud easily - so I'd rather have the speakers set to a lower level - right now this would mean that I don't have enough headroom for airplay if I level it so raspotify is safe.

Any idea what this could cause?

Cheers

**Comment by mikebrady** [comment]
Thanks for the post. Have you hooked up the volume control on Shairport Sync?

**Comment by microfx** [comment]
I can control the volume, yes (didn‘t know that was impossible to have included)

**Comment by mikebrady** [comment]
Just to clarify: if the output device has a hardware volume control, you should use it by giving its name in the configuration file. If you don't, Shairport Sync will use its own internal software volume control. Either way, you will be able to control the volume, therefore merely being able to control the volume does not tell you whether or not you're using the hardware volume control.

If you have a hardware volume control on the output device, you can check if Shairport Sync is controlling it. Just open `alsamixer` to look at the output device. If you then play something through Shairport Sync, say from an iPhone, and if you vary the volume on the iPhone, the `alsamixer` slider should move in sympathy. If the slider doesn't move, you're not controlling the hardware volume.

Now, if there is a hardware volume control on the device and Shairport Sync is not controlling it, then it will have whatever arbitrary setting it happened to have from whatever happened before –  which could be low – and since Shairport Sync isn't controlling it, it becomes the highest level that Shairport Sync can output.

**Comment by microfx** [comment]
Alright thanks for the very good explanation. I am using a DAC (hat for pi) with a potentiometer so it‘s as you say. I guess I have to live with it.

**Comment by mikebrady** [comment]
Thanks for the update. Can you tell us more about the way the potentiometer works? Does it signal Raspotify or the Pi itself?

**Comment by microfx** [comment]
It‘s a pisound https://blokas.io/pisound/ - I also use it to produce music / record stuff. It‘s 48 kHz only though which is a bit sad (Shairport is 44,1 kHz only, iirc). Are there plans for the Airplay 2 implementation to support 48 kHz?

**Comment by mikebrady** [comment]
Thanks. It really is a potentiometer, not a rotary encoder as I had thought. So yeah, you might have to live with it. The only other thing to suggest is to use the setting `ignore_volume_control` so that audio would be delivered to the DAC at full volume, regardless of the iPhone setting...
