### ISSUE TITLE
Run python script on session start and end

### ISSUE THREAD

**Issue by Lilfaen** [mikebrady/shairport-sync#979]
Hey Guys, 

i'm trying to run a python script when starting a session, later i want it to control lights when i connect and start playing music. 

The script is working, i can run it in a terminal. But i cant seem to get it running on session start.  What am i doing wrong? 

This is the path i set:
`run_this_before_play_begins = "#!/home/pi/shairport-sync-activate/activate.py";`

and the python script starts with 
`#!/usr/bin/python`

The Script is executable, as i said above. Done with `chmod +x activate.py`

Can anybody help me?

**Comment by mikebrady** [comment]
Thanks for the post. The environment in which the script runs is very different when it’s called from Shairport Sync while it is running as a daemon. I suggest you have a look at closed issues, for example [this one](https://github.com/mikebrady/shairport-sync/issues/152) for more.

**Comment by Lilfaen** [comment]
Thanks for your reply. In the linked issue, they're talking about services and i need to run a script instead of a service. Is it still the same? 
I really don't know what to do and other issues didn't really help.. Would a python or a shell script be better? Soo many questions.

**Comment by Lilfaen** [comment]
Well, i have to apologize. 
I followed some false instructions to add 'shaiport-sync' to the 'sudo-group'. 

Now i'm using a python script and the correct path:
'run_this_before_play_begins = "#!/home/pi/shairport-script/myscript.py";'

Is 'run_this_before_play_begins' recommended or 'run_this_before_entering_active_state'? The script turns some electronics on and off.

**Comment by mikebrady** [comment]
You can use either "hook". I think `run_this_before_entering_active_state` and `run_this_after_exiting_active_state` are better though. Basically, these are "deglitched" replacements for play start/play end program hooks. 

Here is some background.

Many users use the `run_this_before_play_begins` program hook to turn on an amplifier and the `run_this_after_play_ends` hook to turn it off. A big problem is when another play session starts immediately after a play session ends, causing the amplifier to be switched off and then on again very shortly afterwards. This happens, for example, when a YouTube clip ends and the next one begins.

To get around this, the concept of an "active state" covering a sequence of play sessions is introduced. When a play session starts, the system goes active -- it enters the active state. When the play session ends, the system remains active for a period determined by the `active_state_timeout` setting, 10 seconds by default. If another play session starts before the period elapses, the system stays active; otherwise the system goes inactive -- it leaves the active state.

The program hooks `run_this_before_entering_active_state` and `run_this_after_exiting_active_state` can be used to execute programs/scripts when the system goes active or inactive. They are to be found the `sessioncontrol` group of settings.

**Comment by Lilfaen** [comment]
Thank you for your answer! I use now `run_this_before_entering_active_state` and a 30 seconds timeout. 

What are some use cases of the completion-waiting? The music starts without waiting for completion, but i think this is because shairport doesn't control the music.. So i'm wondering what this is for..

**Comment by mikebrady** [comment]
To be honest, I’m not sure how useful waiting for completion really is. 

By default, when a script is executed, the program thread playing the music does not wait for it to finish.

But of you wanted to wait, for example, for the amplifier to come on before sending music to it, you might wait for the script to complete. The delay would have to be short though.

**Comment by Lilfaen** [comment]
Ah, okay that explains a lot. Thank you very much for your time! 

And, honestly, thank you for your work! Shaiport-sync is really nice and well done!
