### ISSUE TITLE
Only a few devices can see it and for a limited time.

### ISSUE THREAD

**Issue by albertoxamin** [mikebrady/shairport-sync#994]
I have installed shariport-sync on a raspberry pi zero without wifi but with an ethernet adapter by following this [guide](https://appcodelabs.com/7-easy-steps-to-apple-airplay-on-raspberry-pi) 
The server is visible by my macbook and my iPhone (and not on the other apple devices in the house), however after a few minutes it becomes invisible.
However the status is active

```
● shairport-sync.service - Shairport Sync - AirPlay Audio Receiver
   Loaded: loaded (/lib/systemd/system/shairport-sync.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-04-15 18:17:24 CEST; 28min ago
 Main PID: 335 (shairport-sync)
   Memory: 1.8M
   CGroup: /system.slice/shairport-sync.service
           └─335 /usr/local/bin/shairport-sync

Apr 15 18:17:24 raspberrypi systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
```

But after restarting the service it becomes visible again (always only on some devices).

**Comment by mikebrady** [comment]
Thanks for the post. This looks really like some kind of a network problem.

The service (`_raop._tcp`) should be visible on all devices, and the fact that it is not is odd.

One thing to check is whether the service is being properly "advertised" on the network. The advertising is done via Zeroconf/Bonjour and requires multicast to be working.

If you install `avanti-utils` on the Pi, then using `avahi-browse`, you can check that the Shairport Sync service is being advertised at the Pi end. Then, using Discovery from TildeSoft on the iOS/Mac end, you can see it the advertised service is being seen. If it's being advertised but not seen, then it's a sign that some kind of network problem is occurring.

This can happen due to issues with the router, or (at a guess) possibly in your case, the Ethernet port itself.

**Comment by albertoxamin** [comment]
Yes, it is advertised however I noticed that after a few minutes the raspberry is no longer visible.
I hacked it with a crontab that restarts the avahi-deamon every five minutes
```bash
*/5 * * * * sudo systemctl restart avahi-daemon
```
However that results in the music stopping every five minutes, which is not ideal...

I have a crappy old router that was provided by my ISP

**Comment by mikebrady** [comment]
Hmm. It might be worth checking if the router has a firmware update...
